### ISSUE TITLE
Radio button interactive examples are problematic — you can select all options at once

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/interactive-examples#1003]
On Firefox anyway. I just tested it on Nightly v62.

See these examples:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

You can select all the options at once, and you should be able to. They all have the same name attribute value.

This is not a problem on Chrome, but it is on Firefox.

**Comment by wbamberg** [comment]
> You can select all the options at once, and you should be able to. They all have the same name attribute value.

Do you mean "should **not** be able to"? From the docs:

> A radio group is defined by giving each of radio buttons in the group the same name. Once a radio group is established, selecting any radio button in that group automatically deselects any currently-selected radio button in the same group.

...so they *should* have the same name, so they are all part of the same group, so only one is selectable. Right?

The problem seems to be that Firefox expects them to be inside a `<form>` element, or it doesn't respect this. Try copying the example in the page body:

```
<form> 
  <p>Please select your preferred contact method:</p>
  <div>
    <input type="radio" id="contactChoice1"
           name="contact" value="email">
    <label for="contactChoice1">Email</label>
    <input type="radio" id="contactChoice2"
           name="contact" value="phone">
    <label for="contactChoice2">Phone</label>
    <input type="radio" id="contactChoice3"
           name="contact" value="mail">
    <label for="contactChoice3">Mail</label>
  </div>
  <div>
    <button type="submit">Submit</button>
  </div>
</form>
```

...into the editor. It works. Remove the surrounding `<form>`. It doesn't.

**Comment by chrisdavidmills** [comment]
> Do you mean "should not be able to"? From the docs:

D'oh, yes I did mean that! That one typo scuppered the entire meaning of the issue ;-)

So yes, it looks like we'll have to add form elements into these examples at some point. Thanks for investigating.
