### ISSUE TITLE
JS editor: disable/hide Reset button unless it's needed

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#101]
This also came up in SF: people we confused about the Reset button and suggested it might be clearer if the Reset button was either hidden or disabled if the contents of the editor had not been changed. This might be a signal about what the button does.

I'm not sure if hiding or disabling is better.

**Comment by schalkneethling** [comment]
I am thinking hiding it, and then showing it on the first key-up event inside the editor. Probably with a fade-in?

I am also thinking to move to the bottom right, as apposed to its current position. The reasoning behind this is that, it is more likely for long lines of code to happen at the top, where the button can obscure the code, than at the bottom.

Thoughts @stephaniehobson @wbamberg

**Comment by stephaniehobson** [comment]
Hm, that's unfortunate. I was hoping that the reset button would signal to users that it is editable, not be confusing :/ 

Yeah, hiding it until first key up is a good idea.
