### ISSUE TITLE
Certain attributes don't work in the interactive example editor in Firefox

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/interactive-examples#1058]
So, this is true for both the accesskey example that has already been merged, and the spellcheck example that is currently in PR (https://github.com/mdn/interactive-examples/pull/1057).

When I test them on my local machine in a simple static page, they work in Firefox (e.g. the attributes have the expected effect). But when I embed them in the interactive example editor iframe, they don't work in Firefox (the attributes have no effect).

But they do work in Chrome, Safari, and Opera when embedded in the interactive example editor.

It is not just an iframe thing either. I tried embedding the examples in a simple static iframe page locally, and they work in Firefox.

**Comment by NiedziolkaMichal** [comment]
Accesskey works fine, but spellcheck doesn't. It's because of shadow dom and it will be fixed when [#903](https://github.com/mdn/bob/pull/903) is merged.
I have also filed bug report on firefox, so they can fix this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1792827

**Comment by NiedziolkaMichal** [comment]
The interactive example window no longer uses shadow dom, so both attributes are working well. Thanks for reporting it.
