### ISSUE TITLE
Use disambiguating prefix for all HTML attribute examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1065]
The example for the `style` attribute calls the resulting file "style-attr.html", to avoid a clash with the `<style>` element.

This is nice, but we should do this for all attribute examples, and use the form "attribute-style.html" to distinguish this group more clearly and to be consistent with what we have done for CSS functions: https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/transforms/meta.json#L13-L32

**Comment by schalkneethling** [comment]
@wbamberg Ah, so you are saying the following:

```
"accesskey": {
            "exampleCode": "./live-examples/html-examples/global-attributes/accesskey.html",
            "cssExampleSrc": "./live-examples/html-examples/global-attributes/css/accesskey.css",
            "fileName": "accesskey.html",
            "title": "HTML Demo: accesskey",
            "type": "tabbed",
            "height": "tabbed-standard"
        }
```

Would change to:

```
"accesskey": {
  "exampleCode": "./live-examples/html-examples/global-attributes/attribute-accesskey.html",
  "cssExampleSrc": "./live-examples/html-examples/global-attributes/css/attribute-accesskey.css",
  "fileName": "attribute-accesskey.html",
  "title": "HTML Demo: accesskey",
  "type": "tabbed",
  "height": "tabbed-standard"
}
```

And then that would apply to all entries in https://github.com/mdn/interactive-examples/blob/master/live-examples/html-examples/global-attributes/meta.json

**Comment by wbamberg** [comment]
@schalkneethling  - yes exactly! Just to be consistent. It's not a big deal but would be nice I think.
