### ISSUE TITLE
Example for <picture> doesn't do what it says it does

### ISSUE THREAD

**Issue by a2sheppy** [mdn/interactive-examples#1085]
It's designed to replace the photo when the width passes back and forth across 1000px, but because the example is constrained to a small box, that never happens.

**Comment by wbamberg** [comment]
I don't think so: the media condition is applied to the example's iframe, not the output box, and that is >1000px on my monitor at full width.

It works in Chrome and Safari:

![picture-media](https://user-images.githubusercontent.com/432915/44823103-50ecec00-abb3-11e8-91c2-262545140d81.gif)

...but not Firefox.

**Comment by a2sheppy** [comment]
Interesting. I can't get it to work in Firefox.

**Comment by ollelauribostrom** [comment]
It's working for me in Firefox 61.0.1 as well. 

However, when on a 13" laptop the picture will never change as long as the media attribute is set to `media="(min-width: 1000px)"`.  I'm guessing that my screen is simply to small. 

Maybe the default value could be changed to something like `media="(min-width: 800px)"`?

**Comment by wbamberg** [comment]
> Maybe the default value could be changed to something like media="(min-width: 800px)"?

@ollelauribostrom , that's a good idea.

**Comment by wbamberg** [comment]
> It's working for me in Firefox 61.0.1 as well.

Yes, me too! Now I check it is only not working in Nightly ¯\_(ツ)_/¯.

**Comment by wbamberg** [comment]
I think https://github.com/mdn/interactive-examples/pull/1149 fixes the only outstanding issue in this bug, so let's close it.
