### ISSUE TITLE
Make CSS and JS code match

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#110]
All syntax highlighting on MDN should match.

Currently the CSS examples and MDN's code examples use Prism with the default theme.

Two questions need to be resolved to make all 3 match:
Can we switch the JS examples to use Prism? (Are there technical reasons it does not use it currently?)
What do we want all 3 to look like? (Will and I liked Code Mirror's "eclipse" best of the Code Mirror themes)

**Comment by schalkneethling** [comment]
Prism does not have a lot of themes out of the box so comparing, the closest I get is:

Prism: http://prismjs.com/ using the default theme
Codemirror: https://codemirror.net/demo/theme.html#duotone-light

In terms of colour contrast, it is a little dodgy 

Wondering, should we go with a darker theme? No opinion on it, just throwing out there as it is an option. Perhaps a no option, option ;)

**Comment by schalkneethling** [comment]
I am sticking to the default things that ships with these because we want to surely avoid just lumping in more dependencies and kb
