### ISSUE TITLE
Missing quotation mark in try/catch example

### ISSUE THREAD

**Issue by jacobq** [mdn/interactive-examples#1117]
Attempting to run https://github.com/mdn/interactive-examples/blob/bd8a91b5dd6c85c51adce007218838d3daf1d465/live-examples/js-examples/statement/statement-trycatch.html#L3 produces:

> SyntaxError: unterminated string literal

(i.e. to reproduce the problem go to [the MDN `try...catch` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) and click "Run >")

**Comment by wbamberg** [comment]
That's the intention - it's demonstrating the use of try/catch to catch an error.

**Comment by jacobq** [comment]
:man_facepalming: I need to go home for the day, sorry. Apparently my mind is gone :laughing:

**Comment by wbamberg** [comment]
No worries - and thanks for making the effort to report it :).
