### ISSUE TITLE
Style Guide for Interactive Examples

### ISSUE THREAD

**Issue by atopal** [mdn/interactive-examples#1138]
Interactive examples in my mind should allow you to instantly see how to use something to either remind you of the usage or give you a quick first insight. The rest of the page can handle exceptions and things to look out for. 

I was looking up the a[udio element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) and can’t even see the syntax without scrolling, that to me defeats the purpose of putting it on top of the page.

I'd suggest that we come up with a Style Guide that describes best practices and can be used to review submissions.

**Comment by wbamberg** [comment]
-> https://github.com/mdn/interactive-examples/pull/1184

**Comment by wbamberg** [comment]
Based on the draft guidelines and our discussions, I've been through the HTML elements and added an annotation (column C) saying whether they are OK as they are or should have some changes, and if so what the changes should be. The notes are a bit cryptic, but in general they are things like:

* simplifying and shortening where that seemed needed, to make the examples quicker to grasp and to fit without scrolling. To do this I've recommended things like:
    * removing extraneous elements that add extra complexity, where that doesn't seem needed
    * removing extra options (for example, when a <audio> example shows two <audio> elements, recommending we only show 1
    * removing whitespace where that seemed like the only way to get things to fit
* fixing some things that seem like accessibility issues (e.g. missing labels, use of title for explanatory text)
* improving formatting to make examples easier to scan
* using CC0 media so as not to have attributions in the examples
* setting a different height for the editor: either shorter for very short examples, or taller for longer ones that we can't reduce.

The trickiest I think were the table elements: the source there is always too long, but I think it's hard to get a table in the space, so I think we may need to use a taller editor for these.

**Comment by atopal** [comment]
Thanks for doing this, Will!

**Comment by wbamberg** [comment]
FYI - I estimated these updates at 2 days, laughably: it took me 6 days elapsed.
