### ISSUE TITLE
CSS editor should not focus on page load

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1148]
The CSS editor focuses when the page loads. This breaks links to fragments: https://developer.mozilla.org/en-US/docs/Web/CSS/margin#Specifications.

The idea here was to emphasise that the examples were editable, but I'm not sure this is effective, and I don't think it is worth the cost.

I think it's not quite as simple as removing https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/css-editor-utils.js#L40 - doing only that means the user has to click twice in a box before getting the focus.

**Comment by stephaniehobson** [comment]
The first item still inits so it's one click to edit not two. I think this is a good improvement. You could keep an eye on the editor stats for the first couple weeks after this is launched if you're worried.

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/1158 - thanks @stephaniehobson !
