### ISSUE TITLE
Ready and merge WebAPI example into master

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1166]
Except for one potentially tricky issue [https://github.com/mdn/interactive-examples/pull/1142#issuecomment-423178962] the Web API example prototype is ready to be merged to master :tada:

Having talked with @wbamberg at least the first week of the sprint will be needed to sanely and cleanly merge all the work and changes into the master branch. The breakdown, and thus acceptance criteria for this is as follows:

## Acceptance Criteria

* [x] Need to rebase with the latest that is in master [Schalk]
* [x] Do a sanity check [Schalk, Will]
* [x] Merge to webapi-editor feature branch on mdn/interactive-examples [Schalk]

At this point we need to put a halt on new pull request for ~1 week.

* [x] Clean out the PR queue [Schalk, Will]
* [x] Rebase everything from master to webapi-editor [Schalk]
* [x] Sanity check the CSS, JS and HTML examples [Schalk, Will]
* [x] Merge mdn/webapi-editor to mdn/master [Schalk]
* [x] Reopen master for business

~~* [ ] Continue fine tuning the WebAPI example editor [Schalk]~~
~~* [ ] Write additional WebAPI examples [Will, Writing Team]~~
~~* [ ] Ready for user testing~~

**Comment by wbamberg** [comment]
@schalkneethling what do you think about removing the last three points here:

>  Continue fine tuning the WebAPI example editor [Schalk]
>
> Write additional WebAPI examples [Will, Writing Team]
>
> Ready for user testing

Then the goal of this item is to get the new editor (and Bob) merged and in use.

**Comment by schalkneethling** [comment]
Yeah, that makes sense. I was hoping for your feedback as I do not know what your focus for the sprint will be. Let me edit the above.

**Comment by schalkneethling** [comment]
@wbamberg Ok, the PR has now been rebased against master and also includes the latest BoB. We are now on sanity check before merging into `webapi-editor`

**Comment by schalkneethling** [comment]
@wbamberg I have poked around a number of the CSS, HTML and JS examples and all seem good. Let me know if you find any issues, else I reckon we can merge this monster 👹 :)

**Comment by wbamberg** [comment]
It looks good to me, and I've approved the PR. I didn't merge only because that item has your name beside it in in https://github.com/mdn/interactive-examples/issues/1166#issue-364476618 :).

It's still failing tests according to snyk, but I don't know if that's a problem or not.
