### ISSUE TITLE
datalist example doesn't work in Firefox Nightly

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1169]
The interactive example for `<datalist>` doesn't work in Firefox Nightly:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
https://interactive-examples.mdn.mozilla.net/pages/tabbed/datalist.html

It does work in release Firefox (62) and Chrome.

The example lower down the page (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#Examples) does work - but if you copy that code into the editor, it does not work.

This makes me wonder if this is shadow DOM related.

**Comment by wbamberg** [comment]
Possibly related? https://bugzilla.mozilla.org/show_bug.cgi?id=1489440

**Comment by wbamberg** [comment]
If you toggle "dom.webcomponents.shadowdom.enabled" to false, the example works again.

**Comment by jgribonvald** [comment]
I confirm it's related to the shadowdom

**Comment by DavidBruant** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1489440 is now fixed in nightly

**Comment by SphinxKnight** [comment]
@wbamberg just browsing this and can confirm it works fine in Fx Nightly 97.0a1 (2021-12-25) (64 bits)

**Comment by NiedziolkaMichal** [comment]
This example seems to work fine on firefox nightly for some time now, so I will close the issue.
