### ISSUE TITLE
Should we style the iframe differently for no-js

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#117]
As I wrote up the brief for Brigade I noticed that, especially the JavaScript example, look pretty odd when JS is disabled.

<img width="695" alt="screen shot 2017-07-18 at 11 13 45" src="https://user-images.githubusercontent.com/10350960/28311548-4e526892-6bb0-11e7-8957-17719e66f671.png">

Here is an example of the CSS example:

<img width="694" alt="screen shot 2017-07-18 at 11 50 14" src="https://user-images.githubusercontent.com/10350960/28311559-57f50e68-6bb0-11e7-90ee-a6150f50f151.png">

Couple of questions on this then:

1. Will the JS interactive example, and thus the static fallback replace the syntax block? Like for example here?

https://developer.mozilla.org/en-US/docs/User:schalkneethling:push

<img width="698" alt="screen shot 2017-07-18 at 11 59 30" src="https://user-images.githubusercontent.com/10350960/28311649-9d406526-6bb0-11e7-9dfe-d484e2d05025.png">

If that is the case, we should probably:

1. Have the default height of the `iframe` be a lot less tall.
2. Add the blue side border to the output area as it is on the current Syntax example
3. Add a Syntax heading that will be displayed as part of the fallback

The CSS is a bit more tricky perhaps or, maybe we can do the same. Thoughts @stephaniehobson @wbamberg

**Comment by stephaniehobson** [comment]
I believe the long term plan is to remove the syntax boxes, or move them down the page to Specifications section. I don't think we need to worry about replicating their look and heading.

We can definitely update kuma to make the iframes shorter if the user has disabled javascript.

**Comment by schalkneethling** [comment]
Closing this out.
