### ISSUE TITLE
CSS examples iframe is too big

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1175]
The iframe for the CSS examples is too big, so there's some empty gray space underneath it:

<img width="1197" alt="screen shot 2018-10-09 at 1 06 06 pm" src="https://user-images.githubusercontent.com/432915/46695309-1455dc80-cbc4-11e8-9626-862299162b16.png">

**Comment by schalkneethling** [comment]
@wbamberg Are you seeing this on current production? I am not able to reproduce this. Is this using current master or the webapi-editor branch?

**Comment by wbamberg** [comment]
Oh that is weird. Yes, it was in production yesterday, but now it's gone. I'm glad I took a screenshot or noone would have believed me :).
