### ISSUE TITLE
Test perf difference between IE WebAPI editor, Codepen, jsFiddle, and Glitch

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1185]
Now that the WebAPI version of the interactive editor is complete, we need to make a decision in how we move forward. Do we continue to roll our own solution, or would it make more sense to switch to a third party solution such as Codepen, jsFiddle or Glitch

The first step in making this decision is to see what the page load performance impact would be between the four different choices. This will involve creating three demo pages locally, embedding the various editors, then testing the load times using devtools. To get a more real world scenario, we should throttle both the connection as well as the CPU.

Once we have a report on the performance of the different editors, we can make a data driven decision on next steps. The performance is not the only thing that will affect this decision, as the current contribution work flow also needs to be taken into account.

To do the actual testing, either one, or both of the suggestions by @hobinjk and @jwhitlock will need to be used:

## One

For my first round of IE testing I did the equivalent of changing https://github.com/mozilla/kuma/blob/master/kuma/wiki/kumascript.py#L217 to be `return response.text`. You could also build off of https://github.com/mozilla/kuma/pull/5019 which allows you to define @MacrosNotSubjectToSanitization@

## Two 

The iframe sources are limited in the setting ALLOWED_IFRAME_PATTERNS. The environment variable ALLOWED_IFRAME_PATTERNS can be set in the .env file to add a new pattern for local development, or ALLOW_ALL_IFRAMES to turn off checking entirely. James's method will also work to work around the restrictions.

## Acceptance Criteria

* [x] Create local pages for all of the four different editors
* [x] All of the test pages should use the same WebAPI example
* [ ] Report performance figures for each editor

**Comment by schalkneethling** [comment]
Here is my testing feedback with regards to the various editors. All was done with Fast 3G, and 4x CPU throttling.

## jsFiddle

I threw this one out as an option as the embedded examples is not editable.

## HGE (Home Grown Editor)

Here is a video of the page loading:
https://cl.ly/0100ea1c05da

First Contentful Paint: 3.210ms
Speed index: 3.970ms
Time to interactive: 15.170ms
First CPU idle: 11.390ms

### Timing for the iframe

duration: 693.8000000081956
fetchStart: 6625.100000062957
nextHopProtocol: "h2"
responseEnd: 7318.900000071153
startTime: 6625.100000062957

### Summary graph

![Screenshot 2018-10-23 at 14.13.48.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/6a689522-f0e0-4cdf-ba3c-ff3adc1ff76f)

## Codepen click to edit

Here is a video of the page loading:
https://cl.ly/78e3182a69b6

First Contentful Paint: 3.870ms
Speed index: 4.110ms
Time to interactive: 8.270ms
First CPU idle: 8.270ms

### Timing for the iframe

duration: 481.000000028871
entryType: "resource"
fetchStart: 2696.8000000342727
nextHopProtocol: "h2"
responseEnd: 3177.8000000631437
startTime: 2696.8000000342727

### Summary graph

![Screenshot 2018-10-23 at 14.27.27.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/f00cc8dc-64a1-4309-9093-cb32ef90e6ae)

## Glitch

Here is a video of the page loading:
https://cl.ly/c8c8573cf3ce

First Contentful Paint: 3.200ms
Speed index: 3.340ms
Time to interactive: 8.040ms
First CPU idle: 8.040ms

### Timing for the iframe

duration: 589.5000000018626
entryType: "resource"
fetchStart: 2893.199999933131
nextHopProtocol: "http/1.1"
responseEnd: 3482.6999999349937
startTime: 2893.199999933131

### Summary graph

![Screenshot 2018-10-23 at 14.31.18.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/d643db75-8fce-4356-a697-5fb4bf34fffc)

**Comment by schalkneethling** [comment]
@atopal @wbamberg ~ For the above tests I used local overrides in Chrome did overcome the problems I was having with the iframes src being removed by CKEditor or some other backend process. I have no gone ahead and created actual static pages, and here are the revised results.

## Overview

| Measurement              | Codepen | Glitch        | HGE         |
| ----------------------|:---------:|:----------:|:---------:|
| First Contentful Paint | 4.520ms  | 4.490ms   | 4.520ms |
| Speed index                | 4.990ms  | 5.350ms   | 4.780ms |
| Time to interactive     | 8.800ms  | 10.001ms  | 8.670ms |
| First CPU idle              | 8.800ms  | 10.001ms  | 8.670ms |

## Codepen click to edit

First Contentful Paint: 4.520ms
Speed index: 4.990ms
Time to interactive: 8.800ms
First CPU idle: 8.800ms

duration: 500.89999998454005
fetchStart: 693.5000000521541
nextHopProtocol: "h2"
responseEnd: 1194.400000036694
startTime: 693.5000000521541

### Summary graph

![Screenshot 2018-10-23 at 15.27.02.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/bf65e788-53e8-47a9-805a-6679ad14757a)

### Filmstrip

![Screenshot 2018-10-23 at 15.27.50.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/4bf9ff65-c5fe-467b-9815-3ee39ccf8c5b)

## Glitch

First Contentful Paint: 4.490ms
Speed index: 5.350ms
Time to interactive: 10.001ms
First CPU idle: 10.001ms

duration: 327.50000001396984
fetchStart: 594.2000000504777
nextHopProtocol: "http/1.1"
responseEnd: 921.7000000644475
startTime: 594.2000000504777

### Summary graph

![Screenshot 2018-10-23 at 15.34.36.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/10220a51-fd4b-4cfe-86c6-3da77d3f4968)

### Filmstrip

![Screenshot 2018-10-23 at 15.35.05.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/68b7b095-58ae-4b68-bd42-01554111434c)

## Home Grown Editor

First Contentful Paint: 4.520ms
Speed index: 4.780ms
Time to interactive: 8.670ms
First CPU idle: 8.670ms

duration: 89.20000004582107
fetchStart: 585.3999999817461
nextHopProtocol: "h2"
responseEnd: 674.6000000275671
startTime: 585.3999999817461

### Summary graph

![Screenshot 2018-10-23 at 15.39.27.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/087005f9-0caa-44ba-9796-55e72805e5bd)

### Filmstrip

![Screenshot 2018-10-23 at 15.38.37.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/90e70f1a-fc3d-4cd3-8820-0f1dfb877249)

**Comment by atopal** [comment]
Thanks Schalk, looking at this it seems like codepen and our home grown solution are essentially performance neutral, and glitch has a slight performance impact. I'm assuming this was done with the iframed version of the home grown solution?

**Comment by schalkneethling** [comment]
> I'm assuming this was done with the iframed version of the home grown solution?

@atopal Correct.

**Comment by jwhitlock** [comment]
This appears complete to me.
