### ISSUE TITLE
WebAPI examples should not expose shadow DOM machinery

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1186]
Like the HTML editor, the WebAPI editor uses shadow DOM to insulate the example output from the page that the editor is running in.

Currently this internal machinery leaks into the example, because the editor requires the example to explicitly fetch the shadow root before it calls any of the DOM APIs on it:

```
(function() {
    function getHeader() {
        let documentRoot = getShadowRoot();
        return documentRoot.querySelector('header');
    }

    let header = getHeader();
    console.log('header', header.textContent.trim());
    header.style.backgroundColor = '#b2ebf2';
})();
```

This is confusing, and the editor should take care of this internal machinery, so the example can be like:

```
(function() {
    function getHeader() {
        return document.querySelector('header');
    }

    let header = getHeader();
    console.log('header', header.textContent.trim());
    header.style.backgroundColor = '#b2ebf2';
})();
```

I think this is a blocker for running user tests with the editor.

**Comment by stephanmax** [comment]
That totally makes sense, very interesting. Do you mind me taking a look? That would be a PR against the https://github.com/mdn/bob repo, right?

**Comment by wbamberg** [comment]
@stephanmax , unfortunately further testing shows us (just yesterday) that Shadow DOM isn't a suitable implementation for the WebAPI editor at all, so we're going to have to think again about how to provide an editor for WebAPI interactive examples.

But thanks for your interest!
