### ISSUE TITLE
Links to media files are broken

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1192]
See for example:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

This is reproducible in the local environment.

**Comment by stephanmax** [comment]
`mdn-bob` seems to flatten every file in source folder `/media/**/<file>` into dest folder `/media/examples/<file>`, no matter in which subfolder they might be.

If this is intended behavior, then we can simply fix this issue by changing `/media/cc0-images/Grapefruit_Slice--332x332.jpg` to `/media/examples/Grapefruit_Slice--332x332.jpg`, for example.

Let me know if you want that or rather change mdn-bob’s behavior to mirror the folder structure—either way, I’m happy to file a PR, @wbamberg.

**Comment by schalkneethling** [comment]
@stephanmax Thanks for reporting. @wbamberg I reckon let's update the linking to use the flat output folder structure. This will keep things simpler when I also automate  image optimisation via BoB. Thanks!
