### ISSUE TITLE
JS Examples: example for `Object.entries` is confusing

### ISSUE THREAD

**Issue by dovidweisz** [mdn/interactive-examples#1237]
The example for [`Object.entries`][object-entries] is confusing.

The issue is that in line 9 we attempt to subtract one array from another.

instead of : 

    Object.entries(object2).sort((a, b) => a - b);

It should actually match the example code in the page : 

     Object.entries(obj).sort((a, b) => a[0] - b[0]);

[object-entries]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**Comment by kenrick95** [comment]
This should be fixed per #1350

**Comment by wbamberg** [comment]
Yes, thanks @kenrick95 !
