### ISSUE TITLE
Action Required - Malicious dependency requires update to latest master

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1242]
A [security vulnerability has been identified](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream) that affects a large number of projects that depends on the [event-stream npm package](https://www.npmjs.com/packag/event-stream). While interactive-examples does not directly depend on it, the package [npm-run-all](https://www.npmjs.com/package/npm-run-all) that we do depend on, does have it as a dependency.

## Action required

* [ ] Open this issue to track the work required to ensure our contributors are notified
* [ ] Open an issue on forks of the repo and let the users know about the vulnerability and how to resolve the issue
* [ ] Send general notification on social media pointing to this issue

### Community

If you have forked this repo, please update to the latest master branch. This will update the affected dependency to a version that is no longer affected, and remove the security concern.

Please prune all branches that are on your forked version of this repo. The simplest way to accomplish this from your command line is as follows:

```
git push origin :branch-name

# then also delete the branch locally
git branch -D :branch-name
```

We appreciate your assistance in this matter. Should you need any assistance, please feel free to reach out.

**Comment by schalkneethling** [comment]
Pinging users that have known forks:

@2alin
@a2sheppy
@Abhicoding
@aefhm
@aeinbu
@Anemy
@arai-a
@aretecode-forks
@Arkangus
@arnabtarwani
@atopal
@AugustinusVonHippo
@Austinsmom
@belide
@benji1304
@bobtherobot
@brianlmacdonald
@brianmontanaweb
@bromy
@cafeTechne
@chrisdavidmills
@CodeDotJS
@crazyrex
@CShepartd
@d7ark
@dagolinuxoid
@danieldiaz14
@danielhickman
@danielslab
@ddbeck
@diablero13
@direkshan-digital
@dominicduffin1
@dovidweisz
@edtheman74
@eforegist
@Elchi3
@elharony
@elihw
@enterstudio
@ericwbailey
@escattone
@estelle
@eszjay
@euthophis
@ExE-Boss
@fawmi
@FeLUXMAJ
@gabrieleluigi
@galman33
@GAUTAMRAJU15
@gene1wood
@Geolem
@GladiumLab
@jdhakert
@goodwin64
@Granjow
@helmutgranda
@hidde
@hobinjk
@huijing
@iansan5653
@ichthub
@irenesmith
@jacktheclicker
@jimthoburn
@Jonathan-Ironman
@jpamental
@jpmedley
@jrohatiner
@justsml
@jwhitlock
@karlstolley
@kenrick95
@kevinsimper
@Konrud
@Krinkle
@krohne
@kublaj
@laiyongqin
@LLyaudet
@LygutaKsusha
@maboa
@maddhruv
@akshitagoel
@madeinfree
@majidzeno
@marcusgsta
@MarioECU
@martijnthe
@MatsPalmgren
@MaxwellKendall
@meowwwls
@mfluehr
@mlissner
@mobarakali
@navdeepsingh
@neilkakkar
@nikhilganji
@ninjanails
@nnupoor
@npuzyrev
@ogwurujohnson
@ollelauribostrom
@paulirish
@pepkin88
@pl78
@poojasrivastav
@prashantsharma
@qcgm1978
@qwIvan
@rachelandrew
@Regaddi
@revelt
@ro-ka
@Row
@roza
@rozzzly
@rudzboy
@rwaldron
@Satyam-Bhalla
@calmesam01
@schalkneethling
@sdob
@sethips
@ShadowMitia
@sheeeng
@sidvishnoi
@sigoa
@sir-kain
@solayos
@SphinxKnight
@stephanmax
@suknuk
@SWW13
@tatellos
@tbazin
@thomasd801
@tigt
@TremaineNeethling
@vantreeseba
@veekas
@vsemozhetbyt
@wbamberg
@wmsbill
@yisibl
@yukulele
@zkcode
@zofrus

**Comment by schalkneethling** [comment]
@GAUTAMRAJU15
@gene1wood
@Geolem
@GladiumLab
@jdhakert
@goodwin64
@Granjow
@helmutgranda
@hidde
@hobinjk
@huijing
@iansan5653
@ichthub
@irenesmith
@jacktheclicker
@jimthoburn
@Jonathan-Ironman
@jpamental
@jpmedley
@jrohatiner
@justsml
@jwhitlock
@karlstolley
@kenrick95
@kevinsimper
@Konrud
@Krinkle
@krohne
@kublaj
@laiyongqin
@LLyaudet
@LygutaKsusha
@maboa
@maddhruv
@akshitagoel
@madeinfree
@majidzeno
@marcusgsta
@MarioECU
@martijnthe
@MatsPalmgren
@MaxwellKendall
@meowwwls
@mfluehr
@mlissner
@mobarakali
@navdeepsingh
@neilkakkar
@nikhilganji
@ninjanails
@nnupoor
@npuzyrev
@ogwurujohnson
@ollelauribostrom
@paulirish
@pepkin88
@pl78
@poojasrivastav
@prashantsharma
@qcgm1978
@qwIvan
@rachelandrew
@Regaddi
@revelt
@ro-ka
@Row
@roza
@rozzzly
@rudzboy
@rwaldron
@Satyam-Bhalla
@calmesam01
@schalkneethling
@sdob
@sethips
@ShadowMitia
@sheeeng
@sidvishnoi
@sigoa
@sir-kain
@solayos
@SphinxKnight
@stephanmax
@suknuk
@SWW13
@tatellos
@tbazin
@thomasd801
@tigt
@TremaineNeethling
@vantreeseba
@veekas
@vsemozhetbyt
@wbamberg
@wmsbill
@yisibl
@yukulele
@zkcode
@zofrus

**Comment by schalkneethling** [comment]
@nnupoor
@npuzyrev
@ogwurujohnson
@ollelauribostrom
@paulirish
@pepkin88
@pl78
@poojasrivastav
@prashantsharma
@qcgm1978
@qwIvan
@rachelandrew
@Regaddi
@revelt
@ro-ka
@Row
@roza
@rozzzly
@rudzboy
@rwaldron
@Satyam-Bhalla
@calmesam01
@schalkneethling
@sdob
@sethips
@ShadowMitia
@sheeeng
@sidvishnoi
@sigoa
@sir-kain
@solayos
@SphinxKnight
@stephanmax
@suknuk
@SWW13
@tatellos
@tbazin
@thomasd801
@tigt
@TremaineNeethling
@vantreeseba
@veekas
@vsemozhetbyt
@wbamberg
@wmsbill
@yisibl
@yukulele
@zkcode
@zofrus

**Comment by hobinjk** [comment]
@schalkneethling The version of `event-stream` in `package-lock.json` is 3.3.4 so I don't think we're directly effected, just at risk?

**Comment by jwhitlock** [comment]
@hobinjk ``event-stream 3.3.6`` was the affected version, which started requiring ``flatmap-stream 0.1.0``. ``flatmap-stream 0.1.1`` is the version with the vulnerability, and npm update rules would have started including the minor version update. The master branch was updated with PR #1239 on November 26, 2018. This [Ars Technica article](https://arstechnica.com/information-technology/2018/11/hacker-backdoors-widely-used-open-source-software-to-steal-bitcoin/) has more information.

If your fork is using ``event-stream 3.3.4``, it is 1) very out of date, and 2) not affected.  You still may want to update your fork, or delete your fork if you have no open PRs and don't intend to contribute in the near future.

**Comment by 2alin** [comment]
Thank you for the call out. Updating my fork, now.

**Comment by ExE-Boss** [comment]
Done on my end.

**Comment by ollelauribostrom** [comment]
Thanks for the heads up 👍 Updated my fork.

**Comment by GAUTAMRAJU15** [comment]
just updated . Thanks 💯
