### ISSUE TITLE
Make an npm package export of Web API examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1244]
Rather than a homegrown editor, we're intending to use [embedded CodePens](https://blog.codepen.io/documentation/features/embedded-pens/) for Web API interactive examples.

This will work a little differently to the existing CSS/JS/HTML examples. Those examples are currently built into standalone web pages (e.g. https://interactive-examples.mdn.mozilla.net/pages/css/background-color.html) that are then embedded in MDN inside an iframe.

For embedded CodePens, we'll more likely have a situation where the MDN wiki page contains the source for the example, and then some code running in the wiki page creates a pen from the code and embeds it in an iframe (the exact details of this are unclear at the moment - but the way the existing Live Sample system implements "Open in CodePen" is not all that different: https://github.com/mozilla/kuma/blob/master/kuma/static/js/wiki-samples.js).

But we don't want to maintain the example sources themselves in the wiki. We want to maintain them in interactive-examples, so we can keep them all in one place, under source control, with the possibility of linting and testing, etc etc.

So we need a way to make them available to Wiki pages. The proposal for doing that is:

1. we build an npm package out of interactive examples, that contains the source for the Web API examples
2. KumaScript gets a dependency on this package
3. a macro in the page fetches the example source from this package and adds it to the page with the appropriate markup for CodePen to do its thing.

This is the same system as that used for browser-compat-data.

This issue covers the first of these items "build an npm package".

## Acceptance criteria
- [ ] An npm package can be built, containing the source for Web API interactive examples.

**Comment by wbamberg** [comment]
One thing to decide here is the structure of the package. We can experiment here, but as a first suggestion: follow the hierarchical "BCD structure" for this, where a user of the package can get access to a portion of it using a query like 

    api.document.querySelector.__interactive_example

...and get back an object with up to three properties, all strings: `html_source`, `js_source`, `css-source`.

**Comment by NiedziolkaMichal** [comment]
I believe this is no longer relevant, as it was chosen to use BOB for interactive examples, instead of embedded codePens.
