### ISSUE TITLE
CSS examples: "Reset" does not persist

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#127]
With the CSS examples, if I change the initial contents of row A, the Reset button appears. If I switch to a different row, the button disappears - this is as expected. But if I then switch back to row A, the Reset button does not reappear - it's now impossible to get back to the original without reloading the page.

**Comment by schalkneethling** [comment]
> But if I then switch back to row A, the Reset button does not reappear - it's now impossible to get back to the original without reloading the page.

Yeah. So, I did make it so the Reset button shows by default if the field was in an invalid state. Making this change means that, we will also show the reset button by default unless, the current state matches the original state. Correct?

**Comment by wbamberg** [comment]
Yes, I think Reset should be displayed if both the following are true:
* the row is selected
* the contents of the row is different from its original contents

To me, the point is that there's "invalid" meaning "invalid CSS", and "invalid" meaning "not the CSS I meant to write". Say I start with the CSS in an example and want to tweak it. I change it, and don't get the effect I want, but still get something technically valid. I now can't go back to the original without reloading the page.

**Comment by schalkneethling** [comment]
Ok so, the flow is as follows:

-> Select row
-> If row was in an invalid state => show reset
-> If the current CSS is not equal to the original CSS => Show reset
-> If current CSS and original CSS match => No reset
