### ISSUE TITLE
Editor for full environments

### ISSUE THREAD

**Issue by kevinsimper** [mdn/interactive-examples#1270]
Talking with @wbamberg about #1266 there is a need for an editor that can handle HTML/CSS/JS.

So I guess it is something like JSBin/Codepen that has 3 boxes, that gets combines into one document into a iframe?

**Comment by wbamberg** [comment]
We're hoping to use embedded CodePens for this: https://blog.codepen.io/documentation/features/embedded-pens/ - but we still want to use interactive-examples as the contribution path, so there's going to be some glue work needed, which I started outlining here https://github.com/mdn/interactive-examples/issues/1244.

**Comment by NiedziolkaMichal** [comment]
This is now possible. Tabbed examples like [this](https://github.com/mdn/interactive-examples/pull/2224), can now display HTML, CSS, and JS tabs.
Thanks a lot for suggesting it.

**Comment by kevinsimper** [comment]
@NiedziolkaMichal Nice, awesome 🎉

**Comment by wbamberg** [comment]
Amazing work @NiedziolkaMichal !
