### ISSUE TITLE
In MDN Web docs, CodeMirror-code section taking console logs executed in the browsers developer console

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1290]
Originally reported in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1512793

Description of issue from Bugzilla:

What did you do?
================
1. Executed JavaScript Demo: Statement - Label using run button
2. On developers console executed console log statements 
3. the console log result is appended to the JavaScript Demo: Statement - Label results i.e. output-container

What happened?
==============
1. Executed JavaScript Demo: Statement - Label using run button
2. On developers console executed console log statements 
3. the console log result is appended to the JavaScript Demo: Statement - Label results i.e. output-container

<img width="1670" alt="screen shot 2018-12-08 at 3 18 21 pm" src="https://user-images.githubusercontent.com/10350960/51237257-c13ab500-197c-11e9-91d4-d9b73e7141f0.png">

What should have happened?
==========================
it should the modify the docs demo code result.

Is there anything else we should know?
======================================

**Comment by schalkneethling** [comment]
I am unable to reproduce this using both Chrome and Firefox. @wbamberg Thoughts?

**Comment by wbamberg** [comment]
I can't reproduce this either.

**Comment by schalkneethling** [comment]
Thanks @wbamberg - closing
