### ISSUE TITLE
running locally, offline?

### ISSUE THREAD

**Issue by titaniumbones** [mdn/interactive-examples#1310]
Hi @wbamberg ,  @schalkneethling, et al

I'm on my way to the Indian Himalaya to do a very brief trial run teaching HTML & CSS in a girls school in a very low-bandwidth region. We are running a local copy of JSBin & a couple of static sites off of a raspberry pi & gathering necessary libraries (jQuery, etc) as we need them. For some time I've been thinking about trying to get some fraction of MDN running locally as well, but when I looked at the repo structure some months ago I was overwhelmed, and haven't had the bandwidth to think about it again until now.  

If you were going to self-host part of the MDN framework, what would you start with? And how hard would it be?  It looks like there are many interdependencies. If you possibly have a second to help is figure it out, I would be super-grateful.

Tagging my collaborator @dcwalk as well.  Thank you!

**Comment by wbamberg** [comment]
You can set up the interactive examples to run locally by cloning this repo and running "npm install". After that you can run a local server with "npm run start", and this will serve running copies of all the interactive examples.

For bigger pieces of MDN, including the prose content, it's more problematic. MDN doesn't support an offline mode. Some people offer an offline version by scraping the site (e.g. https://kapeli.com/dash) but I don't know how well that works. I would love for this to be a properly supported MDN feature at some point in the future but it looks a long way off at the moment.

**Comment by schalkneethling** [comment]
@titaniumbones Wow, that is an awesome project. I wish you all of the best with it. As @wbamberg said, running specifically the interactive-examples locally should be as easy as forking, `npm i`, and then `npm start` and you're up an running.

For the https://developer.mozilla.org site, it is a whole other kettle of fish ;p The resource Will pointed you to is definitely a good first step, which I have personally used in the past.

Just as an FYI, and you might know about this already, but internet-in-a-box is also something well worth looking into. http://internet-in-a-box.org/
