### ISSUE TITLE
Why is there synchronous code logging "Async code started"

### ISSUE THREAD

**Issue by arye-dov-eidelman** [mdn/interactive-examples#1330]
I would like to make two corrections in the [Promise Object Advanced Example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Advanced_Example). I couldn't find the interactive demo for this here so I'm not sure where the correct place to make this change would be.

### Sync code is logging "Async code started" it should be wrapped in a setTimeout 0 or removed

Excerpt starting at line 12:

```javascript
    let p1 = new Promise(
        // The executor function is called with the ability to resolve or
        // reject the promise
       (resolve, reject) => {
            log.insertAdjacentHTML('beforeend', thisPromiseCount +
                ') Promise started (<small>Async code started</small>)<br/>');
            // This is only an example to create asynchronism
            window.setTimeout(
                function() {
                    // We fulfill the promise !
                    resolve(thisPromiseCount);
                }, Math.random() * 2000 + 1000);
        }
    );
```

lines 16 - 17 logs "...(Async code started)", while in fact, it is running synchronously.

```
1) Started (Sync code started)
1) Promise started (Async code started)
1) Promise made (Sync code terminated)
1) Promise fulfilled (Async code terminated)
```

If it were running asynchronously it would output:

```
1) Started (Sync code started)
1) Promise made (Sync code terminated)
1) Promise started (Async code started)
1) Promise fulfilled (Async code terminated)
```

While this may not be perfect it would be more correct if it were wrapped in a setTimeout 0, changed to "promise started (still running synchronously)" or removed altogether.

```javascript
    let p1 = new Promise(
        // The executor function is called with the ability to resolve or
        // reject the promise
       (resolve, reject) => {
            window.setTimeout(
                function() {
                    log.insertAdjacentHTML('beforeend', thisPromiseCount +
                        ') Promise started (<small>Async code started</small>)<br/>');
                }, 0);
            // This is only an example to create asynchronism
            window.setTimeout(
                function() {
                    // We fulfill the promise !
                    resolve(thisPromiseCount);
                }, Math.random() * 2000 + 1000);
        }
    );
```

### then defines the actions for a settled promise (fulfilled/rejected), not a resolved one 

At line 27

```
// We define what to do when the promise is resolved with the then() call,
```

then defines what to do when the promise is **fulfilled** and optionally also when it's rejected ie when it's **settled**. It doesn't define what to do while the promise's state is "'locked in' to match the state of another promise".
This goes back to [this revision](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise$compare?locale=en-US&to=1356659&from=1349245).

**Comment by wbamberg** [comment]
Thanks for filing. Yes, we don't use the interactive examples framework for these examples so issues should just be filed as MDN content bugs, which I've done here: https://github.com/mdn/sprints/issues/1251.

I'm closing this as we will track it over there.
