### ISSUE TITLE
EmbedLiveSamples (where to find and how to fix them)?

### ISSUE THREAD

**Issue by Konrud** [mdn/interactive-examples#1343]
I don't seem to find where example that is embedded like this `{{ EmbedLiveSample('Live_Examples', '100%', '150px') }}` can be easily found in order to fix it?
 I think it's a bit an issue here because a lot of these examples are poorly defined and don't work.

**Comment by wbamberg** [comment]
Hi @Konrud 

As usual with MDN there are several different systems each with their own quirks. With `EmbedLiveSample` the code is in the Wiki page itself (or sometimes a different Wiki page).

There's an overview of all our example systems here: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Code_examples.

There are detailed docs on `EmbedLiveSample` here: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Live_samples.

Thanks for offering to help improve them! Please do ask if you have any specific questions, although asking in our forum: https://discourse.mozilla.org/c/mdn is better than a GitHub issue. And I think it's a good idea to talk in there about which examples you're intending to fix, so people can help review them &c.
