### ISSUE TITLE
Make it easier to change live-examples

### ISSUE THREAD

**Issue by ackvf** [mdn/interactive-examples#1347]
It is no longer necessary to suggest cloning&PR, since github does that automatically when live-editing a file, right from github web interface.

![image](https://user-images.githubusercontent.com/2313018/57762405-be1fbd80-76ff-11e9-8ab6-e9fc9d564f3d.png)

Before:
><p class="hidden">The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> and send us a pull request.</p>

After:
><p class="hidden">The source for this interactive example is stored in a GitHub repository. Use the github web interface to change this example <a href="https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/regexp/regexp-prototype-test.html">here</a> or clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> and send us a pull request.</p>

Where `here` is a direct link to the example in question if possible, or link to /master/live-examples.

```
<p class="hidden">The source for this interactive example is stored in a GitHub repository. Use the github web interface to change this example <a href="https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/regexp/regexp-prototype-test.html">here</a> or clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> and send us a pull request.</p>
```

**Comment by zlatnaspirala** [comment]
I don't know where to ask, this page looks like nice topic for my Q.

  I have article with my small game engine and i wanna make pull request with basic examples but there is no proper folder to do it.  Is it possible to create new folder like "frameworks" or any other alias . Then
 from that folder create : 
   (Just for example)

 /frameworks/ or /game-engines/
   - pixi.js/  all pixi examples 
   - phaser/ all phaser ...
    ...

   Please give me any suggestion to make this possible.

**Comment by ackvf** [comment]
@zlatnaspirala You better ask at https://stackoverflow.com/ so that somebody notices your question.

**Comment by wbamberg** [comment]
@ackvf , sorry to be slow responding to your suggestion. I did read about it and thought about it, but I'm not 100% sure I like the idea.

As a rule I would like contributors to test out the example before making a PR for it, and I think this is more likely to happen if they have taken the step of cloning the repo (because they can run `npm run start` to see it locally).

On the other hand of course your suggestion does lower the bar to contributions, and maybe that's worth getting more PRs that don't work properly because they weren't tested.

Either way, there's no easy way to make this change: you would have to go and manually edit all [909 en-US pages](https://developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=EmbedInteractiveExample&topic=none), or all [4321 pages in all locales](https://developer.mozilla.org/en-US/search?locale=*&kumascript_macros=EmbedInteractiveExample&topic=none), and I'm not personally going to have the time to do this for the forseeable future.

**Comment by wbamberg** [comment]
@zlatnaspirala , I'm not sure what you are suggesting. Is the article on MDN? If so can you point to it?

**Comment by ackvf** [comment]
@wbamberg I see, that's quite a lot :) I thought that was just an included template. What a shame though, it would be more friendly and not discouraging as it sounds now. (The clone&PR is little frightening, tbh.)

You mentioned running `npm start`, but I always copy/paste the examples into a console to fiddle with them, that should suffice to test them, no?

**Comment by wbamberg** [comment]
>  I always copy/paste the examples into a console to fiddle with them, that should suffice to test them, no?

Yes, I often do that too, and of course having to clone isn't itself a guarantee anyone will test it either. So I do think your suggestion is a good one and if I could wave a wand and have it done I probably would, at least as an experiment.

Background:

1) The interactive examples have their own build system, which builds examples into separate standalone web pages (e.g. https://interactive-examples.mdn.mozilla.net/pages/js/array-slice.html). The build system is actually implemented by a different repo: https://github.com/mdn/bob.

2) To include them in MDN pages we have a [macro](https://github.com/mdn/kumascript/blob/master/macros/EmbedInteractiveExample.ejs) that basically just adds an iframe containing that URL. You add this macro to the page and give it the path to the example page (e.g. `{{EmbedInteractiveExample("pages/js/array-slice.html")}}`).

3) We also have a bit of hidden text, that only shows up in edit mode, that tells you that the example isn't part of the Wiki, and that contains the link to the GitHub repo, and that's the bit you were quoting originally. This text is manually added for each page.

As you say it would be much better to link to the particular file (e.g. https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/array/array-slice.html) than just to https://github.com/mdn/interactive-examples/tree/master/live-examples. This would be relatively easy to do inside the build process at (1) above. So we could amend that build process to add a little link in the built page (a bit like the "Fork me on GitHub" banners that you see on built docs pages).

One reservation about this is: I like the fact that the text in (3) is only visible to people who are already editing, but there's AFAIK no easy way to automate that text. By adding the link directly into the built page, the link is now visible to everyone, even people who have no intention or desire to contribute.So this is (a) extra visual noise for some people and (b) might increase the amount of "noise PRs" that we get in the repo.

I'm not sure how to balance that against making it easier for people to contribute. I appreciate that it's not that easy at the moment, but we do still get a fair trickle of good contributions here even so.

**Comment by zlatnaspirala** [comment]
> @zlatnaspirala , I'm not sure what you are suggesting. Is the article on MDN? If so can you point to it?

Yes here is the link [ /docs/Games ](https://developer.mozilla.org/en-US/docs/Games/visual_typescript_game_engine) .

 I will forget this idea (for this project). I have webpack, typescript also my build system create one package (>400kb js).  Only way is to make custom chucks files (separate libs / example) and still example code will be javascript ecma5 not typescript - no sense at all.

 -The perfect situation would be to import the project through a package.json file with all its dependency etc...  

 In that case, you can quickly verify PR source code because most of apps usually already use validated node modules.

**Comment by ackvf** [comment]
@wbamberg Thank you for the exhaustive explanation!

I totally agree that the "Fork on github" should be hidden when viewing and only visible when user is already editing a page.

---

So basically, what you are saying is that when somebody writes a new  MDN page (by hand), they have to type (possibly copy/paste) this maually as well, when an already existing standalone interactive example is being used.

```
<div>{{EmbedInteractiveExample("pages/js/regexp-prototype-test.html", "taller")}}</div>

<p class="hidden">The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> and send us a pull request.</p>
```

---

I now see very clearly why it can't be automated or changed on every page at the same time. It's just plain text! I am so sad.

So I guess, close this issue as way too complicated for little value?

**Comment by wbamberg** [comment]
> So I guess, close now this issue as way too complicated for little value?

I guess so, yes. I'm sad too but I don't realistically think this is going to get done.
