### ISSUE TITLE
array filter example is not inline with the browser compatibility table

### ISSUE THREAD

**Issue by valerian-precop** [mdn/interactive-examples#1404]
Array filter example is not inline with the browser compatibility table.
Using the arrow function is not compatible with IE11 and bellow.

Suggested fix:
``
words.filter(function(word) { return word.length > 6; });
``

**Comment by wbamberg** [comment]
Thanks for filing!

You are right according to the guideline: https://github.com/mdn/interactive-examples/blob/master/JS-Example-Style-Guide.md#language-choice-es5es6. I think it would be better to use multiple lines, like:

```js
const result = words.filter(function(word) {
  return word.length > 6;
});
```

Still it does feel weird to be using this syntax here, and [the general MDN guideline is now to use ES6 features in examples](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Use_ES6_features). The general MDN guidelines were written later than the interactive-examples guidelines which helps explain the discrepancy.

So it would probably be better to update the guidelines for interactive examples to align (or simply point to) with the general MDN ones!

**Comment by wbamberg** [comment]
Fixed by updating the guidelines -> https://github.com/mdn/interactive-examples/pull/1410.
