### ISSUE TITLE
Idea: draw an arrow from the current example to the output box

### ISSUE THREAD

**Issue by a2sheppy** [mdn/interactive-examples#145]
How about actually drawing an arrow that runs from the current example's code box and points at the output of the example? Something like the attached.

![interactive-transform-example-arrow](https://user-images.githubusercontent.com/1641439/28687280-fb53dc42-72db-11e7-9fae-1eb5b98ac079.png)

**Comment by schalkneethling** [comment]
I feel like with the recent changes made to the editors, this has been resolved for the most part. There is some feedback forthcoming from The Brigade with regards to UX so, I reckon we can close this one? @stephaniehobson @wbamberg Thoughts?

**Comment by stephaniehobson** [comment]
Yes, we can close this. The connection between the two will be addressed by The Brigade.
