### ISSUE TITLE
The image in css style guide is invalid

### ISSUE THREAD

**Issue by Ende93** [mdn/interactive-examples#1471]
## Steps
Follow [CSS-Example-Style-Guide.md](https://github.com/mdn/interactive-examples/blob/master/CSS-Example-Style-Guide.md) > Output width considerations > https://screenshots.firefox.com/YYrEvqLEmLjJCddS/developer.mozilla.org

## Result
Only see that error page.

## Expect
Please update the image.

**Comment by velusgautam** [comment]
The issue with link is there. Also the screenshots.firefox.com is going to be deprecated. So need to put that image in repo and refer or some other reliable links. @wbamberg  Do you have any pointers how to fix this?
https://screenshots.firefox.com/YYrEvqLEmLjJCddS/developer.mozilla.org

I will try to fix it. Thanks @Ende93 .

**Comment by wbamberg** [comment]
> I will try to fix it.

Sorry @velusgautam , I didn't see this part of your comment, and just filed a fix already. Thanks for the information about it though, and thanks @Ende93 for filing.
