### ISSUE TITLE
Color Adjust not working in chrome. 

### ISSUE THREAD

**Issue by velusgautam** [mdn/interactive-examples#1473]
![Screenshot 2019-11-06 at 12 04 20](https://user-images.githubusercontent.com/8556085/68293613-99911680-008e-11ea-89dd-d5666b6b7795.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust

**Comment by wbamberg** [comment]
According to our docs, this property is only supported in Chrome behind the `-webkit-` prefix. Actually this doesn't seem quite right - according to https://css-tricks.com/almanac/properties/c/color-adjust/, the Chrome version is called `webkit-print-color-adjust`. Still, it is possible to support multiple different names for properties (see https://github.com/mdn/interactive-examples/pull/1120 for how).

But, this property has no visual effect even in Firefox, so I don't think it's a useful thing to have an example of. So I've just removed the example from the page.
