### ISSUE TITLE
Add docs on using allcontributors

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1487]
I used to always keep the contributors list up to date via `allcontributors`. I have not done this in some time and that is unfortunate. Also, because I always just did this, I never documented what I actually do. #sad

This issue is to document this and/or have a look at the evolution of `allcontributors` and see whether this cannot be automated entirely.

**Comment by wbamberg** [comment]
What do you think about removing allcontributors from this repo? I understand that it's a nice thing to have, but it is an extra thing to maintain by people who barely have time to maintain the other things. And we don't use it for other MDN repos, and it's always possible to get the list of contributors from https://github.com/mdn/interactive-examples/graphs/contributors.

**Comment by schalkneethling** [comment]
> What do you think about removing allcontributors from this repo? I understand that it's a nice thing to have, but it is an extra thing to maintain by people who barely have time to maintain the other things. And we don't use it for other MDN repos, and it's always possible to get the list of contributors from https://github.com/mdn/interactive-examples/graphs/contributors.

Let me have a quick look and see whether the new version is indeed automated. If it still requires manual hand-holding, then I reckon it makes sense to remove it.

**Comment by velusgautam** [comment]
@all-contributors please add @velusgautam  for  code, doc and bug

**Comment by velusgautam** [comment]
I have earlier added manually and it was a mistake.

**Comment by velusgautam** [comment]
@schalkneethling I have added my details manually to the Readme.md and it was a mistake. Can you please correct it.

**Comment by schalkneethling** [comment]
> @schalkneethling I have added my details manually to the Readme.md and it was a mistake. Can you please correct it.

Any specific reason you feel it was a mistake? If you have contributed(which it definitely looks like you have, then having you on the list is perfect. Let me know if I am missing something. Thanks!

**Comment by schalkneethling** [comment]
I am in the process of adding the AllContributors Bot to the repo https://allcontributors.org/en

Once that is all good and ready, the process will be largely automated. See:
https://allcontributors.org/docs/en/bot/usage

**Comment by velusgautam** [comment]
@schalkneethling I was also mentioning that, the bot was supposed to add me. I didn’t notice that and added it manually. 
No worries, when process is complete I hope things will be in order :)

**Comment by tannerdolby** [comment]
I kinda wanted to append myself to the list. Is this still an issue/feature that needs completing? Let me know @schalkneethling !

**Comment by schalkneethling** [comment]
@tannerdolby Thank you for bringing this up again. I kinda left this to "rot" 😸  mainly because I think Github does a good job of this now natively?

![Screenshot 2021-06-01 at 10 54 16](https://user-images.githubusercontent.com/10350960/120295738-b96ad980-c2c7-11eb-95e1-d2898a9542ee.png)

https://github.com/mdn/interactive-examples/graphs/contributors

What do you reckon, shall we close this one?

**Comment by tannerdolby** [comment]
@schalkneethling Your welcome! I completely understand 😸  Yeah I think you are right, GitHub does a fine job of handling the contributor list in https://github.com/mdn/interactive-examples/graphs/contributors

I reckon we close this one!

**Comment by wbamberg** [comment]
If we are not going to keep this up to date, shouldn't we remove it?

**Comment by schalkneethling** [comment]
> If we are not going to keep this up to date, shouldn't we remove it?

Indeed, I shall remove it.
