### ISSUE TITLE
Keep example's javascript consistent with that feature's EMCA release

### ISSUE THREAD

**Issue by Paul-Browne** [mdn/interactive-examples#1498]
For example the `array.reduce` interactive example uses `const` and an arrow function `=>` which were not part of the EMCAScript 5 release (when reduce was introduced).

Obviously this reduce example will still work, but not in IE9, which is listed in the browser compatibility section. 
Rather use javascript in the interactive example that was around when the feature was released. In this case `var` and regular good old functions.

I'm just bringing this up as a teacher who has had some confused students.

**Comment by wbamberg** [comment]
Thanks for filing! We've fairly recently changed our policy on this, and now recommend using "modern JS" features (like `const` and `let` and arrow functions) for all our example code.

Please see https://discourse.mozilla.org/t/proposal-for-policy-change-regarding-use-of-es6-features-in-code-examples/32686 and https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript.

I appreciate that this might confuse people targeting older browsers (who aren't using a transpiler to support modern features), but on the other side:

* Features like `let` and `const` are pretty widely used now, and many developers expect to see them. By not using them, we would confuse these developers.
* There are major benefits to using these features, and we should be encouraging their use.
* At this point, it's probably better for people who need to support obsolete browsers to use a transpiler, so they can use these language features.

So I think the upside of using these features in our examples outweighs the downside.
