### ISSUE TITLE
Decrease the height of short examples

### ISSUE THREAD

**Issue by ikarasz** [mdn/interactive-examples#1530]
Since the short example's line limit has been reduced, there is a bigger white gap at the bottom of short examples:
![short-interactive-example-gap](https://user-images.githubusercontent.com/5849426/72507050-1b1ad700-387e-11ea-9cca-1dd146660632.png)
So I am wondering whether we should reduce the height of the editor and iframe as well. It would look like this with a smaller editor:
![short-interactive-example](https://user-images.githubusercontent.com/5849426/72507223-7351d900-387e-11ea-9ff2-c7892358b153.png)

However, it might be good if we leave some space to play around with the code.
What do you think?

**Comment by wbamberg** [comment]
A bit of data/analysis on this.

We have 3 editor heights, "short", "standard", "tall".

**"short"**
* can show 9 lines
* examples < 7 lines get the short editor
* example of the tallest "short" example: [`String.lastIndexOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf)

**"standard"**
* can show 13 lines
* examples 7-12 lines inclusive get the standard editor
* example of the shortest "standard" example: [`String.substring()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring)
* example of the tallest "standard" example: [`Array.includes()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

**"tall"**
* can show 23 lines
* examples > 12 lines get the taller editor
* example of the shortest "tall" example: [`String.slice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)

**Distribution**, given as:
`example size: number of examples of that size`

short:

    2: 2
    4: 17
    5: 21
    6: 33

standard:
    
    7: 28
    8: 58
    9: 38
    10: 47
    11: 100
    12: 95

tall:

    13: 25
    14: 12
    15: 1
    16: 1
    17: 3
    18: 1
    19: 4
    20: 1
    21: 3
    22: 4
    23: 1
    27: 1
    29: 1

**Comment by wbamberg** [comment]
So having written all that out :) then if we are happy with these boundaries, then I agree, we could trim the short editor by a couple of lines, and still have an empty line at the end.

Alternatively we could move the boundary for "short" so that examples with 7 get the short editor. As you say though it's a balance between giving space back to the page, and having a bit of space under the example for people to experiment.

I don't know who else would have a view on this. @Elchi3 , @chrisdavidmills ?

**Comment by chrisdavidmills** [comment]
I don't think anything needs to be done here. Having a bit of whitespace at the bottom of the short examples doesn't look wrong, imo, it makes the example window look nicely balanced. If you make it shorter still, it looks a bit squashed.

And it is nice to have a bit of visible space available in which to experiment.

**Comment by Elchi3** [comment]
From looking at some of these, I also don't feel strongly about changing anything here. It is just a feeling, however. I haven't done any analysis. Changing the boundaries, like Will says, might be an idea to experiment with, if we feel the need to optimize this.

**Comment by wbamberg** [comment]
OK, thanks for your feedback, people! And thanks for raising this @ikarasz . I'm glad to have done this analysis - it's worth checking these assumptions from time to time. But I think we may as well close this, since there doesn't seem to be a strong desire to change things.
