### ISSUE TITLE
JS examples: need example for Array.flatMap()

### ISSUE THREAD

**Issue by Elchi3** [mdn/interactive-examples#1587]
-> https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

How to do this work: https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-JavaScript.md

**Comment by CreaTorAleXander** [comment]
Why is it a bug?

**Comment by tannerdolby** [comment]
@wbamberg If this is still available I can submit a PR!
