### ISSUE TITLE
Embed JS editor

### ISSUE THREAD

**Issue by johnaweiss** [mdn/interactive-examples#1591]
Hi, simple question, what's the minimal code to embed a JS code editor in an HTML webpage?

thx!

**Comment by wbamberg** [comment]
These examples get built into standalone web pages under https://interactive-examples.mdn.mozilla.net/ : for example https://interactive-examples.mdn.mozilla.net/pages/js/array-slice.html. So you could just embed that page in an iframe, and that's what the MDN pages themselves do.

However, this is considered an internal implementation detail of the interactive examples system, so while I can't see any problem with you doing this, it's not explicitly supported either, so we can't guarantee that it will continue to work forever.
