### ISSUE TITLE
Example displayed differently depending what example was displayed before

### ISSUE THREAD

**Issue by avivmu** [mdn/interactive-examples#1614]
In https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size
There is a problem with the second example `inline-size: 150px;
writing-mode: vertical-rl;`.
If you click on it when the _first_ example is displayed then it is shown OK:
![image](https://user-images.githubusercontent.com/19804341/86107268-490d7400-baca-11ea-8331-150ded621276.png)

However if you click on it when the _third_ example is displayed then it is cropped and not all the content is displayed.
![image](https://user-images.githubusercontent.com/19804341/86107193-32671d00-baca-11ea-9071-d70f2a09f077.png)
My browser is Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by wbamberg** [comment]
I can't reproduce this in Chrome (85) or Firefox. @schalkneethling , can you?

**Comment by avivmu** [comment]
I noticed it also happens the first time coming from the first example as well, but after that only the third example is causing it
Also I managed to get the fourth example not span all the available height (Not connected to the error shown in the log):
![image](https://user-images.githubusercontent.com/19804341/88889359-a66f1f00-d248-11ea-82b4-854d6e1662ef.png)

**Comment by schalkneethling** [comment]
I can reproduce this on Chrome 83 and 84 as well as Edge 84 and 85(dev). This seems to be a Blink bug that is fixed in Chrome 85. I say Blink because Safari does not exhibit the same problem.

**Comment by avivmu** [comment]
Doesn't reproduce anymore
