### ISSUE TITLE
JS examples: copy/paste is weird

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#162]
In the JS editor, if you copy some text from the window and paste it somewhere else, the pasted test gets this weird border: http://imgur.com/a/v05ZP.

**Comment by schalkneethling** [comment]
Hmmm, this seems to be a bug in Firefox. It copies the parent `<code class="  language-js">` as well. I tested it in Chrome, Safari and Opera and none of them exhibit the behaviour.

I mean, there is a way we can fix it in Firefox. One would need to dig into the ClipboardEvent[1] most likely and do some RegEx matching on the contents to strip of the `<code>` tags before a user pastes. Thoughts @wbamberg ?

[1] https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/ClipboardEvent

**Comment by schalkneethling** [comment]
@stephaniehobson Any suggestions on how to handle this? I guess it is kinda obvious that we need to "fix" it by using `ClipboardEvent` but, thought I would ask in case you have another suggestion. Thx

**Comment by stephaniehobson** [comment]
I agree the correct way to do it would be to strip the extra `code` tags.

The fast way might be to remove the border using CSS. Provided having the extra `code` element doesn't interfere with actually running the example.

**Comment by schalkneethling** [comment]
> The fast way might be to remove the border using CSS. Provided having the extra code element doesn't interfere with actually running the example.

It does effect running the examples. Whatever is pasted is ignored so, it is not just the border that is the problem. Basically it seems to copy the HTML including the parent element as apposed to just the selected text.
