### ISSUE TITLE
Object.prototype.isPrototypeOf

### ISSUE THREAD

**Issue by hinell** [mdn/interactive-examples#1622]
Replace existing example of the [isPrototypeOf] ([MDN]) by the following:

```js
function Foo() {}
function Bar() {}

Bar.prototype = Object.create(Foo.prototype);

const bar = new Bar();

console.log(Foo.prototype.isPrototypeOf(bar));
// expected output: true

console.log(Bar.prototype.isPrototypeOf(bar));
// expected output: true
```
Current example is vague.

[isPrototypeOf]: https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/object/object-prototype-isprototypeof.js
[MDN]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf

**Comment by wbamberg** [comment]
> Current example is vague.

Can you explain what you mean by vague? What's vague about it, specifically, and how does the proposed change fix that?

**Comment by hinell** [comment]
@wbamberg It's hard to catch what's going on due to bad namings. Instance names are mixed with constructors's ones:
```js
...
object1 ...
object2 ...
object3 ...
...
```
