### ISSUE TITLE
update gap example

### ISSUE THREAD

**Issue by SimonSiefke** [mdn/interactive-examples#1629]
Currently there is [one example](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) that shows the use of `grid-gap`. 
Since `gap` is now [widely supported](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) I think it would make sense to update the example to show the use of `gap` instead of `grid-gap`. If wanted, I can make a PR. 🙂

**Comment by wbamberg** [comment]
Yes, I agree, we should update this. And yes, I'd be very happy to see a PR for it :).
