### ISSUE TITLE
JS examples: adding new lines to the editor overflows the iframe

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#163]
I think that if you add new lines to the JS editor, the editor size should stay the same, and it should get scrollbars. What happens is that the editor expands, and the iframe gets scrollbars.

Also, the editor doesn't get line numbers for the new lines: http://imgur.com/a/gmRmk.

**Comment by schalkneethling** [comment]
> Also, the editor doesn't get line numbers for the new lines:

Indeed, this is one of the limitations we are running into with Prism as it is not a code editor such as codemirror. All is not lost though. I was thinking that we could listen for when a user presses the enter/return key, and then call Prism.highlight again. This should solve the line number problem.
