### ISSUE TITLE
JS examples: need example for Array.flat()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1636]
-> https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

How to do this work: https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-JavaScript.md

Split out from https://github.com/mdn/interactive-examples/issues/1587.

**Comment by GAUTAMRAJU15** [comment]
Cool on it

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/interactive-examples/pull/1655.
