### ISSUE TITLE
CSS examples: need examples for border-inline property and its longhands

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1638]
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline

and its longhands:
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline-width
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline-style
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline-color

This property is part of the "logical properties". This group of properties set things like `padding`, `margin`, and `border`, but instead of using physical attributes to describe the part of the box (like top, left, bottom, right) they use logical attributes, that are relative to the direction in which the text runs, so as to make sense for vertical and RTL writing systems. In this case we set borders in the "inline" sides as opposed to "block" (see https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#Block_and_inline_dimensions).

This particular property is like setting https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end and https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start both together, and it would be fine to repurpose those interactive examples here.

**Comment by chrisdavidmills** [comment]
@sahilempire we would love your help; thanks !

**Comment by rachelandrew** [comment]
@sahilempire did you get chance to add these? If not I may well do them as I did the other logical properties examples. Let me know.

**Comment by sahilempire** [comment]
@rachelandrew I'm still working on this. And i understood, what i have to do.

**Comment by mattiapontonio** [comment]
I believe that you can do 2 branches and a PR on each other or in any case push different commits on the same PR being the assignees of an issue 2.

**Comment by rachelandrew** [comment]
Hi @sahilempire it looks like you haven't had chance to work on this so I'm going to reassign it to me, as I built the others so I can do these pretty quickly.

**Comment by sahilempire** [comment]
okay @rachelandrew , No Problem.

Thanks.
