### ISSUE TITLE
CSS examples: need example for image-rendering

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1641]
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

The page has a good description of the property and a live sample that could provide a basis for an interactive example, although it would be nice at least to use a different image, if possible. I don't know if you have to choose a particular type of image in order to see the effect -  guess at least it has to be scaled up or down.

Note that there are some browser compatibility considerations with the names for property values, and I see different results for the live sample between Firefox and Chrome.

**Comment by Blakelist7** [comment]
Hey @wbamberg @chrisdavidmills I would like to work on this issue if it is still open.
Please let me know

**Comment by wbamberg** [comment]
Sure, that would be great! Just ask if you need any help.

**Comment by Blakelist7** [comment]
Cool

**Comment by Blakelist7** [comment]
@wbamberg 
Hey, correct me if I am wrong .
We just have to add another example right?
I cloned the repo but I am unable to find the page that you linked in the issue. I only found a html page that has some lizard picture.
![Screenshot from 2021-05-05 18-33-52](https://user-images.githubusercontent.com/54525960/117145353-b23bd300-add0-11eb-8920-b9cd711b9f9f.png)
Could you help where I am getting it wrong?

**Comment by wbamberg** [comment]
Oh I'm sorry, @Blakelist7 , it looks as if this example has already been implemented, just not added to the MDN page for `image-rendering`.

If you want to take care of that, it would be a pull request to https://github.com/mdn/content/blob/main/files/en-us/web/css/image-rendering/index.html in the [mdn/content](https://github.com/mdn/content) repo, to add a line like:

```
 <div>{{EmbedInteractiveExample("pages/css/image-rendering.html")}}</div>
```

...after the first paragraph.

I'll have a look through the other open issues here to see which might be suitable for you, if you like.

**Comment by Blakelist7** [comment]
@wbamberg no issue, I will request a PR for this and let me know if you find other issue for me , thanks for that in advance.😀
