### ISSUE TITLE
CSS examples: need example for line-break

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1642]
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/line-break

There's a live sample in the page that could help guide an interactive example. But it would be *very* helpful for the author of this example to understand Chinese, Japanese, or Korean text.

**Comment by sahilempire** [comment]
I wanna work on this issue, **Please assign this to me**. **@wbamberg**

**Comment by schalkneethling** [comment]
> I wanna work on this issue, **Please assign this to me**. **@wbamberg**

Thank you so much for your interest, @sahilempire. I see someone else has already picked this up here: https://github.com/mdn/interactive-examples/pull/2132

**Comment by sahilempire** [comment]
okay, No Problem!

**Comment by NiedziolkaMichal** [comment]
This issue can be closed now.
