### ISSUE TITLE
CSS examples: need example for offset

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1643]
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset

This is a shorthand property for the properties used to animate an element along a path.

This is a relatively complex example to implement, but there are some nice interactive examples for some of the longhand properties, that could be adapted for this one. In particular https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset-path seems like a reasonable way to approach this. Note that this example uses a "Play/Pause" button to start and stop the animation, and this might be a good approach here rather than playing the animation automatically. The example for https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor uses the same approach.

**Comment by Blakelist7** [comment]
I'll like to give one shot at this one

**Comment by Blakelist7** [comment]
@wbamberg can you help me with this one ?
I'm not able to understand how to apply offset property
