### ISSUE TITLE
JS examples: need example for Intl.ListFormat.resolvedOptions()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1648]
See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/resolvedOptions.

The interactive example could follow a similar pattern to the example for [Intl.NumberFormat.resolvedOptions()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/resolvedOptions).

**Comment by IestynGage** [comment]
I'll have a look at this 😄

**Comment by IestynGage** [comment]
hey @wbamberg whats the next step? 😄

**Comment by wbamberg** [comment]
Apparently the next step is "ping me because I forgot" :). Sorry! I'll look at it now.

**Comment by NiedziolkaMichal** [comment]
Closed via #1986
