### ISSUE TITLE
JS examples: need example for Intl.NumberFormat.formatToParts()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1649]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

The interactive example could follow a similar pattern to the example for [Intl.RelativeTimeFormat.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/formatToParts).

**Comment by NiedziolkaMichal** [comment]
Closed via #1717
