### ISSUE TITLE
JS examples: need example for Intl.PluralRules.resolvedOptions()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1650]
See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/resolvedOptions.

The interactive example could follow a similar pattern to the example for [Intl.NumberFormat.resolvedOptions()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/resolvedOptions).

**Comment by asifurrahaman754** [comment]
please assign it to me

**Comment by asifurrahaman754** [comment]
added an pr, kindly check #2283

**Comment by NiedziolkaMichal** [comment]
Fixed by #2283
