### ISSUE TITLE
JS examples: need example for Intl.PluralRules.select()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1651]
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/select

**Comment by asifurrahaman754** [comment]
hello, @wbamberg do you mean add try-it for this example? if that's the case then you can assign it to me. Thanks

**Comment by wbamberg** [comment]
Yes, that's what I meant, @asifurrahaman754 . Thank you!

**Comment by asifurrahaman754** [comment]
hey @wbamberg i need small help, can you tell me how can i add the editor? to get an idea i saw the code of other examples, there were some paths like, "EmbedInteractiveExample("pages/js/globalprops-isfinite.html")" that were added to show the editor, but i cannot find any folder named pages/js/globalprops...

**Comment by asifurrahaman754** [comment]
hey, @wbamberg I have made the pr #2278 . Please check
