### ISSUE TITLE
JS examples: need example for Intl.PluralRules.supportedLocalesOf()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1652]
See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/supportedLocalesOf.

The interactive example could follow a similar pattern to the example for [Intl.DateTimeFormat.supportedLocalesOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/supportedLocalesOf).

**Comment by CreaTorAleXander** [comment]
I can do it
