### ISSUE TITLE
Broken image for CSS filter Demo https://developer.mozilla.org/en-US/docs/Web/CSS/filter

### ISSUE THREAD

**Issue by luka-bacic** [mdn/interactive-examples#1667]
# Request type
- [x] Correction or update
The image link needs updating

# Details
The image for the CSS filter Demo is broken

# Page in question
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

**Comment by schalkneethling** [comment]
this is resolved in:
https://github.com/mdn/interactive-examples/pull/1669

**Comment by schalkneethling** [comment]
Confirmed to work now on: https://developer.mozilla.org/en-US/docs/Web/CSS/filter
