### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

### ISSUE THREAD

**Issue by hacker-eleos** [mdn/interactive-examples#1670]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In background-position CSS documentation, the demo window seems illogical. Doesn't really convey any information about position while changing the property values.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
![image](https://user-images.githubusercontent.com/63001252/90367580-9ba8ec80-e086-11ea-831d-347c420c3f87.png)

**Comment by schalkneethling** [comment]
resolved in: https://github.com/mdn/interactive-examples/pull/1669

**Comment by schalkneethling** [comment]
Confirmed as resolved: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
