### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice

### ISSUE THREAD

**Issue by ajostel** [mdn/interactive-examples#1671]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The CSS demo doesn't work: the /media/examples/border-florid.svg is not accessible

**Comment by schalkneethling** [comment]
Confirmed to work at: https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
