### ISSUE TITLE
Need New labels

### ISSUE THREAD

**Issue by iamVP7** [mdn/interactive-examples#1710]
This is not related to code contribution, but can help contributors.

It will be good to have labels specifically like JS, CSS, HTML.

Yes the heading is helping a lot, but labeling will help in easy filtering for beginners like me.

If created, I can help in assigning labels.

**Comment by chrisdavidmills** [comment]
Hi @iamVP7 

Thanks for bringing this up. So to make sure I am understanding you correctly, you want to add labels to the open issues on this repo to indicate what subject areas they relate to, for easier triaging/contribution?

This being the case, I think it is a really good idea. For consistency, I think we should probably stick to the same scheme as our main sprints repo: https://github.com/mdn/sprints/labels/

If you agree, then I am happy to set up the labels, and then maybe you could help me to add them?

Let me know what you think, and thanks again!

**Comment by iamVP7** [comment]
`
Thanks for bringing this up. So to make sure I am understanding you correctly, you want to add labels to the open issues on this repo to indicate what subject areas they relate to, for easier triaging/contribution?
`
Exactly  this is the main reason.

`
This being the case, I think it is a really good idea. For consistency, I think we should probably stick to the same scheme as our main sprints repo: https://github.com/mdn/sprints/labels/
`

Checked the Sprints repo. Looked the below 3 will match to some extent.

1. Content:JS  for [JS examples](https://github.com/mdn/interactive-examples/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22+JS+examples%22)
2. Content:CSS for [CSS examples](https://github.com/mdn/interactive-examples/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22CSS+examples%22+)
3. Content:HTML for [HTML examples](https://github.com/mdn/interactive-examples/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22HTML+examples%22+)

Will love to know your thoughts on reusing them.

**Comment by chrisdavidmills** [comment]
I agree with you, and have created the labels: see https://github.com/mdn/interactive-examples/labels

**Comment by iamVP7** [comment]
Thanks @chrisdavidmills  :)  closing this comment.
