### ISSUE TITLE
JS Examples: String.prototype.replaceAll() demo is broken

### ISSUE THREAD

**Issue by XRFXLP** [mdn/interactive-examples#1715]
![image](https://user-images.githubusercontent.com/23459568/97310691-84a62800-1889-11eb-9940-6f966574b7b9.png)

The code example of replaceAll which is given [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) returns an error.

Step to reproduce:
1. Go to the attached link.
2. Click run.

**Comment by chrisdavidmills** [comment]
@XRFXLP This works for me, in Chrome and Firefox. Which browser are you using? Does it support [replaceAll()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#Browser_compatibility)?

**Comment by XRFXLP** [comment]
Firefox 76.

It turns out that my browser is not updated, since support of Firefox started from 77.
