### ISSUE TITLE
https://github.com/mdn/content/issues/154

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/interactive-examples#1734]
https://github.com/mdn/content/issues/154
@wbamberg @schalkneethling

**Comment by mattiapontonio** [comment]
@wbamberg @schalkneethling

**Comment by bershanskiy** [comment]
@mattiapontonio Since the original issue was moved to #1737, please consider closing this issue.

**Comment by mattiapontonio** [comment]
@bershanskiy yes thanks. Sounds like a bot 😊
