### ISSUE TITLE
lable attribute in the <option> example

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/interactive-examples#1737]
There Is no the `label` attribute in the example so Is not clear where them are rendered when You test it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

![Screenshot_20201205-230200.png](https://user-images.githubusercontent.com/44380480/101266736-2c98f600-3752-11eb-813f-eedc1af66d79.png)

**Comment by peterbe** [comment]
Now moved.
