### ISSUE TITLE
Decide on browser support baseline

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#177]
In order to determine things such as:

* Whether feature detection needs to be implemented for a specific feature
* Whether we should fallback to the no-js view

We need to define what our browser support looks like for the interactive examples.

I propose the following:

Firefox: Last three release channel versions
Chrome[Webkit]: Last three release channel versions
IE: 11+
Edge: Latest

Thoughts @stephaniehobson @wbamberg

**Comment by wbamberg** [comment]
Again, I'm happy to go with whatever you decide. Your suggestion sounds fine to me.

**Comment by schalkneethling** [comment]
Waiting on @stephaniehobson thoughts but, if she is happy with my suggestions as well. What do w do for browsers that does not meet our baseline? Here of course I am mainly(only?) referring to IE.

Should just fallback to the no-js experience for lteIE10?

**Comment by atopal** [comment]
No JS for lteIE10 sounds okay to me. It's share is tiny anyway. A bigger issue is Safari, what's the recommendation there?

**Comment by schalkneethling** [comment]
> No JS for lteIE10 sounds okay to me, its share is tiny anyway. A bigger issue is Safari, what's the recommendation there?

I do not believe Safari should prove to be to much of a problem but, I will do some proper testing and post feedback here.

**Comment by atopal** [comment]
Thanks Schalk, what I meant was that Safari has a bigger share on MDN, so we should state what our policy is for that. Latest version would be fine, or maybe last 2?

**Comment by schalkneethling** [comment]
> Thanks Schalk, what I meant was that Safari has a bigger share on MDN, so we should state what our policy is for that. Latest version would be fine, or maybe last 2?

I reckon people pretty much upgrade Safari as the new releases are released as part of an OS update. So yeah, latest two releases should be good.

**Comment by schalkneethling** [comment]
Added browser support information to README - https://github.com/mdn/interactive-examples#browser-support-baseline
