### ISSUE TITLE
Should we experiment with copy to clipboard functionality for the CSS examples?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#178]
Because of the single line nature of the CSS examples, a copy to clipboard button here makes a lot of sense to me. It is also almost a standard UI feature these days. While we will not have this for the JavaScript editor, perhaps we can add this to the CSS editor. This way we can see during user testing:

1. Whether the users actually click it
2. Whether users notice that it is missing for the JS examples

In terms of implementation. I would say that we use `clipboard.js` and implement in the same style as is in use on Github i.e.

<img width="339" alt="screen shot 2017-08-08 at 13 12 12" src="https://user-images.githubusercontent.com/10350960/29069424-3bce5708-7c3b-11e7-9a44-a1fc8508808a.png">

Thoughts @wbamberg @stephaniehobson

**Comment by stephaniehobson** [comment]
Because we are short on horizontal space I would like to use the pop up menu that Brigade suggested for this functionality. It's definitely worth experimenting with this on the CSS and watching the analytics to see if it's used.

**Comment by wbamberg** [comment]
I like Schalk's version a lot more than the pop up. I'm bothered that the pop up menu obscures content (always) while the Schalk's version above just reduces horizontal space a little, which only obscures content for lines long enough.

Is it worth considering using Schalk's, but only showing it while the mouse is over the selected row?

**Comment by schalkneethling** [comment]
Ok, I have implemented an experiment that is a kind of combination of the ideas we have all had. Have a look and let me know your thoughts:

https://github.com/mdn/interactive-examples/pull/189

Would also be interesting to see how the test users respond to it.

**Comment by stephaniehobson** [comment]
I'm still against taking up any of the horizontal space for this feature but interested to see how the user testing goes.

**Comment by schalkneethling** [comment]
You can see the current experiment here:
https://interactive-examples.mdn.mozilla.net/pages/css/border-style.html

**Comment by schalkneethling** [comment]
> I'm still against taking up any of the horizontal space for this feature but interested to see how the user testing goes.

Yup, I mainly did this as an experiment so we can get user feedback. We can make a call whether to keep, or drop it when the testing concludes.

**Comment by schalkneethling** [comment]
@wbamberg @atopal @stephaniehobson Do we want to keep this on the CSS examples for the beta testing phase?

**Comment by stephaniehobson** [comment]
Is it instrumented?

**Comment by schalkneethling** [comment]
> Is it instrumented?

Yes it is. https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/clippy.js#L25

**Comment by atopal** [comment]
I'd suggest we keep it and measure engagement with it.
