### ISSUE TITLE
Should we add the bold variant of the Zilla font and use it for headings?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#179]
The question came up in the most recent meeting notes so, I thought it warrants an open discussion here so that we can make a call on it. @wbamberg @stephaniehobson

**Comment by wbamberg** [comment]
I'm happy to go along with whatever you and @stephaniehobson decide.

**Comment by schalkneethling** [comment]
This is what it looks like with Zilla Bold:

<img width="1136" alt="screen shot 2017-08-09 at 16 56 57" src="https://user-images.githubusercontent.com/10350960/29128336-d68da012-7d23-11e7-9e8a-e85516990f3d.png">

**Comment by stephaniehobson** [comment]
I'm leaning towards no. We had so many problems with it on kuma and it will slow down display of the title.

**Comment by schalkneethling** [comment]
I have added Zilla Bold and I am using it for the main heading. If this looks good for everyone, I will go ahead an close out this one.

**Comment by atopal** [comment]
I'm with Stephanie on this one. If it slows down the page load, because the web font has to be loaded, it's not worth it.

**Comment by schalkneethling** [comment]
@atopal @stephaniehobson I absolutely agree. I also do not feel like it looks that much "better" than a standard `sans-serif` therefore, the pros win.
