### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by Elchi3** [mdn/interactive-examples#1794]
https://github.com/github/renaming#renaming-existing-branches

**Comment by peterbe** [comment]
[The mdn/content repo has already solve this :)](https://github.com/mdn/yari/discussions/3427)

**Comment by wbamberg** [comment]
@schalkneethling , can you do this? I don't apparently have the permissions.

**Comment by schalkneethling** [comment]
> @schalkneethling , can you do this? I don't apparently have the permissions.

Done.

**Comment by wbamberg** [comment]
Thanks!
