### ISSUE TITLE
Scroll bars always visible even when no scrolling

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#181]
Kadir and I both have the OSX system preference to show the scroll bar track when there is a scroll bar present. I believe the use of `overflow: scroll;` is causing the scroll bar tracks to appear even when there is no scroll bar. Maybe `overflow: auto`?

<img width="496" alt="screen shot 2017-08-08 at 10 01 29" src="https://user-images.githubusercontent.com/854701/29084500-03b366c0-7c21-11e7-9f7c-91eff93107be.png">

**Comment by stephaniehobson** [comment]
It's even weirder with scroll bars:

<img width="913" alt="screen shot 2017-08-08 at 14 35 20" src="https://user-images.githubusercontent.com/854701/29095749-e2349746-7c46-11e7-84de-e254ea7e5db5.png">x

**Comment by stephaniehobson** [comment]
Our user today ran into this problem too. I now suspect it effects everything except default OSX configuration. They were using Windows 10 and had the scrollbars in both Chrome and Firefox.

**Comment by schalkneethling** [comment]
This seemed to have fixed it for me:
https://github.com/mdn/interactive-examples/blob/master/css/editor-libs/common.css#L2

I will double check though, as the above will not have any effect in Chrome.
