### ISSUE TITLE
Syncronize breakpoints between kuma and samples

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#182]
We should check that the kuma iframes are re-sizing at the right place for the examples and that they are resized to the correct dimensions for the examples. (https://developer.mozilla.org/en-US/docs/User:stephaniehobson:interactive has problems but I'm not sure it is running the most recent version of the code either?)

**Comment by schalkneethling** [comment]
Here are the heights I have been able to work out. Some of these are *very* tall so, I am wondering whether we should not consider setting a fixed height, and making the CSS examples list scrollable should it go beyond the available height. Thoughts @wbamberg @stephaniehobson 

## CSS

```
@media (min-width: 47.9385em)
.interactive {
    height: 390px;
}
```

### Large

```
@media (min-width: 47.9385em)
.interactive-large {
    height: 635px;
}
```

### Stacked

```
.interactive {
    height: 650px;
    width: 100%;
}
```

### Stacked Large

```
.interactive-large {
    height: 1020px;
}
```

### JS

```
@media (min-width: 47.9385em)
.interactive-js {
    height: 400px;
}
```

**Comment by schalkneethling** [comment]
Here is the PR for the `postMessage` listener on the Kuma side:
https://github.com/mozilla/kuma/pull/4361

**Comment by schalkneethling** [comment]
Follow up PR: https://github.com/mozilla/kuma/pull/4369

**Comment by schalkneethling** [comment]
The code merged here today, in combination with this pull request, should resolve this:
https://github.com/mozilla/kuma/pull/4379
