### ISSUE TITLE
The title attribute example should be updated to not use abbr elements

### ISSUE THREAD

**Issue by ericwbailey** [mdn/interactive-examples#1822]
The `title` attribute used on an `abbr` element has [numerous accessibility issues](https://www.tpgi.com/short-note-the-abbreviation-appreciation-society/). Can we update it to demonstrate a more appropriate usage?

I was thinking along the lines of:

```html
<iframe title="Wikipedia page for Tangerines" src="https://en.m.wikipedia.org/wiki/Tangerine"></iframe>
```

**Comment by escattone** [comment]
Thanks @ericwbailey -- cc @schalkneethling.

**Comment by schalkneethling** [comment]
Thanks, @ericwbailey - I wonder if we should add a link to the post you referenced here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#accessibility_concerns

I can take care of updating the example to demonstrate it on an `iframe` instead as you demonstrated.

**Comment by ericwbailey** [comment]
>I wonder if we should add a link to the post you referenced here:
developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#accessibility_concerns

@schalkneethling Sounds like a great idea. Will do!
