### ISSUE TITLE
Each of the interactive examples should shift to a column layout at smaller viewports

### ISSUE THREAD

**Issue by tannerdolby** [mdn/interactive-examples#1834]
> On MDN pages the editor is laid out "side by side": that is with the example choices on the left and the output on the right, as it is in the local server that's started by yarn start. Then if the page width goes below some threshold it switches to "top and bottom", with the example choices above and the output below.

https://github.com/mdn/interactive-examples/blob/master/CSS-Example-Style-Guide.md#output-width-considerations

I proposed a shift to column layout with a media query in the mentioned issue above. But wanted to create this issue explicitly to shed light on the fact that interactive examples stay "side by side" forever and don't change layout to a column layout at smaller viewport widths like stated in the `mdn/interactive-examples` CSS style guide.

Related:
#1825 
[#1720](https://github.com/mdn/yari/issues/1720) - `mdn/yari`

**Comment by tannerdolby** [comment]
Having your eyes on this would be great @schalkneethling !

**Comment by tannerdolby** [comment]
> Also, while working on something else I believe I found why this may not be happening anymore. We used to have the communication between the iframe and the parent document via `postMessage` that would cause the code in the iframe to toggle a class on the container. This is no longer happening 😱 - Perhaps we will just resurrect that, or decide on a completely new approach.

I think resurrecting the `postMessage` so that a class is toggled on the container would be ideal. Depending on how much fuss it is to bring this back, we can decide on whether spinning up a whole new approach would be the better option.

**Comment by schalkneethling** [comment]
See comment here https://github.com/mdn/interactive-examples/issues/1849#issuecomment-860549513

**Comment by NiedziolkaMichal** [comment]
This is now fixed. Thanks a lot for reporting this issue.
