### ISSUE TITLE
Remove allcontributors in favour of native Github

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#1838]
If we are not going to keep this up to date, shouldn't we remove it?

_Originally posted by @wbamberg in https://github.com/mdn/interactive-examples/issues/1487#issuecomment-852290028_

**Comment by NiedziolkaMichal** [comment]
This should be closed.

**Comment by wbamberg** [comment]
I'm not sure why, it is still here isn't it? https://github.com/mdn/interactive-examples/blob/main/.all-contributorsrc

**Comment by NiedziolkaMichal** [comment]
I am sorry, you are right. I thought it was removed.
