### ISSUE TITLE
Removes inner container from example output for better responsiveness

### ISSUE THREAD

**Issue by tannerdolby** [mdn/interactive-examples#1849]
Related to #1825 

A dedicated issue for removing the inner container `.example-container` for interactive examples in `css-examples`. Not all of the CSS examples have a nested `.example-container` and some that do don't need it to be removed. There is a handful that have the inner container and need it removed, a majority in the `flexbox` section that we have already fixed but the full possible list is below. I used `git grep` to find all the occurrences of `.example-container` and this was the log:

```
tannerdolby:interactive-examples TannerDolby$ git grep -n "example-container"
live-examples/css-examples/basic-box-model/clear.css:1:.example-container {
live-examples/css-examples/basic-box-model/clear.html:33:        <div class="example-container">
live-examples/css-examples/basic-box-model/float.css:1:.example-container {
live-examples/css-examples/basic-box-model/float.html:26:        <div class="example-container">
live-examples/css-examples/basic-box-model/visibility.css:1:.example-container {
live-examples/css-examples/basic-box-model/visibility.css:10:.example-container > div {
live-examples/css-examples/basic-box-model/visibility.html:26:        <div class="example-container">
live-examples/css-examples/basic-user-interface/user-select.css:1:.example-container {
live-examples/css-examples/basic-user-interface/user-select.html:19:    <div class="example-container">
live-examples/css-examples/box-alignment/align-content.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/align-items.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/align-self.css:1:.example-container {
live-examples/css-examples/box-alignment/align-self.css:12:.example-container > div {
live-examples/css-examples/box-alignment/align-self.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/column-gap.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/gap.html:40:        <div class="example-container">
live-examples/css-examples/box-alignment/justify-content.html:40:        <div class="example-container">
live-examples/css-examples/box-alignment/justify-items.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/justify-self.css:1:.example-container {
live-examples/css-examples/box-alignment/justify-self.css:12:.example-container > div {
live-examples/css-examples/box-alignment/justify-self.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/place-content.html:40:        <div class="example-container">
live-examples/css-examples/box-alignment/place-items.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/place-self.css:1:.example-container {
live-examples/css-examples/box-alignment/place-self.css:12:.example-container > div {
live-examples/css-examples/box-alignment/place-self.html:33:        <div class="example-container">
live-examples/css-examples/box-alignment/row-gap.html:33:        <div class="example-container">
live-examples/css-examples/compositing-and-blending/background-blend-mode.html:33:        <div class="example-container">
live-examples/css-examples/compositing-and-blending/mix-blend-mode.css:1:.example-container {
live-examples/css-examples/compositing-and-blending/mix-blend-mode.html:33:        <div class="example-container">
live-examples/css-examples/filter-effects/backdrop-filter.css:1:.example-container {
live-examples/css-examples/filter-effects/backdrop-filter.html:26:        <div class="example-container">
live-examples/css-examples/fragmentation/box-decoration-break.css:1:#example-container {
live-examples/css-examples/fragmentation/box-decoration-break.html:23:        <div id="example-container">
live-examples/css-examples/grid/function-fit-content.html:26:        <div class="example-container">
live-examples/css-examples/grid/function-minmax.html:26:        <div class="example-container">
live-examples/css-examples/grid/function-repeat.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-area.css:1:.example-container {
live-examples/css-examples/grid/grid-area.css:16:.example-container > div {
live-examples/css-examples/grid/grid-area.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-auto-columns.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-auto-flow.html:26:        <div class="example-container">
live-examples/css-examples/grid/grid-auto-rows.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-column-end.css:1:.example-container {
live-examples/css-examples/grid/grid-column-end.css:12:.example-container > div {
live-examples/css-examples/grid/grid-column-end.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-column-start.css:1:.example-container {
live-examples/css-examples/grid/grid-column-start.css:12:.example-container > div {
live-examples/css-examples/grid/grid-column-start.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-column.css:1:.example-container {
live-examples/css-examples/grid/grid-column.css:12:.example-container > div {
live-examples/css-examples/grid/grid-column.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-row-end.css:1:.example-container {
live-examples/css-examples/grid/grid-row-end.css:12:.example-container > div {
live-examples/css-examples/grid/grid-row-end.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-row-start.css:1:.example-container {
live-examples/css-examples/grid/grid-row-start.css:12:.example-container > div {
live-examples/css-examples/grid/grid-row-start.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-row.css:1:.example-container {
live-examples/css-examples/grid/grid-row.css:12:.example-container > div {
live-examples/css-examples/grid/grid-row.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-template-areas.html:35:        <div class="example-container">
live-examples/css-examples/grid/grid-template-columns.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-template-rows.html:33:        <div class="example-container">
live-examples/css-examples/grid/grid-template.html:35:        <div class="example-container">
live-examples/css-examples/grid/grid.html:26:        <div class="example-container">
live-examples/css-examples/logical-properties/inset-block-end.html:34:        <div class="example-container" id="example-element">
live-examples/css-examples/logical-properties/inset-block-start.html:34:        <div class="example-container" id="example-element">
live-examples/css-examples/logical-properties/inset-inline-end.html:34:        <div class="example-container" id="example-element">
live-examples/css-examples/logical-properties/inset-inline-start.html:34:        <div class="example-container" id="example-element">
live-examples/css-examples/masking/clip-path.css:5:.example-container {
live-examples/css-examples/masking/clip-path.html:33:        <div class="example-container">
live-examples/css-examples/masking/mask-position.css:5:.example-container {
live-examples/css-examples/masking/mask-position.html:33:        <div class="example-container">
live-examples/css-examples/positioned-layout/bottom.html:33:    <section id="default-example"><div class="example-container">
live-examples/css-examples/positioned-layout/left.html:33:    <section id="default-example"><div class="example-container">
live-examples/css-examples/positioned-layout/offsets.css:1:.example-container {
live-examples/css-examples/positioned-layout/right.html:33:    <section id="default-example"><div class="example-container">
live-examples/css-examples/positioned-layout/top.html:33:    <section id="default-example"><div class="example-container">
live-examples/css-examples/rhythm/line-height-step.css:1:.example-container {
live-examples/css-examples/rhythm/line-height-step.css:14:.example-container h2, p {
live-examples/css-examples/rhythm/line-height-step.css:18:.example-container h2 {
live-examples/css-examples/rhythm/line-height-step.html:26:        <div class="example-container" id="example-element"> 
live-examples/css-examples/shapes/shape-image-threshold.css:1:.example-container {
live-examples/css-examples/shapes/shape-image-threshold.html:32:        <div class="example-container">
live-examples/css-examples/shapes/shape-margin.css:1:.example-container {
live-examples/css-examples/shapes/shape-margin.html:33:        <div class="example-container">
live-examples/css-examples/shapes/shape-outside.css:1:.example-container {
live-examples/css-examples/shapes/shape-outside.html:33:        <div class="example-container">
live-examples/css-examples/text/overflow-wrap.css:1:.example-container {
live-examples/css-examples/text/overflow-wrap.html:28:        <div class="example-container">Most words are short &amp; don't need to break. But <b class="transition-all" id="example-element">Antidisestablishmentarianism</b> is long. The width is set to min-content, with a max-width of 11em.</div>
live-examples/css-examples/transforms/transform-origin.css:21:#example-container {
live-examples/css-examples/transforms/transform-origin.html:33:        <div id="example-container">
(END)
```

There is quite a few, but atleast this narrows it down and verifies the only interactive examples that might have the `.example-container` class are within the `css-examples` directory. I'm looking through each of the files listed above and checking to see if removing the inner container is needed as some in the list above don't need it.

After removing the inner container for those that have it (and need it to be removed for better responsiveness of demo output), now for all viewports there is visible output change when you select different example choices, (around mobile viewport sizes it gets too squished and should shift to column layout but that is being discussed in #1834) when previously it would sometimes be completely a mystery whether the example choices produced any different output as the amount of space the example output had to occupy wasn't very much as the viewport width got smaller. 

Before:

```html
<section id="default-example" class="default-example">
   <div class="example-container">
       <div id="example-element" class="transition-all">Order me</div>
       <div style="order: 1">Order 1</div>
       <div style="order: 2">Order 2</div>
       <div style="order: 2">Order 2</div>
       <div style="order: 3">Order 3</div>
   </div>
</section>
```

After inner container `.example-container` is removed:

```html
<section id="default-example" class="default-example">
   <div id="example-element" class="transition-all">Order me</div>
   <div style="order: 1">Order 1</div>
   <div style="order: 2">Order 2</div>
   <div style="order: 2">Order 2</div>
   <div style="order: 3">Order 3</div>
</section>
```

**Comment by tannerdolby** [comment]
Some containers dont need to be modified like mentioned above, as they don't have the extra inner container `.example-container` and that HTML looks like this:

```html
<section id="default-example" class="default-example">
  <div id="example-element" class="transition-all">
     <div>Item One</div>
     <div>Item Two</div>
     <div>Item Three</div>
     <div>Item Four</div>
     <div>Item Five</div>
     <div>Item Six</div>
  </div>
</section>
```

**Comment by tannerdolby** [comment]
I went through each of the pages listed in the comment above and tested each example to see if it was working correctly for all viewports (<450px). For almost all of the pages, everything is working correctly and the interactive example demo output is functional for pretty much all screen sizes besides the mobile viewports where its squished from staying in a row layout.

Oddly enough, this problem of the example output not changing when selecting different example choices primarily occurred in the `flexbox` css examples. There was only one example that could benefit from removing in the inner container from the list shown in the comment above. 

I think this is pretty much "handled" for now as I can't find any css-examples for viewports > 450px where a example isn't functioning as expected. It really was only a problem in the flexbox examples. Ping! :) @schalkneethling

**Comment by schalkneethling** [comment]
> I went through all of the pages listed in the comment above and tested each example to see if it was working correctly for all viewports (>450px). For 99% of the pages, everything is working correctly and the interactive example demo output is functional for pretty much all screen sizes besides the mobile viewports where its squished from staying in a row layout. The only page that needed to have the inner container removed was `order.html` in the `flexbox` section.
> 
> Oddly enough, this problem of the example output not changing when selecting different example choices primarily occurred in the `flexbox` css examples. There was only one example that could benefit from removing in the inner container from the list shown in the comment above.
> 
> I think this is pretty much "handled" for now as I can't find any css-examples other than the `order.html` page for viewports > 450px where a example isn't functioning as expected. It really was only a problem in the flexbox examples. Ping! :) @schalkneethling

Wow, that is great news. Thank you so much for all the research @tannerdolby! What I would say we should then do is:

1. Update those that remain i.e. `order.html` and any other that will benefit.
2. Put https://github.com/mdn/interactive-examples/issues/1834 on the back-burner while we make some decisions around interactive examples on mobile phones - There is a redesign pending where we can address this

And I think that is pretty much it. Thoughts?

**Comment by tannerdolby** [comment]
> Wow, that is great news. Thank you so much for all the research @tannerdolby! What I would say we should then do is: 1. Update those that remain i.e. order.html and any other that will benefit. 2. Put #1834 on the back-burner while we make some decisions around interactive examples on mobile phones - There is a redesign pending where we can address this

Your welcome @schalkneethling ! The `order.html` page is fixed in #1850, not sure if any other JS or HTML examples have any issues since I only checked the CSS sections but I will slowly make my way through checking each of those too. 

In regards to #1834, I think putting it on the back burner for now until we make some choices around interactive examples on mobile phones is OK. Once the pending redesign (I'd love to have a look, unless its private which I understand) comes to conclusion lets jump on this because the current UI/UX of the interactive examples on mobile phones isn't ideal since they are so squished together in the row format with the output overflowing its parent container, rendering most of them not functional on mobile viewports. 

I think that is pretty much it too. I'm glad this "removal of inner container" issue only affected a small number of interactive examples. Once #1850 is merged to fix `order.html`, then this issue is prime for closing and we can move all energy to #1834 for figuring out mobile redesign for interactive examples.

**Comment by schalkneethling** [comment]
> I'd love to have a look, unless its private which I understand

I am hoping and advocating for doing this in the open :)

**Comment by tannerdolby** [comment]
> I am hoping and advocating for doing this in the open :)

Ok great :) My fingers are crossed it can be done in the open because I would love to be apart.
