### ISSUE TITLE
Code snippet incorrect 

### ISSUE THREAD

**Issue by Biki-das** [mdn/interactive-examples#1891]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE

What information was incorrect, unhelpful, or incomplete?

`function multiply(x, y) {
  if (x * y < Number.MIN_VALUE) {
    return 'Process as -Infinity';
  }
  return (x * y);
}

console.log(multiply(5e-324, 1));
// expected output: 5e-324

console.log(multiply(-1.7976931348623157e+308, 2));
// expected output: Process as -Infinity`

the above code has incorrect return values and expected output

Specific section or headline?
Demo

What did you expect to see?

`function divide(x, y) {
  if (x / y < Number.MIN_VALUE) {
    return 'Process as 0';
  }
  return (x / y);
}

console.log(divide(5e-324, 1));
// expected output: 5e-324

console.log(divide(5e-324, 2));
// expected output: Process as 0`

Did you test this? If so, how?
Checked the example in browser

I have already opened a PR, to solve the issue , please look upto it.
here is the PR link-https://github.com/mdn/interactive-examples/pull/1890#issuecomment-899639131

**Comment by teoli2003** [comment]
Closed by #1890
