### ISSUE TITLE
Where would I create example for self.reportError?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/interactive-examples#1919]
Context is here: https://github.com/mdn/content/issues/8608

This belongs to top level Window or Worker API, that may eventually make it to note - i.e it is a global function. I can't find a good location in the folder structure for thsi.

The example will just look like this.
```
var newError = new Error('Some error message', "someFile.js", 11);
self.reportError(newError);

window.onerror = function(message, source, lineno, colno, error) {
  console.log('message:' + error.message + ', lineno: ' + lineno );
  return true;
};

self.addEventListener('error', (error) => {
    console.log(error.filename);
});

// Output
// > "message:Some error message, lineno: 11"
// > "someFile.js"
```

EDITED: Note, I have proceeded without this, but would still like advice. This is similar to asking where I would put an example for `fetch()`, `atob()` or one of the other global functions.

**Comment by wbamberg** [comment]
We don't have any interactive examples for Web/API at the moment, and implementing that is a big project. So the answer is "nowhere".
