### ISSUE TITLE
Remove eslint ignored files

### ISSUE THREAD

**Issue by Rumyra** [mdn/interactive-examples#1922]
eslint does not support static initialization blocks in js classes ... yet. This meant two js examples were failing tests - they have both been added to the `.eslintignore` file. They are:

* live-examples/js-examples/classes/classes-static-initialization.js
* live-examples/js-examples/classes/classes-static.js

Once [this issue](https://github.com/eslint/eslint/issues/15016) has been resolved and eslint supports static blocks, we can remove these files from the ignore file

**Comment by ddbeck** [comment]
The actual changes are:

- https://github.com/mdn/interactive-examples/commit/c35c3c653a645a9440819751690101dc772098a0
- https://github.com/mdn/interactive-examples/commit/3f6ed18a5d629f5e32d19f5a46f88efd55a7ebc8
