### ISSUE TITLE
CSS examples: add a delay to the "invalid CSS" indicator

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#199]
In the CSS editor, if the CSS is invalid, then you get an orange border with a cross, the "invalid CSS indicator".

This is great, except that the CSS is applied as you type. So suppose you start with, say `color: blue;` and want to change `blue` to `red`. You delete `blue`, start typing - and the "invalid CSS indicator" comes up, even as you are typing. This is quite off-putting I think.

It would be better if there was a delay: the CSS is only applied, say, .5 seconds after the last keystroke. Or, the CSS is applied immediately, but the "invalid CSS indicator" is only shown .5 seconds after the last keystroke.

This is just an enhancement, not a blocker.

**Comment by atopal** [comment]
My vote would be to apply the CSS immediately, but only show the invalid indicator with a delay. That way, quick changes of value that are always valid (like adding a 0 to a value) would still show up immediately as expected.

**Comment by wbamberg** [comment]
Sorry to reopen, but the implementation of this isn't quite right. The idea would be that the yellow border is only shown 500ms (or whatever) after the *last* keystroke. That is, the clock is reset every time the user presses a key, and the border only changes color when it runs out.

So, say we start off with:

`color: green;`

I select  `green`, delete and type `b`,`l`,`u`,`e`.

Technically, I'm in an invalid state from the point I delete `green` until I've typed the `e`. Say each keystroke takes me 200ms: that's 800ms. But because I'm typing, I reset the clock, so the border never changes to yellow. Unless I do make a mistake, and type `blug` or something, then I see the yellow indicator 500ms after typing `g`.

Does that make sense?

**Comment by schalkneethling** [comment]
Gotcha!
