### ISSUE TITLE
CSS examples: the "X" should have a tooltip

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#200]
This came up a couple of times in user testing. It seems like it would be good for the "X" "invalid CSS" icon to have a tooltip, like:

"The CSS you entered is invalid."

or something better..

**Comment by schalkneethling** [comment]
@wbamberg Do you mean for this to show when you hover over the `X` or, by default?

**Comment by wbamberg** [comment]
Only when you hover.

Do you think this suggestion is a good idea?

**Comment by schalkneethling** [comment]
> Only when you hover.

I was thinking that as well

> Do you think this suggestion is a good idea?

I am torn on this one. It is not a big thing to add but, would this add value? We cannot tell the user what is wrong just that the code is not valid. I am also thinking, what if someone completely changes the code and, it is valid, but not supported?

We have no way of distinguishing between those two scenarios. Perhaps we should leave this open until @stephaniehobson has a chance to give her thoughts?

**Comment by schalkneethling** [comment]
I also landed https://github.com/mdn/interactive-examples/issues/199 with a delay of 500ms that might make this not needed anymore? We can also bump it up to 1 second if 500ms is to quick? @wbamberg @stephaniehobson

**Comment by stephaniehobson** [comment]
The "x" should have a tool tip even though it will just be something like "This CSS is invalid". One of the user testers did hover over it to try to verify if his speculation about what it meant was accurate. 

I'm trying to think of a more friendly message. "There is an error in this CSS"? I dunno.

**Comment by stephaniehobson** [comment]
In a perfect world we give them as much help as we can but I don't want to block the beta on this.

"There is an error in this CSS. Check that you are using the correct syntax and spelling. You can try copying from another examples or using the reset button to return to the original state."

**Comment by schalkneethling** [comment]
Looking at this some more, there are a couple of additional things to consider here:

* Currently the indicator is shown using generated content so, adding a hover state to the icon looks to be something that cannot be done at the moment and, there is the inherit a11y issues that will introduce as well.
* We can turn these into an empty `div`, set the icons as background images on that, and use the div for the hover target. Couple of issues here. A11y wise it is not any better than if the above was possible. This means we need to add a bunch of empty `div` elements to each example option, which can be a lot in a case such as filter[1] (We could get around this using JavaScript and a single div but, as the information we are providing is not great, is all this really worth it?). Hover is not great for mobile.
* On the last point though, this brings up another thing. We hide these completely on mobile which includes tablet.

Thoughts @wbamberg @stephaniehobson?

[1] https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/filter.html

**Comment by stephaniehobson** [comment]
I think it's important to have a tool tip, we did see people not understand the "x" in testing.

But I would not block launch on this.

**Comment by schalkneethling** [comment]
Moved to target official version release after beta.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CSS examples: the "X" should have a tooltip](https://trello.com/c/dOXY4ZS1/6-css-examples-the-x-should-have-a-tooltip)

**Comment by schalkneethling** [comment]
I know we do not want to muck to much with the codebase while we are running the code live for a potential large number of users. I am simply going through the list of issues to see what there is, what is still an issue, and which we can close.

With the entire FYI ;p what are people's thoughts on this one?

* [ ] Yup
* [ ] Nope

@wbamberg @stephaniehobson @atopal

**Comment by wbamberg** [comment]
Personally I don't think we need this.
