### ISSUE TITLE
Add voting or, link to two question survey

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#203]
To help us determine the value added by the interactive editors, we want to add either a simple up/down voting system below the editor or, link to a short two questions survey i.e.

Does the interactive editor add value [Yes|No]
Comments: [freeform]

This needs to be implemented on the Kuma side, and will likely need some guidance from @stephaniehobson

**Comment by schalkneethling** [comment]
First version of the survey has been set-up and a link sent out to @wbamberg @atopal and @stephaniehobson for comments.

**Comment by stephaniehobson** [comment]
I don't think the survey needs the "This 1-2 minute survey consists of only one page and 1-2 questions." line and we could encourage more feedback by making the comment box a text area.

**Comment by schalkneethling** [comment]
We need to update the macro on KumaScript to also output the link the the survey just below the iframe.

**Comment by schalkneethling** [comment]
I have updated the survey and sent out the test for review.

**Comment by schalkneethling** [comment]
PR for changes on Kumascript: https://github.com/mdn/kumascript/pull/291
