### ISSUE TITLE
box-shadow: Hard to read in dark mode

### ISSUE THREAD

**Issue by GeorgeDaris** [mdn/interactive-examples#2032]
![MDN Dark Mode issue](https://user-images.githubusercontent.com/88941705/156565787-c92fc1e4-c99e-41dc-80db-4eefc2fd4d01.PNG)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

When viewed with the new dark mode, the text of the box, as well as the border surrounding it, become eligible.  

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/box-shadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/box-shadow/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
I made [Pull Request](https://github.com/mdn/interactive-examples/pull/2034) that removes "color: #333;" and fixes this issue.
