### ISSUE TITLE
Datalist is not showing value of option tag in Firefox Nightly.

### ISSUE THREAD

**Issue by Sadowskyy** [mdn/interactive-examples#2077]
Problem exists only in Firefox Nightly in Brave, Chrome etc. everything is ok. 

When I have code like that below:
`<option value="Sweet">Chocolate</option>`

I have only Chocolate displayed :(
I can make  `<option value="Sweet Chocolate">` and it works, but why that code above dosen't works only in Firefox Nightly?

**Comment by NiedziolkaMichal** [comment]
It's browser dependant feature.
On Firefox, Firefox Nightly & Internet Explorer: just element inner content is displayed in a drop-down, while value is actually placed in the text box when option is selected.
On Safari: inner content is ignored when attribute value is present.
On Chromium: Both inner content and content of value attribute are displayed.

I will include info about it in the datalist element.

**Comment by wbamberg** [comment]
So I uess we can close this? Thank you @Sadowskyy for filing and @NiedziolkaMichal for the explanation and fix!
