### ISSUE TITLE
Expanding field on CSS examples, distracting or beneficial

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#210]
I have added an experimental enhancement to the CSS editor a little while back. The feature basically expands an option when selected. This is more visible on examples with fever options than those like `filter`

The reasoning behind it is to draw the user's attention to the selected option a little more by changing colour, but then also adding the small animation of the field expanding.

@wbamberg mentioned that he finds it a bit distracting, and obviously this is not the intent. This is to discuss whether we want to keep it, or remove it before going into beta testing.

@stephaniehobson @atopal

**Comment by atopal** [comment]
I'm not seeing any resizing, do you have an example for that?

**Comment by schalkneethling** [comment]
@atopal Sure, have a look here and tab through, or click through the examples:
https://developer.allizom.org/en-US/docs/User:schalkneethling2:background-clip

**Comment by atopal** [comment]
I kinda like that, but from user testing it looks like it's not necessary for people to tell that these are different options. I have a bigger problem with the default height. The code has a lot of white space around it. Is that necessary?

**Comment by wbamberg** [comment]
Also, they don't all expand the same amount. Looking at https://interactive-examples.mdn.mozilla.net/pages/css/background-size.html, the first choice expands much more than the second.

To me it feels like there's a lot of movement going on: there's the transition in the output box from one state to the next, there's the transition on the arrow, and now the the up/down transition in the box resizing. It just feels like too much. Compared with https://interactive-examples.mdn.mozilla.net/pages/css/background-color.html, feels better to me.

> The code has a lot of white space around it. Is that necessary?

I think this is because the iframe has a fixed minimum size, so when a property has fewer choices, they will expand to fill the available space. I think this is going to be kind of inevitable with 3-choice pages.

**Comment by schalkneethling** [comment]
> To me it feels like there's a lot of movement going on: there's the transition in the output box from > one state to the next, there's the transition on the arrow, and now the the up/down transition in the box resizing. It just feels like too much.

I am more than happy to back that out. @atopal is correct that the user testing did not seem to bring up a need for it, so we can totally remove it.

> I think this is because the iframe has a fixed minimum size, so when a property has fewer choices, > they will expand to fill the available space.

Yes. We spoke about this a while back, and because we wanted to have fixed heights for the various editors to make the iframe height handling simpler, we decided to use `flex-box` ability to automatically expand elements to fit their container.

So, as @wbamberg mentioned, if there are a small number of options, the container for each example will be much larger than when there are a lot of options, such as on filter or transform.

With that said, with the code I added to this project, and this PR[1], the iframe should size based on the height of the iframe content. This means, we can switch from a `min-height` to a `max-height` perhaps? And then we no longer need the expansion of the individual options.

We will be able to make a more informed decisions once we can test the `iframe` code on staging, or even production.

Thoughts @wbamberg @atopal @stephaniehobson 

[1] https://github.com/mozilla/kuma/pull/4361

**Comment by wbamberg** [comment]
Yes, the changes you're making definitely give us more flexibility to choose a size. But we might still want to have a minimum height, to ensure that the output box is high enough, and maybe even just for aesthetics. So it's still possible that when we have 3 (or [maybe even 2](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing)) options, then their boxes will be taller, and that's probably the right thing to do in these cases.

**Comment by stephaniehobson** [comment]
I would like to avoid re-sizing things on the page as much as possible. I don't want someone on a slow connection who has scrolled do the page and started reading to lose their place when the interactive examples frame re-sizes itself. 

It will also make life easier for the people coding the examples if they know they have a consistent minimum height for the display area.

I think we should have a default height that the vast majority of examples conform to.

This thread was about resizing the currently selected example though and I agree we should remove it. It's neat but if we can simplify the interface without impacting the user's understanding that's preferable.
