### ISSUE TITLE
Setup pages for beta testing

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#211]
For the beta testing phase of the project, we need to set-up three pages for the CSS examples, and three for JS on production. For the JavaScript side, duplicates of the following pages on staging will most likely be sufficient:

* https://developer.allizom.org/en-US/docs/User:schalkneethling2:push
* https://developer.allizom.org/en-US/docs/User:schalkneethling2:concat
* https://developer.allizom.org/en-US/docs/User:schalkneethling2:reduce

For the CSS side, @wbamberg has suggested the following:

* box-shadow
* transform
* background-size
* background-color (not that high, but I like the idea of including a very simple one)

To add to this, I am thinking:

* An example that has a lot of options, like transform or filter for example
* One with a medium number of options
* One with just a few(3?) options

@stephaniehobson Thoughts?

**Comment by stephaniehobson** [comment]
I think you two are better situated to decide on these pages :) I can say "looks good to me!" now or you can wait 3 days for me to dig out from under this pile of vacation email, spend an hour looking at the options, spend an hour trying to think of stuff you didn't consider and then, most likely, just saying, "looks good to me!" ;)

**Comment by schalkneethling** [comment]
@wbamberg I can go ahead and set-up the pages, and I guess we just want to go ahead and create these on production? With that, I guess I will need some guidance on how to proceed.

We want to create a duplicate page of the existing live page
We want the URL to be similar but, have an element to it that is different to use as a hook for Traffic Cop.

You had them as https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/Array.prototype.push for example, perhaps something like https://developer.mozilla.org/en-US/docs/js/interactive/Array.prototype.push

**Comment by atopal** [comment]
I found the documentation :) https://docs.google.com/document/d/1CUe6-EqNbpSkLMLxfd0RWW6-TbPZFRtLc0rMh2Uu3G0/edit#heading=h.l8wq7aggy3so It's the "implementation" section.

**Comment by schalkneethling** [comment]
I have set-up the JS pages here:

https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/Array.prototype.reduce()
https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/Array.prototype.push()
https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/Array.prototype.reduce()

Because the latest KumaScript is not there, the editor does not load but, I believe there is going to be a push today/tomorrow so, then that will be sorted.

**Comment by schalkneethling** [comment]
@wbamberg How does 

* box-shadow
* transform
* background-color

sounds for the CSS pages?

**Comment by wbamberg** [comment]
Sounds perfect.

**Comment by schalkneethling** [comment]
And here are the CSS example pages:

* https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/background-color
* https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/transform
* https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/box-sizing

**Comment by schalkneethling** [comment]
@wbamberg Just to confirm, we said we wanted to remove these output examples from the page with the interactive editor correct?

<img width="1002" alt="screen shot 2017-08-17 at 19 48 01" src="https://user-images.githubusercontent.com/10350960/29426035-a13e296e-8385-11e7-9836-37c973ed6291.png">

<img width="1006" alt="screen shot 2017-08-17 at 19 50 40" src="https://user-images.githubusercontent.com/10350960/29426044-aa2adcca-8385-11e7-8a10-e2d03f953b7a.png">

**Comment by wbamberg** [comment]
Yes, I think we should.

> https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/box-sizing

box-sizing or box-shadow? The [last comment](https://github.com/mdn/interactive-examples/issues/211#issuecomment-323102350) was for box-shadow.

**Comment by schalkneethling** [comment]
Added `box-shadow` - https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor/box-shadow
