### ISSUE TITLE
Difficulty finding source code for interactive editor

### ISSUE THREAD

**Issue by curran** [mdn/interactive-examples#2157]
Greetings,

I'm intrigued by the MDN live editor and would like to study it to learn how it works.

I found this page here: https://interactive-examples.mdn.mozilla.net/pages/tabbed/iframe.html, and I'm looking to find the source code for the editor environment here (using CodeMirror, some tabs UI, and some way of dynamically executing edited code).

I understand this editor page is derived from [iframe.css](https://github.com/mdn/interactive-examples/blob/9f1562f6d449c93dc4aef03470c4f8502baaa2cc/live-examples/html-examples/embedded-content/css/iframe.css) and [iframe.html](https://github.com/mdn/interactive-examples/blob/9f1562f6d449c93dc4aef03470c4f8502baaa2cc/live-examples/html-examples/embedded-content/iframe.html) which reside in this repository, but where is the source code that defines the editor environment? Is that in this repository as well? I'm looking for the source files that build to [editor-tabbed.js](https://interactive-examples.mdn.mozilla.net/js/editor-tabbed.js?v=f41847f) and [editor-tabbed.css?v=f41847f](https://interactive-examples.mdn.mozilla.net/css/editor-tabbed.css?v=f41847f). I see there that is uses the `postMessage` API, and I'm interested to study how that might be used to dynamically inject CSS or JavaScript into an iframe.

Many thanks!

**Comment by caugner** [comment]
Hi @curran, the interactive examples are powered by https://github.com/mdn/bob, hope that helps! ✌️

**Comment by curran** [comment]
That's it! Many thanks 🙏
