### ISSUE TITLE
CSS examples: keystrokes are not recognized

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#218]
Just today, the CSS examples seem to be not responding to any keypresses (except tab). Perhaps this is related to https://github.com/mdn/interactive-examples/pull/217?

See also: https://discourse.mozilla.org/t/interactive-examples-testing-please/18107/3.

**Comment by schalkneethling** [comment]
Ok, I backed out all of those changes, and some additional one's. I am going to revisit it in a separate pull request. There are some weird inconsistency even between Chrome and Firefox so :-/
