### ISSUE TITLE
Add staging and localhost to list of allowed window origins for post message.

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#219]
To make it possible to test the kuma code can we add developer.allizom.org and localhost:8000 to the list of allowed origins for post messages? I think it would make sense to make this list a global constant.

**Comment by schalkneethling** [comment]
So, it looks like you can only specify either `*` (which is not a good idea) or a specific domain[1]. Therefore the best one can do here is to manually change the domain here[2] and here[3] if you are running these examples and Kuma side by side locally. Would that work?

[1] https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Syntax
[2] https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/analytics.js#L12
[3] https://github.com/mozilla/kuma/pull/4361/files#diff-94c143958fe4718bffbe73d2b02429a9R12

**Comment by schalkneethling** [comment]
Looks like this is not possible. It is pretty much a manual override one needs to do when testing :(
