### ISSUE TITLE
Server is not gzipping examples.

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#221]
@jgmize said he'd turn this on if I filed an issue.

**Comment by atopal** [comment]
Since one of the goals of the beta test is measuring page load time and this could affect that, I'd mark this is as a blocker

**Comment by jgmize** [comment]
Verified fix with the following:
```
$ curl -H "Accept-Encoding: gzip" -I https://interactive-examples.mdn.mozilla.net/pages/css/font.html
HTTP/1.1 200 OK
Content-Type: text/html
Connection: keep-alive
Date: Thu, 31 Aug 2017 22:13:32 GMT
Last-Modified: Wed, 30 Aug 2017 13:01:16 GMT
x-amz-version-id: s5kH3T09BqcLV5Hl_gpsTagVxgNbccoN
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 33ca1aa308d2c3dd926101c0bb80980a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 94Pq2lNrH0XLS5EBlGdBVATIiSwTawgr6OtU6bAqjdVfJBgGge6zWQ==
```

Note the `Content-Encoding: gzip` in the response.

**Comment by jgmize** [comment]
Thanks again for pinging me on IRC about this @schalkneethling; this had completely slipped off my radar.

**Comment by atopal** [comment]
Thanks a lot for the quick turnaround, Josh! Can you tell me whether this is on production already? I need to reset the counter for the A/B test based on when the editor started being served gzipped.

**Comment by jgmize** [comment]
@atopal yes, the curl command and output I pasted into https://github.com/mdn/interactive-examples/issues/221#issuecomment-326434813 was against the production domain. Also, feel free to ping me on IRC (or slack if you prefer) for a quicker response in the future.
