### ISSUE TITLE
CSS examples: code is no longer vertically centered

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#222]
In the latest revision of the CSS editor, the choices are aligned at the top of their boxes, rather than being centered. Is this intentional?

e.g. https://interactive-examples.mdn.mozilla.net/pages/css/box-shadow.html

**Comment by schalkneethling** [comment]
No, not with the CSS editors. I believe this is as a result of a change on the JS editor side, and they share some CSS. I am working on this editor today so, will take care of this as part of other small changes and improvements.

**Comment by schalkneethling** [comment]
Resolved
