### ISSUE TITLE
[media] Old MDN Logo in the Example for `<area>`

### ISSUE THREAD

**Issue by YDX-2147483647** [mdn/interactive-examples#2229]
- MDN page: [`<area>`: The Image Map Area element - HTML | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area) ([source in mdn/content repo](https://github.com/mdn/content/blob/510836b0fff9fd7fef01eba7a74962eb06106cf7/files/en-us/web/html/element/area/index.md?plain=1#L22))
- Embed interactive example: [pages/tabbed/area.html](https://interactive-examples.mdn.mozilla.net/pages/tabbed/area.html) ([source](https://github.com/mdn/interactive-examples/blob/9f1562f6d449c93dc4aef03470c4f8502baaa2cc/live-examples/html-examples/image-and-multimedia/area.html#L24))

![mdn-info.png](https://user-images.githubusercontent.com/73375426/180347963-be29285f-bc26-4896-aa03-5968cb78edd8.png)

The image here use a variant of the old MDN Logo. Should we [update](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) it, or leave it there as a memento?

**Comment by NiedziolkaMichal** [comment]
I don't see any point in changing it. @wbamberg what do you think?

**Comment by wbamberg** [comment]
I think we probably ought to change it. Organizations don't much like to see old logos out there (which in retrospect is a good reason for avoiding logos in examples in the first place) and we have had similar issues with people using old Firefox logos in mdn/content.

I don't think it is a high priority though.

**Comment by NiedziolkaMichal** [comment]
How about this? Blue "M" logo doesn't really fit.
![mdn-info](https://user-images.githubusercontent.com/100634371/193076370-e137fac0-6641-418a-8a5a-a338bdc1ded9.png)

**Comment by wbamberg** [comment]
I love that branding, but it's even older isn't it? IMO if we are going to change it we should change it to something completely different, so not subject to the whims of anyone's marketing department.

**Comment by NiedziolkaMichal** [comment]
It is older, but still in use [on the main page](https://developer.mozilla.org/en-US#nav-footer). Maybe lets just remove middle region?

**Comment by wbamberg** [comment]
> It is older, but still in use [on the main page](https://developer.mozilla.org/en-US#nav-footer).

That is...surprising. I thought Mozilla had replaced that branding a long time ago.

> Maybe lets just remove middle region?

I think that would look a bit weird. Maybe make each section a triangle extending to the centre? Then the text in each section should be offset from the edge more. And we could also replace "Graphics" with "HTTP".

**Comment by bsmth** [comment]
@NiedziolkaMichal I think what Will was suggesting is something like this:

![export](https://user-images.githubusercontent.com/43580235/205879586-2fb0fb24-061b-48d5-b62c-525f636edc34.png)

Maybe we can use this instead?
