### ISSUE TITLE
Update to BOB 2.2.1

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/interactive-examples#2235]
BOB version 2.2.1 was [released May 24](https://github.com/mdn/bob/pull/794), but interactive-examples repo still uses 2.2.0. I can see that [NPM](https://www.npmjs.com/package/mdn-bob) & [YARN](https://yarnpkg.com/package/mdn-bob) are also considering 2.2.0 as newest version, so probably it wasn't published correctly. @schalkneethling Could you please try to fix it? It would be great to have #[759](https://github.com/mdn/bob/pull/759) applied finally.

**Comment by nschonni** [comment]
2.2.0 is installed now https://github.com/mdn/interactive-examples/blob/0449b71c11ed96fd3144b426f4e1243f8ba90e5d/package.json#L43

**Comment by NiedziolkaMichal** [comment]
Yes, but ^ allows minor and patch updates to a given version, so 2.2.1 should be recognized.

**Comment by queengooborg** [comment]
`mdn-bob` 2.2.1 never actually got released on NPM, most likely due to the same reason that the recent attempt to release 3.0.0 failed.  Releases will be fixed in https://github.com/mdn/workflows/pull/116, under the new package name (see #2423 for more details).

**Comment by queengooborg** [comment]
Now that #2426 has been merged and v3.0.0 will be coming out soon, we should probably close this issue.
