### ISSUE TITLE
Multiple console.log statement not working as expected

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#224]
@maboa Mentioned this on Discourse:

I grabbed the latest version from github (https://github.com/mdn/interactive-examples) and was trying out the recently added multiple console.log support locally - a worthy addition I think, as it will give us more flexibility with examples.

I tried out the following code:

```
var fruits = ['Apple', 'Banana'];

console.log(fruits);

fruits.push('Orange');

console.log(fruits);
```

which when run, comes back with:

```
Apple,Banana,Orange
Apple,Banana,Orange
```

I was expecting output more like:

```
["Apple", "Banana"]
["Apple", "Banana", "Orange"]
```

So there’s a couple of things here:

It looks like multiple console logs can produce unexpected results.

(A question) When we output the contents of an array should the editor output show square brackets and quotes?

Hope this is helping and that I am posting in the right place.

**Comment by maboa** [comment]
Thanks @schalkneethling - I was just now getting around to filing properly. I'll put all issues here in future! :)

**Comment by maboa** [comment]
In case it wasn't clear, this appears to be related to the fact that we are logging the same thing twice:

For example:

```
var fruits = ['Apple', 'Banana'];

console.log(fruits+"");

fruits.push('Orange');

console.log(fruits);
```

results in the expected : 

```
Apple, Banana
Apple, Banana, Orange
```

**Comment by schalkneethling** [comment]
@maboa The output here https://github.com/mdn/interactive-examples/issues/224#issuecomment-323983635 actually is what I would expect. If I run this in a browser console, it essentially prints the same. Of course, it adds the [] and "" but other than that, it is the same. Thoughts?

I do not think we want to try and replicate what the browser console does, we simply want to show the output of each `console.log` @wbamberg @stephaniehobson agree?

**Comment by stephaniehobson** [comment]
+1 on not trying to write our own console. 

Do we need to add some kind of styling to indicate where one console.log stops and another starts? (not as a blocker for release but as a future improvement?) It would be useful with multi line statements, but I assume we are avoiding including those in our examples so it would only come up via user input.

**Comment by schalkneethling** [comment]
> Do we need to add some kind of styling to indicate where one console.log stops and another starts?

Yeah, we can definitely do that easily enough. My first thought is to use a `$` but, that might seem to shell like. Consoles generally do `>` so perhaps this will work?

**Comment by schalkneethling** [comment]
So, I am unsure as to the status of this one. The output from https://github.com/mdn/interactive-examples/issues/224#issue-251622852 and https://github.com/mdn/interactive-examples/issues/224#issuecomment-323983635 is what we would expect.

We have basically agreed to not try an emulate the browser console entire but, at least make it clear where output line starts.

It therefore seems that the only thing left to do here is to prepend a `>`, correct? @stephaniehobson @maboa @atopal @wbamberg

**Comment by schalkneethling** [comment]
> The output from #224 (comment) and #224 (comment) is what we would expect.

Nope, I take that back. There is an issue. Working on it.
