### ISSUE TITLE
JS examples: some examples overflow code editor

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#226]
With the JS editor, you get a maximum height that is enough to display 11 lines: https://interactive-examples.mdn.mozilla.net/pages/js/array-concat.html. Some of our examples are a bit bigger than this, and in these cases you get a scrollbar and the end of the example is not visible: https://interactive-examples.mdn.mozilla.net/pages/js/array-reduce.html.

It would be great if the editor were able to resize to fit its contents, but I'm not sure how difficult that would be.

**Comment by schalkneethling** [comment]
Yeah, I am also not sure how we would do this seeing that we are inside an iframe and if the editor section grows, the iframe needs to grow along with it. With that said, I can at the very least ensure that scrolling reveals all of the lines clearly without obscuring anything.

**Comment by wbamberg** [comment]
I do think it's a problem to have to scroll to see the "expected output", and in the current design that means you have a strict maximum of 11 lines per example. Even in the few we've done, it's clear that this will often not be enough.

If it's not possible to resize the thing automatically (and I can see how this would be difficult), should we reconsider the maximum, to say 16 lines, and increase the max-height and iframe height accordingly?

**Comment by schalkneethling** [comment]
> If it's not possible to resize the thing automatically (and I can see how this would be difficult), should we reconsider the maximum, to say 16 lines, and increase the max-height and iframe height accordingly?

I would be totally happy to do this. It makes the most sense, and is the easiest to implement. Also, it currently takes up less vertical space than the CSS editor so, it can definitely be larger. I will make that change.

**Comment by schalkneethling** [comment]
With the move back to CodeMirror, I believe this problem is resolved. I am therefore closing it but, should the problem still persist, or come up in another guise, feel free to reopen.
