### ISSUE TITLE
JS examples: strangeness when pressing <return> at the end of a line

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#227]
This seems tb be Firefox-only.

In the JS editor, if I put the cursor at the end of a line and press <return>, it moves the cursor to the next line, but doesn't seem to insert a new line: instead it looks like it inserts a space. Sorry this is hard to describe.

http://imgur.com/a/5sg2r

**Comment by atopal** [comment]
Weird, only at the end of a line, otherwise it works as expected.

**Comment by schalkneethling** [comment]
With the move back to CodeMirror, I believe this problem is resolved. I am therefore closing it but, should the problem still persist, or come up in another guise, feel free to reopen.
