### ISSUE TITLE
Broken links in CONTRIBUTING-HTML

### ISSUE THREAD

**Issue by bsmth** [mdn/interactive-examples#2301]
There are two broken resources:

* https://schalkneethling.github.io/mdn-fiori/patterns/scss/variables/
* https://screenshotscdn.firefoxusercontent.com/images/fff1dc63-ad6c-4a97-b20a-52b605e7994c.png (removed)

Found in https://github.com/mdn/interactive-examples/pull/2300

cc @schalkneethling

**Comment by NiedziolkaMichal** [comment]
[dn-fiori CSS formatting guidelines](https://mdn.github.io/mdn-fiori/patterns/css/formatting/) and [shadow-fonts.css](https://github.com/mdn/interactive-examples/blob/main/css/editor-libs/shadow-fonts.css) are also missing.
