### ISSUE TITLE
Wrap interactive example macro with a <div>

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#231]
Left to its own devices the WYSIWYG on kuma will wrap macros with a `<p>`. The new styles to give text a readable line length will restrict the widths of paragraphs. We need to make sure the interactive examples are not wrapped in `<p>`s. 

Wrapping them in a `<div>` seems to keep ckeditor from adding the `<p>`.

**Comment by schalkneethling** [comment]
Oh wait, so this is not a code change but, a change in the editor when we include the macro. Probably worth adding this to the README or some such documentation page.

**Comment by schalkneethling** [comment]
I updated the A/B test pages to be explicitly wrapped in a `<div>`
