### ISSUE TITLE
Content covered by "output" square in top-right corner of interactive examples

### ISSUE THREAD

**Issue by tannerdolby** [mdn/interactive-examples#2350]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

### What information was incorrect, unhelpful, or incomplete?

Legend text covered for the input type="checkbox" interactive example.

### What did you expect to see?

Expected to see the `<legend>`'s content without being partially covered by the "output" square fixed in the top right corner.

### Do you have anything more you want to share?

For larger viewports its more noticeable, but the`.output` class has 1rem padding which in its current state covers some of the legend:

<img width="672" alt="Screen Shot 2022-12-04 at 7 12 38 PM" src="https://user-images.githubusercontent.com/48612525/205542162-5fb710e5-d70f-400e-b401-cdb4cdd9bd6d.png">

Bumping up the top/bottom margin (or just the top) to 1.75rem makes the `<legend>` text fully visible without altering the original layout too much. I understand this is generated by the interactive example macro, so maybe this could just be a CSS change to that `.output` class. Thanks!

<img width="695" alt="Screen Shot 2022-12-04 at 7 13 06 PM" src="https://user-images.githubusercontent.com/48612525/205542159-50f50922-aaf9-471e-b3eb-61d598fe2624.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.md
* Last commit: https://github.com/mdn/content/commit/7594b50698a76ce79209b159835e615052915723
* Document last modified: 2022-10-31T06:32:10.000Z

</details>

**Comment by bsmth** [comment]
Hi @tannerdolby thanks for opening the issue. It looks like the example you're referring to is here: https://github.com/mdn/interactive-examples/tree/main/live-examples/html-examples/input so I've moved the issue into this repo :)

**Comment by NiedziolkaMichal** [comment]
We have already prepared a fix for this issue in PR [#820](https://github.com/mdn/bob/pull/820). It will be deployed soon. Thanks for submitting the issue.

**Comment by tannerdolby** [comment]
@bsmth @NiedziolkaMichal Thanks for the quick response :) Glad to see a fix has been implemented. I will go ahead and close this issue as your team has a fix coming in the next deploy.
