### ISSUE TITLE
CONTRIBUTING.md is outdated

### ISSUE THREAD

**Issue by MrBrain295** [mdn/interactive-examples#2360]
From a quick glance I can see a couple issues. One part references adding an example in HTML and it’s all markdown now, two is that it like to issues with the example needed label but the last one of those was made in 2018.

**Comment by bsmth** [comment]
Do you mean the section https://github.com/mdn/interactive-examples/blob/main/CONTRIBUTING.md#publishing, the code block needs to be markdown instead?

**Comment by NiedziolkaMichal** [comment]
I have removed markdown in CONTRIBUTING.md in PR #2363, but I don't understand what you mean about a label.

**Comment by MrBrain295** [comment]
In good first issues examples wanted.

**Comment by NiedziolkaMichal** [comment]
Alright, thanks for noticing. I have improved this part of the page.
