### ISSUE TITLE
[CI] We don't need to perform a prod deploy if meta docs are updated

### ISSUE THREAD

**Issue by bsmth** [mdn/interactive-examples#2364]
This is a minor efficiency issue where we're triggering deploys based on any commit to main. We should at least exclude some paths:

```bash
# exclude markdown in root as this gets updated frequently
./*.md

# alternatively, only watch the following?
./bin/**/*
./live-examples/**/*
./media/**/*
Jenkinsfile
yarn.lock
package.json
```

**Comment by NiedziolkaMichal** [comment]
That's a good idea. Changes to `LICENSE` and all files starting with `.` also shouldn't trigger deployment, so it's better to write an inclusion list.

**Comment by bsmth** [comment]
copying a note here from @schalkneethling:

```yaml
on:
  push:
    paths-ignore:
      - '**.md'
```

**Comment by NiedziolkaMichal** [comment]
Thanks, I have added PR.
