### ISSUE TITLE
chore: standardize repository settings

### ISSUE THREAD

**Issue by dipikabh** [mdn/interactive-examples#2379]
Following the guidelines defined in https://github.com/mdn/mdn/issues/168

#### General

- [x] A default or custom social share image (already exists)
- [x] Disable wiki & projects - as per repo save wiki if necessary ("Wikis" are enabled, "Discussions" and "Projects" are already disabled)
- [x] "Preserve this repository" (already selected)
- [x] "Allow merge commits" > "Default message" (turned this on)
- [x] "Allow squash merging" > "Default message"
- [x] "Allow rebase merging" (enabled this)
- [x] "Always suggest updating pull request branches" (already selected)
- [x] "Allow auto-merge" (turned this off)
- [x] "Automatically delete head branches"  (already selected)

#### Branches
- [x] Ensure default branch is `main` (already `main`)
Branch protection for the main branch:
- [x] "Require a pull request before merging" (already selected) > "Require approvals" (turned this on) > "Required number of approvals before merging: 1"
- [x] "Require status checks to pass before merging" (turned this on) > "Require branches to be up to date before merging" (turned this on)
- [x] "Require signed commits" (turned this on)

#### Environments, Releases, Packages
- [x] Disable environments, releases & packages if appropriate
- "Releases" is on, "Packages" is already off, "Environments" is on but disabling it (the last `github-pages` was deployed in Aug 2017)

#### Actions
- [x] Add `idle` and `welcome-bot` workflows: https://github.com/mdn/interactive-examples/pull/2380
- [x] Add CodeQL (already exists)

#### Add files to the repository
- [x] Prettier if appropriate (`.prettierrc` already exists)
- [x] Editor config if appropriate (`.editorconfig` already exists)
- [x] Add template docs
- CODE_OF_CONDUCT.md already exists
- CONTRIBUTING.md already exists, albeit it is different from the one in [project-template](https://github.com/mdn/project-template/blob/main/CONTRIBUTING.md). Noting here that this repo additionally contains:
  - CONTRIBUTING-CSS.md
  - CONTRIBUTING-HTML.md
  - CONTRIBUTING-JavaScript.md
- REVIEWING.md and SECURITY.md: https://github.com/mdn/interactive-examples/pull/2381

### Issue/PR/label/discussion triage

- [x] Common set of labels
- [x] Edit existing labels as per repository - TBD, the list of other labels is captured here: https://github.com/mdn/mdn/issues/286
- [x] Issue templates https://github.com/mdn/interactive-examples/pull/2384
- [x] Add PR template: https://github.com/mdn/interactive-examples/pull/2382
- [ ] Triage issues, pull requests & discussion (a rough triage rather than a detailed one - try and get things in right place)
- [ ] Move all 'suggestions' to the mdn/mdn repo and add label needs triage
- [x] Remove all discussions and shut down feature (apart from mdn-community & translated-content)
- [ ] Assign tier 2 repos

**Comment by NiedziolkaMichal** [comment]
Do we need both `welcome` and `github-actions` bot messages? Take a look at PR #2397 in which 2 messages are sent when PR is created and when it is merged.

**Comment by bsmth** [comment]
> Do we need both `welcome` and `github-actions` bot messages? Take a look at PR #2397 in which 2 messages are sent when PR is created and when it is merged.

This should be fixed now, we are only using the `github-actions` one in https://github.com/mdn/workflows/blob/main/docs/allo-allo.md
