### ISSUE TITLE
Low colour contrast for css function syntax when using Dark Theme

### ISSUE THREAD

**Issue by mokyox** [mdn/interactive-examples#2392]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

### What specific section or headline is this issue about?

Code snippets/syntax highlight

### What information was incorrect, unhelpful, or incomplete?

The colour contrast for CSS keywords e.g `clamp()`is low (1.47) and very hard to see on Dark Mode. 

### What did you expect to see?

Higher colour contrast for CSS keywords on Dark Mode

### Do you have anything more you want to share?

<img width="421" alt="Screenshot 2022-12-22 at 16 03 22" src="https://user-images.githubusercontent.com/23492964/209174750-af0a3440-81b9-418d-94ee-86baa6e83a63.png">

**Comment by bsmth** [comment]
Hi @mokyox , thanks for opening this one. This has been reported already in https://github.com/mdn/interactive-examples/issues/2054, so I will close this as a duplicate and you may track the progress or comment (+1) in the other issue if you like. Thank you :)
