### ISSUE TITLE
Issues with :root example

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#2393]
The example for `:root` has 2 spelling errors, and does not show the effect I would have expected (purple text): https://interactive-examples.mdn.mozilla.net/pages/tabbed/pseudo-class-root.html .

**Comment by NiedziolkaMichal** [comment]
Sorry! I was just testing it with the new BOB version, in which this example gives the expected result:
![image](https://user-images.githubusercontent.com/100634371/210079795-a7dc1edb-0dd3-4b21-bfd6-ef87bc604b41.png)
I think it's better to keep it and publish it only after the new BOB version is released.

I have created #2396 to fix spelling errors.
