### ISSUE TITLE
First Name name attribute wrong value assigned

### ISSUE THREAD

**Issue by PiyushAgrawal1243** [mdn/interactive-examples#2416]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

HTML Demo content first name name attribute wrong value assiged

### What information was incorrect, unhelpful, or incomplete?

First Name name attribute value "firstName" is wrong ,for fix this issue we need to assign "firstname" to name attribute   then it will work.

I have added 2 images first with name attribute with "firstname" that suggesting us a option  second image with name attribute  with "firstName" that didn't suggesting us a option.

Due to name attribute  value autocomplete attribute is able to identify the fields and auto complete the field value.

check  below images.
![Screenshot from 2023-01-25 12-34-39](https://user-images.githubusercontent.com/77185336/214500947-53429bbb-e3b4-467a-a5fc-031cdf9fc266.png)
![Screenshot from 2023-01-25 12-34-29](https://user-images.githubusercontent.com/77185336/214500953-f3a9c61f-efc7-4a56-9e4b-188c6436d789.png)

### What did you expect to see?

![Screenshot from 2023-01-25 12-34-39](https://user-images.githubusercontent.com/77185336/214501168-3e0afe7d-930a-4320-b465-e35cd7c05b18.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6
* Document last modified: 2023-01-18T07:45:13.000Z

</details>

**Comment by bsmth** [comment]
Moving this over as it looks like the example is here: https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/form-attributes/attribute-autocomplete.html

Although I'm not sure what the issue is. In the first screenshot you are changing `firstName` to `firstname` and I'm not sure this makes a difference, have I misread the issue?

**Comment by NiedziolkaMichal** [comment]
Both ways of writing `firstName` in `name` attribute are correct. Browsers are building auto-completion results, based on previous usages of `input` elements with the same case-sensitive name. There are many suggestions over the internet to use either of those forms and for me, auto-completion works on both of them.

**Comment by PiyushAgrawal1243** [comment]
> Both ways of writing `firstName` in `name` attribute are correct. Browsers are building auto-completion results, based on previous usages of `input` elements with the same case-sensitive name. There are many suggestions over the internet to use either of those forms and for me, auto-completion works on both of them.

If that so then why name="firstName" not working for me in example and name="firstname" working in example.

For reference you can check above images.

I tried both ways in my project but name="firstname" work for me.

**Comment by NiedziolkaMichal** [comment]
You can use the following guide, to find out the exact information held by the Chrome browser, used in autofill suggestions: [https://superuser.com/questions/884029/see-all-autofill-data](https://superuser.com/questions/884029/see-all-autofill-data).
Those values are present in my case:
![image](https://user-images.githubusercontent.com/100634371/215598736-d63dbca4-1f4d-4e45-83d1-55a23d450706.png)

As you can see, `first-name`, `first_name`, `firstname`, and `firstName` keys are used, and the value displayed to the user depends on the `name` attribute value.
In your case, the browser holds just `firstName` keys while it doesn't have anything for `firstname`, because other websites you have visited, use lowercase names.

I really don't know if we should use `firstName` or `firstname` in our example, as I couldn't find any official guidance about it. If someone knows more about this subject, I would be happy to find out.

**Comment by CBID2** [comment]
> You can use the following guide, to find out the exact information held by the Chrome browser, used in autofill suggestions: https://superuser.com/questions/884029/see-all-autofill-data. Those values are present in my case: ![image](https://user-images.githubusercontent.com/100634371/215598736-d63dbca4-1f4d-4e45-83d1-55a23d450706.png)
> 
> As you can see, `first-name`, `first_name`, `firstname`, and `firstName` keys are used, and the value displayed to the user depends on the `name` attribute value. In your case, the browser holds just `firstName` keys while it doesn't have anything for `firstname`, because other websites you have visited, use lowercase names.
> 
> I really don't know if we should use `firstName` or `firstname` in our example, as I couldn't find any official guidance about it. If someone knows more about this subject, I would be happy to find out.

Hey @NiedziolkaMichal! According to W3, [HTML attribute names may be written with any mix of lower- and uppercase letters that, when converted to all-lowercase, matches the attribute's name; attribute names are case-insensitive](https://www.w3.org/TR/2008/WD-html5-20080610/syntax.html#:~:text=In%20the%20HTML%20syntax%2C%20attribute,attribute%20names%20are%20case%2Dinsensitive.), so you’re onto something.

**Comment by estelle** [comment]
The example was missing the `id` attribute, which has since been fixed. 
it is missing the `<form>` and submit button, which the text advises may be needed. Not sure if that is the issue.

The relevant spec is: 

https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute

> the [autocomplete](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete) attribute, if specified, must have a value that is an ordered [set of space-separated tokens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#set-of-space-separated-tokens) consisting of either a single token that is an **[ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive)** match for the string "[off](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-off)", or a single token that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the string "[on](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-on)", or [autofill detail tokens](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens).

**Comment by CBID2** [comment]
> The example was missing the `id` attribute, which has since been fixed. 
> 
> it is missing the `<form>` and submit button, which the text advises may be needed. Not sure if that is the issue.
> 
> 
> 
> The relevant spec is: 
> 
> 
> 
> https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute
> 
> 
> 
> > the [autocomplete](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete) attribute, if specified, must have a value that is an ordered [set of space-separated tokens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#set-of-space-separated-tokens) consisting of either a single token that is an **[ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive)** match for the string "[off](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-off)", or a single token that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the string "[on](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-on)", or [autofill detail tokens](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens).

Maybe I can add those components to see if this solves the issue @estelle.

**Comment by estelle** [comment]
it works for me in Edge already. I am not sure if this is actually resolved or if there is still an issue.

**Comment by caugner** [comment]
As @estelle already pointed out, the example has been fixed (in https://github.com/mdn/interactive-examples/pull/2530).
