### ISSUE TITLE
bad words included

### ISSUE THREAD

**Issue by AmrAbdelgwaad** [mdn/interactive-examples#2438]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

### What information was incorrect, unhelpful, or incomplete?

attention guys these words (تیز سمی) means sama's ass I don't know if you add it intentionally but just to be aware

### What did you expect to see?

you can replace it with (سما(

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/bdi`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/bdi/index.md
* Last commit: https://github.com/mdn/content/commit/3c925962d641d83660a3c28d3e9a0627a7996183
* Document last modified: 2023-01-19T12:03:58.000Z

</details>

**Comment by hamishwillee** [comment]
According to google translate, this means "sharp poison" or "fast poison". 
I accept that translate is not perfect, but I also tried a more broad search and did not find any indication this means "Sama's ass".

@teoli2003 Do we have any experts who might confirm?

**Comment by AmrAbdelgwaad** [comment]
hey @hamishwillee  I am from Egypt my first language is Arabic and I can confirm that these words have the meaning that I wrote

**Comment by hamishwillee** [comment]
Thanks @AmrAbdelgwaad . Fixed by https://github.com/mdn/interactive-examples/pull/2443

**Comment by AmrAbdelgwaad** [comment]
> you are welcome @hamishwillee  mention me in any Arabic-related content I will be glad to help
