### ISSUE TITLE
:where() demo does not work properly due to editor shadow DOM injected classes

### ISSUE THREAD

**Issue by wolfbeast** [mdn/interactive-examples#2447]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:where

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

Live example does not work

### What did you expect to see?

A demonstration of :where() ;-)

### Do you have any supporting links, references, or citations?

https://repo.palemoon.org/MoonchildProductions/UXP/issues/2078#issuecomment-33984

### Do you have anything more you want to share?

The MDN demo for :where appears to not work because the editor unintentionally increases specificity in the fallback code for browsers that don't support shadow DOM.

The editor says that the following CSS is applied:
```
:where(ol, ul, menu:unsupported) :where(ol, ul) {
    color: green;
}
```
but in reality, the following CSS is applied:
```
.shadow-output:where(ol, ul.shadow-output, menu:unsupported) .shadow-output.shadow-output:where(ol, ul) {
    color: green;
}
```

Because the editor JS code inserts `.shadow-output`, the specificity of that rule is increased despite :where being 0. A copy of that editor demo with the exact same HTML and code, sans the shadow DOM cruft works just fine.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_where`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:where
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_where/index.md
* Last commit: https://github.com/mdn/content/commit/4e002d26cb032c915aeee366f922f23cbacd8bf1
* Document last modified: 2023-02-11T03:07:14.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
Could you please elaborate on what exactly is not working well in the example?
I have checked the same code on codepen(https://codepen.io/NiedziolkaMichal/pen/poOyLma) and on localhost without iframe, and the output looks exactly the same.

I have checked it on Chrome 110 and Firefox 110.

**Comment by wolfbeast** [comment]
Chrome 110 and Firefox 110 bot support shadow DOM so will not trigger the erroneous fallback code.

**Comment by NiedziolkaMichal** [comment]
Could you send back a picture displaying the `erroneous fallback code` that you are talking about, and also write the name and version of the browser that you encounter it?

**Comment by NiedziolkaMichal** [comment]
Today we have stopped using shadow DOM and now the output is displayed in the nested iframe. I think your issue should be resolved. Thanks

**Comment by wolfbeast** [comment]
Looks like that is a good solution. thanks.

**Comment by wolfbeast** [comment]
Pity scoped styles is no longer a thing in mainstream browsers because it was pushed out. This is a perfect use-case for that.
