### ISSUE TITLE
Add tool tip for copy

### ISSUE THREAD

**Issue by atopal** [mdn/interactive-examples#251]
During user testing it became clear that people want and like this feature. However in almost all cases we saw people being unsure whether it was really a copy button and whether it worked. People pasted into the url bar to test it. 

Please add a tool tip that says "copy to clipboard" and a label "copied" that appears below the button after clicking as long as you're hovering over the button or for 3 seconds, whatever is easier to implement.

**Comment by schalkneethling** [comment]
Yup, this is a bug. There is actually user feedback but, seems it is now being shown or, more likely, there is a `z-index` issue.
