### ISSUE TITLE
Interactive Example copy button not working as expected

### ISSUE THREAD

**Issue by Prithviraj2511** [mdn/interactive-examples#2517]
### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/CSS/border I opened this url in my browser.
I tried copying the interactive example code but it is not working.
![image](https://user-images.githubusercontent.com/58082365/235920731-3733e130-6994-4c1d-b1dd-c7f15504005a.png)
I checked by scrolling bit down where syntax was written. There click on copy icon the data is getting copied.
![image](https://user-images.githubusercontent.com/58082365/235921064-037c96c1-ae5a-4a9e-89c2-8e89f610079e.png)

### What did you expect to see?

I am expecting to see the data is getting copied after clicking on copy icon in interactive example block.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/border

### Do you have anything more you want to share?

1. open chrome browser 
2. enter this url - https://developer.mozilla.org/en-US/docs/Web/CSS/border
3. go to interactive example block. and try to copy code by clicking on copy icon.

**Comment by NiedziolkaMichal** [comment]
This issue has been already addressed in PR [#1170](https://github.com/mdn/bob/pull/1170) that awaits a review. Thanks for reporting it.
