### ISSUE TITLE
Add copy to clipboard for JS editor

### ISSUE THREAD

**Issue by atopal** [mdn/interactive-examples#252]
Since the JS editor doesn't offer a full editor environment and particularly because errors are not shown, people will copy paste the code into the console as seen in user testing. We should make that easier by offering the same functionality as in the CSS editor

**Comment by schalkneethling** [comment]
Opening this up for discussion, and as a place to record feedback from user testing and A/B testing before a final decision is reached. Tagging @wbamberg @stephaniehobson

**Comment by stephaniehobson** [comment]
Are people copy and pasting the entire block of code? Or just parts of it?

**Comment by wbamberg** [comment]
I don't think copy-to-clipboard is as useful for the JS as it is for the CSS examples. I don't think error reporting not working is in itself a good reason to support copy-to-clipboard - we should just fix error reporting.

**Comment by schalkneethling** [comment]
I agree, lets see what the data says at the end of the A/B test. For the `CSS`, is the data shows people are using it, it makes sense to keep it. For the JS, not sure it will be that useful, and we then need to add another(although tiny) dependency/lib into the mix.

**Comment by atopal** [comment]
yeah, error messages are the big one, let's not bother otherwise.
