### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by vetapalem** [mdn/interactive-examples#2526]
### What information was incorrect, unhelpful, or incomplete?

// Issue Python syntax
forget to close ')'

### Description
forget closed parenthesis 
The Python syntax error (https://developer.mozilla.org/en-US/docs/Web/WebDriver/Errors/InsecureCertificate).

### List of pages checked
-https://developer.mozilla.org/en-US/docs/Web/WebDriver/Errors/InsecureCertificate

### What did you expect to see?

from selenium import webdriver
from selenium.common import exceptions

session = webdriver.Firefox()
try:
    session.get("https://self-signed.badssl.com/")
except exceptions.InsecureCertificateException as e:
    print("Hit insecure cert on {}".format(session.current_url)) # this line

### Do you have any supporting links, references, or citations?

w3schools:
        https://www.w3schools.com/python/ref_string_format.asp

python:
https://docs.python.org/3/tutorial/inputoutput.html#the-string-format-method

### Do you have anything more you want to share?

![image](https://github.com/mdn/interactive-examples/assets/99022630/30d39680-1f44-4b10-9b04-8a3c0ce47db3)

**Comment by ai-naymul** [comment]
Hey @vetapalem I would love to work on this issue , May I?

**Comment by vetapalem** [comment]
welcome ai-naymul

**Comment by ai-naymul** [comment]
Acrually I am newbie contributor so could you give me more information regarding this problem?

**Comment by vetapalem** [comment]
i think this is a developer problem

**Comment by vetapalem** [comment]
I am just finding bugs only

**Comment by ai-naymul** [comment]
okay I think I got the bug location  Can I work on this problem?

**Comment by vetapalem** [comment]
ok, are you mdn employee..?

**Comment by ai-naymul** [comment]
> ok, are you mdn employee..?

No I am just an open source contributor and I have made a PR regarding the issue in the `content` repository

**Comment by vetapalem** [comment]
ok 
do it
