### ISSUE TITLE
Demo for <input type=url> does not demonstrate validation

### ISSUE THREAD

**Issue by dacook** [mdn/interactive-examples#2535]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

### What specific section or headline is this issue about?

Try it (HTML demo)

### What information was incorrect, unhelpful, or incomplete?

The demo doesn't demonstrate the browser validation for `required` or `pattern`, because it is not inside a `<form>` (at least, not in my Chrome).
I suggest it is wrapped in a simple `<form>` element, see below.

### What did you expect to see?

```
<form>
  <label for="url">Enter an https:// URL:</label>

  <input type="url" name="url" id="url"
       placeholder="https://example.com"
       pattern="https://.*" size="30"
       required>
</form>
```

![Screen Shot 2023-06-02 at 9 58 19 am](https://github.com/mdn/content/assets/4188088/7bb2b07e-4deb-4f82-a630-5f8480e60b32)
![Screen Shot 2023-06-02 at 9 58 23 am](https://github.com/mdn/content/assets/4188088/437d2968-ab1e-4c36-a1bb-72eb071a3ae0)

Note that this doesn't provide any feedback when the submit is successful, it simply clears the form. Perhaps we could add a little javascript to catch the submit and provide a success message instead.

### Do you have any supporting links, references, or citations?

As on the same page (emphasis added)  😉 

> The input value is automatically validated to ensure that it's either empty or a properly-formatted URL before the **form** can be submitted. 

### Do you have anything more you want to share?

I was unable to find a way to submit a PR for this, because these examples don't appear to be in the repository. I searched for the below path with GitHub's "Go to file" tool, but had no luck.

```
{{EmbedInteractiveExample("pages/tabbed/input-url.html", "tabbed-shorter")}}
```

There's nothing mentioned in the readme or contributing.md files, can details be added about this?

**Comment by Josh-Cena** [comment]
@dacook The file you want to edit is in https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/input/url.html. PRs are welcome.

**Comment by CBID2** [comment]
Hey @dacook! I started a pull request for this issue. It’s #2536 
I’d love to have your review of it! :)

**Comment by dacook** [comment]
Thanks Josh for the tip, and thank you @CBID2 for picking this up! I'd love to review it, but I'm not familiar enough with the environment to understand how this change works, and I don't know how to preview it to test it. I wonder if someone else can review it?

**Comment by CBID2** [comment]
> Thanks Josh for the tip, and thank you @CBID2 for picking this up! I'd love to review it, but I'm not familiar enough with the environment to understand how this change works, and I don't know how to preview it to test it. I wonder if someone else can review it?

Hi @dacook! :) I wrote an article on freeCodeCamp about how to review someone's PR. Here it is: https://www.freecodecamp.org/news/code-review-tips/
