### ISSUE TITLE
子应用嵌套子应用，不会加载嵌套子应用的字体图标

### ISSUE THREAD

**Issue by zk320520** [mdn/interactive-examples#2544]
### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/mdn/interactive-examples/assets/24220783/64498f89-59d5-4281-a066-754e0bed8986)
![image](https://github.com/mdn/interactive-examples/assets/24220783/2d509d63-d86e-4176-83b2-37f6de923324)

### What did you expect to see?

能够加载字体图标

**Comment by queengooborg** [comment]
This issue doesn't seem to have any relevance to this project, so closing.
