### ISSUE TITLE
Button HTML error

### ISSUE THREAD

**Issue by parveson** [mdn/interactive-examples#2556]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### What specific section or headline is this issue about?

First example on this page has an error

### What information was incorrect, unhelpful, or incomplete?

The button HTML as written does not work.   It should say class="styled".  Instead it says class="favorite styled".

### What did you expect to see?

The form should submit and show a result.  It does not. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/button/index.md
* Last commit: https://github.com/mdn/content/commit/e0d92259b485a219840367cf4e23a7069f192eec
* Document last modified: 2023-07-03T09:21:02.000Z

</details>

**Comment by Josh-Cena** [comment]
The button is purposefully not connected to a form because that's not the intention of this example. Buttons serve thousands of use cases and submitting a form is just one of them. The button here purely shows its "clickable" nature without any script logic.

The extra class seems harmless to remove, but it shouldn't break anything either.

**Comment by estelle** [comment]
The `class` attribute takes a space-separated list of class names as its value. While the "favorites" class has no associated CSS styles, the attribute as written is valid, though more verbose than needed.

Closing, as the class attribute value is not an issue.
if you are arguing that one of the three button examples on the page should actually have an action attached, please re-open with a comment or submit a new issue.
