### ISSUE TITLE
can't change ime after using eyedropper

### ISSUE THREAD

**Issue by rkawkxkdwlq** [mdn/interactive-examples#2564]
### What information was incorrect, unhelpful, or incomplete?

I'm trying to use the browser's built-in eyedropper, but after using the open method, the windows ime is not being set properly.
If I click outside of the browser to break the focus state of that window or another tap and come back in, it starts working normally.

This problem seems to occur only in Windows browsers.
It doesn't occur on Mac

i'm using Chrome browser and also Edge Browser.
IME is mode for Language.
cannot change keyboard language in browser

![image](https://github.com/mdn/content/assets/24672968/33ae6771-078f-45c2-9483-ba7929bbba5d)

example)
After using the eyedropper inside https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper, you can see that the IME settings are not working properly in the search input tag at the top.

https://github.com/mdn/content/assets/24672968/646a5a51-3939-4df3-b88c-a503bffa78b3

### What did you expect to see?

The keyboard's korean/english keys work normally after the eyedropper action

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

**Comment by bsmth** [comment]
Hi @rkawkxkdwlq - thanks for raising it. There's already an issue open for this here: https://github.com/mdn/content/issues/28067

I'm going to close this so we don't have multiple places tracking the same problem. Thank you :)
