### ISSUE TITLE
Remove hard coded URL

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#257]
Currently the URL to which `postMessage`s are sent, and the origin being checked when receiving a `postMessage` is hard coded in the JavaScript for the editors. This makes testing on various environments difficult or not possible.

We need to find a remedy for this.

**Comment by schalkneethling** [comment]
Is this still an issue with the changes that was made to Kuma and KumaScript?

* [ ] Yup
* [ ] Nope

@jwhitlock @stephaniehobson

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove hard coded URL](https://trello.com/c/4h42vY83/13-remove-hard-coded-url)

**Comment by jwhitlock** [comment]
"developer.mozilla.org" is still hard coded in the JavaScript.

**Comment by kenrick95** [comment]
Suggestion: If we can't eliminate the string "developer.mozilla.org" inside the codes, can we refactor it out at a config file. At testing environments, we could change this config to adapt to testing env URLs. What do you think?

**Comment by schalkneethling** [comment]
@kenrick95 That might be useful. Thing is, the problem is a bit more complex as it involves two external systems and the current build system. At the moment it is not posing enough of a problem that I would spend time on it right now.

Perhaps in future this problem will need to be solved, but for now I am going to lower the priority and leave it in the backlog. Thank you for your suggestion and interest. It is much appreciated.

**Comment by jwhitlock** [comment]
My suggestion is that the embedder sets the return URL as a query string parameter.

On the [MDN margin page](https://developer.mozilla.org/en-US/docs/Web/CSS/margin), the example is included by:

```
<iframe
   src="https://interactive-examples.mdn.mozilla.net/pages/css/margin.html"
   class="interactive  "
   width="100%"
   frameborder="0"
   height="250">
</iframe>
```

This updates to pass the embedding domain as a ``origin`` parameter:

```
<iframe
   src="https://interactive-examples.mdn.mozilla.net/pages/css/margin.html?origin=https://developer.mozilla.org"
   class="interactive  "
   width="100%"
   frameborder="0"
   height="250">
</iframe>
```

The JS introspects the location, parses the query string, and uses the ``origin`` value if provided, defaulting to ``https://developer.mozilla.org`` if not given.  This value is then used for communicating back to the parent.

The steps would be:

1. Extract uses of ``https://developer.mozilla.org`` to a "global" JS variable, add parsing of the query string in the location to override the value
2. Ship that version of interactive examples.
3. Update the KumaScript code to pass ``?origin=https://developer.mozilla.org`` in production, and the relevant URLs in other environments
4. Ship that version of KS
5. Regenerate MDN pages using the KumaScript macro ``EmbedInteractiveExample``
