### ISSUE TITLE
[meta] Should we archive the wiki?

### ISSUE THREAD

**Issue by bsmth** [mdn/interactive-examples#2575]
### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/interactive-examples/wiki

### What did you expect to see?

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing or https://github.com/mdn/interactive-examples/tree/main/contributing

**Comment by caugner** [comment]
Thank you, we decided to [disable the wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis) (which hides the content, but doesn't erase it), and it is now disabled. ✅
