### ISSUE TITLE
`::marker` class showing XML error

### ISSUE THREAD

**Issue by technoph1le** [mdn/interactive-examples#2587]
### What information was incorrect, unhelpful, or incomplete?

"Try it" playground in the the `:marker` pseudo class seems to be broken. 

![Screenshot of `:marker` pseudo class page](https://github.com/mdn/interactive-examples/assets/96492656/5ec8a6e3-e9e5-4093-930b-f638dbbced14)

### What did you expect to see?

Live interactive playground just like others

### Do you have any supporting links, references, or citations?

Web URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::markerSI
Issue credit: https://github.com/mdn/content/issues/28486

### Do you have anything more you want to share?

I inspected the files, and there seems to be no file for the `::marker` class, as well as no mention in the `meta.json` file. I would be happy to solve this issue if you assign it to me!

**Comment by bsmth** [comment]
Thanks a lot, this should be fixed by https://github.com/mdn/interactive-examples/pull/2585
