### ISSUE TITLE
Enhance console.log to differentiate between types

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#261]
Take this example:

```
var uint8 = new Uint8Array([10, 20, 30, 40, 50]);

console.log(uint8.toString());
console.log(uint8);
```

We currently get the following output:
```
10,20,30,40,50
10,20,30,40,50
```

It might be nice at some point to differentiate. 

Perhaps:
```
"10,20,30,40,50" // string
[10,20,30,40,50] // array
10.20304050 // number
```

**Comment by schalkneethling** [comment]
From @maboa ::

Leaving this here for whenever we return to this. Not a pressing issue for me, just wanted to note some findings.

Take a simple example:

```
// create an ArrayBuffer with a size in bytes
var buffer = new ArrayBuffer(8);
var uint16 = new Uint16Array(buffer);

console.log(uint16);
```

The Firefox developer console will return:

`Uint16Array [ 0, 0, 0, 0 ]`

while the Chrome developer console will return:

`Uint16Array(4) [0, 0, 0, 0]`

our interactive editor console returns:

`> 0,0,0,0`

**Comment by wbamberg** [comment]
I just opened https://github.com/mdn/interactive-examples/pull/280 for a first effort here.

**Comment by maboa** [comment]
This is great @wbamberg - thanks! It would be fantastic if we could take it to the next level and display Strings (quotes) and Arrays (square brackets) within arrays so that these examples would display similarly to the browser console.

```
var obj = {
  a: 1,
  b: 2,
  c: 3
};

console.log(Object.getOwnPropertyNames(obj));
// expected output: ["a", "b", "c"]
```

```
// array like object
var obj = { 0: 'a', 1: 'b', 2: 'c' };
console.log(Object.entries(obj)); 
// expected output: [ ['0', 'a'], ['1', 'b'], ['2', 'c'] ]
```

It might also be worth looking at how browser console.logs space out the output - ie spaces after commas and between nested brackets.

**Comment by maboa** [comment]
I took a look at `console.js` and wrote a bit of code that I'm currently not very proud of. It seems to be doing the trick though, will test and hopefully tidy up and submit a PR in case it is useful.

**Comment by maboa** [comment]
I opened [#291](https://github.com/mdn/interactive-examples/pull/291). Went with a recursive approach in the end.

**Comment by maboa** [comment]
Just to flag up that I am working on supporting : 
```
ArrayBuffer, DataView, SharedArrayBuffer,
Int8Array, Int16Array, Int32Array,
UInt8Array, Uint8ClampedArray, Float32Array, Float64Array
```
(also within Arrays).

It's in the testing phase. For now I'm using the Chrome/Safari output style, mostly because it is simpler :)
