### ISSUE TITLE
:nth-child - update example to be inclusive

### ISSUE THREAD

**Issue by estelle** [mdn/interactive-examples#2616]
### What information was incorrect, unhelpful, or incomplete?

The example is "NBA championships". This limits the example to men in the USA

### What did you expect to see?

A more inclusive example in terms of gender and geography.

How about tennis champions? That would enable the representation of multiple countries and both men and women. See https://www.espn.com/espn/feature/story/_/id/16371992/tennis-top-20-all (but that is from 2016, so Serena may have moved up to the top)

### URL

(https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)

**Comment by hamirmahal** [comment]
I used https://www.topendsports.com/world/lists/greatest-all-time/athletics.htm as a reference.

**Comment by hamirmahal** [comment]
I picked athletes from https://www.topendsports.com/world/lists/greatest-all-time/athletics.htm.

It listed 18 male track and field athletes, I think, and 9 female track and field athletes.

I picked 9 male athletes from the list, and all 9 female athletes, for a total of 18 `<li>`s.

**Comment by estelle** [comment]
Thank you @hamirmahal!

**Comment by hamirmahal** [comment]
You're welcome @estelle! Thank you for opening the issue,

**Comment by hamirmahal** [comment]
You're welcome @estelle!

**Comment by hamirmahal** [comment]
Thank you for opening the issue,

**Comment by hamirmahal** [comment]
Thank you for opening the issue.
