### ISSUE TITLE
Console logging TypedArrays

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#262]
Leaving this here for whenever we return to this. Not a pressing issue for me, just wanted to note some findings.

Take a simple example:

```
// create an ArrayBuffer with a size in bytes
var buffer = new ArrayBuffer(8);
var uint16 = new Uint16Array(buffer);

console.log(uint16);
```

The Firefox developer console will return:

`Uint16Array [ 0, 0, 0, 0 ]`

while the Chrome developer console will return:

`Uint16Array(4) [0, 0, 0, 0]`

our interactive editor console returns:

`> 0,0,0,0`

**Comment by schalkneethling** [comment]
Thanks for logging the issue @maboa - I am going to copy this one over to https://github.com/mdn/interactive-examples/issues/261 as they are closely related.
