### ISSUE TITLE
`Array.prototype.reduce()` demo requires horizontal scrolling

### ISSUE THREAD

**Issue by hamirmahal** [mdn/interactive-examples#2632]
### What information was incorrect, unhelpful, or incomplete?

I think it would be more user-friendly if readers didn't have to horizontally scroll to see the `reduce()` example.

### What did you expect to see?

The entire `reduce()` example is visible without any scrolling.

**Comment by hamirmahal** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#try_it

**Comment by hamirmahal** [comment]
![1680x1050](https://github.com/mdn/interactive-examples/assets/43425812/a10ecc0f-0c13-4adc-bf68-0f60a006afdf)

**Comment by hamirmahal** [comment]
The issue also occurs on a 1920 x 1080p display.

**Comment by hamirmahal** [comment]
![image](https://github.com/mdn/interactive-examples/assets/43425812/c98f7b0d-5499-4ff8-a4be-4c2fd1dfc6b8)

**Comment by bsmth** [comment]
Fixed in https://github.com/mdn/interactive-examples/pull/2648 ! Thank you for reporting and opening a PR for it!

**Comment by hamirmahal** [comment]
You're welcome! Thanks for the fix.

**Comment by hamirmahal** [comment]
![image](https://github.com/mdn/interactive-examples/assets/43425812/99eb431b-e2fb-43c7-b679-f4ba0e14892c)
