### ISSUE TITLE
ES6 Mode?

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#265]
At the moment I'm writing examples in ES5, which means I convert things like:

```
var p1 = Promise.resolve(3);
var p2 = 42;
var p3 = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, 'foo');
}); 

Promise.all([p1, p2, p3]).then(values => { 
  console.log(values);
});
```

to

```
var p1 = Promise.resolve(3);
var p2 = 42;
var p3 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 100, 'foo');
});

Promise.all([p1, p2, p3]).then(function(values) {
  console.log(values);
});
```

Even though ES6 browser support came before promises (I think!) So it feels a little odd to use them with the older syntax.

At some point in the future it might be nice to have an ES6 tab on the editor so that we can provide examples in newer formats. Automatic conversion from one format to the other would be great! I guess Babel or Lebab (https://lebab.io/) could help :)

**Comment by maboa** [comment]
A quick play with Lebab shows that this might work!

![screen shot 2017-09-04 at 15 20 07](https://user-images.githubusercontent.com/208756/30028263-9fa08ba8-9184-11e7-9e88-01af00a6ac3e.png)

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ES6 Mode?](https://trello.com/c/KjNkp1uG/7-es6-mode)

**Comment by schalkneethling** [comment]
This is an interesting one from way back in the day. Any thoughts on this @chrisdavidmills?

**Comment by chrisdavidmills** [comment]
@schalkneethling Yup, I'd absolutely love to see this implemented. This has come up a few times.

**Comment by Josh-Cena** [comment]
We no longer use pre-ES6 syntax.
