### ISSUE TITLE
Live example on the groups and backreferences page has inconsistent name

### ISSUE THREAD

**Issue by haocheng6** [mdn/interactive-examples#2664]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences

### What specific section or headline is this issue about?

"Try it" section

### What information was incorrect, unhelpful, or incomplete?

The title of the article is "Groups and backreferences", but the name of the live example is "RegExp Groups and ranges".

Also, it would be better if the example can show the usage of backreferences.

### What did you expect to see?

- The name of the live example is something like "RegExp Groups and backreferences".
- Rewrite the example to show how to use backreferences.

**Comment by pepelsbey** [comment]
Hey! Nice catch :) You’re right, the first example of the “groups and backreferences” article would benefit from both groups and backreferences examples. There is one already at the bottom, but I think it’s worth having one at the very top.

Feel free to send a PR if you have one in mind. Thanks!

**Comment by Himanshuch8055** [comment]
Hey! @haocheng6 @pepelsbey 👍 
I have an example of "groups and backreferences" and I tried to work on it.
