### ISSUE TITLE
increase siteSpeedSampleRate to 100%

### ISSUE THREAD

**Issue by atopal** [mdn/interactive-examples#269]
Google Analytics samples about 1% of users for page load time by default, which is okay for when you look at page load across the site, but not great when you look at just 3 pages (we have less than 20 page load samples that satisfy all the criteria). This is exacerbated by the fact that you can’t limit the sampled data to just the 90% percentile, so with a low amount of samples and just the arithmetic mean, a few outliers will give you mostly useless data. Looking at just the average page load time for the segment that gets the old pages, it’s 11 seconds, compared to a site average of 4s, a 7 second discrepancy when it should be 0.

Luckily there is a distribution view in GA, where you can see page load time bucketed, but unfortunately it buckets users in arbitrary timing buckets, which makes it impossible to calculate actual percentiles, but even those buckets can’t be exported, using the API you only get the total cumulative page load times for a page and the number of samples, which only gives you the arithmetic mean again.

My suggestion is the following: We increase the [siteSpeedSampleRate](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate) rate to 100%, and look at the buckets in the distribution view, and I’ll manually report on the buckets in rough percentiles. We should probably add the rate as a constance config, so we can change it as needed.

I talked to Gareth about this and he doesn't see an issue with an increase in our hits to Google Analytics.

**Comment by jwhitlock** [comment]
This will require a change in Kuma, so @atopal opened [bug 1397858](https://bugzilla.mozilla.org/show_bug.cgi?id=1397858).

**Comment by schalkneethling** [comment]
PR: https://github.com/mozilla/kuma/pull/4419
