### ISSUE TITLE
Split up site.json

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#273]
The `site.json` file will end up getting huge. At some point, we might want to think about splitting it up.

**Comment by schalkneethling** [comment]
Agreed.

I reckon we have a couple of options here that needs some exploration.

It would be a big win if it could be simplified to the point where there are literally the two JS and CSS folders. The page builder would then recursively load all the files in those directories and write the final pages based on the content of the file, the filename, and directory structure.

There are some edge cases where some of these have an additional CSS and/or JS file that makes the above a bit more challenging but, not impossible.

Another approach would be to simply slit the `.json` up into smaller modules. Much in the same way you split up the work for Mark. The page builder then needs to be updated to look for all `.json` files in the root(or other specific directory) and then iterate over these in turn.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split up site.json](https://trello.com/c/a1LAYlNY/9-split-up-sitejson)
