### ISSUE TITLE
bug 1396359: console.log only outputs the first argument

### ISSUE THREAD

**Issue by jwhitlock** [mdn/interactive-examples#277]
Filed at [bug 1396359](https://bugzilla.mozilla.org/show_bug.cgi?id=1396359):

``console.log('what about','that')`` prints ``what about``, but not ``that``.

**Comment by schalkneethling** [comment]
Hmmmm, yeah. This is clearly because we do not implement the `console` API 1:1 but, I am going to add this to the infrastructure project as it is definitely worth exploring. Should not be a hard one to implement. Thanks @jwhitlock
