### ISSUE TITLE
Primary application A is nested with subapplication B, and subapplication B is nested with subapplication C. The font icon of subapplication C cannot be displayed

### ISSUE THREAD

**Issue by zhuangyinyin** [mdn/interactive-examples#2774]
Primary application A is nested with subapplication B, and subapplication B is nested with subapplication C. The font icon of subapplication C cannot be displayed

**Comment by caugner** [comment]
Hi @zhuangyinyin,

it doesn't look like you meant to create an issue in the interactive examples repo, so I'm closing this as won't fix.

If this was wrong, please provide us with some more details, like which interactive example you're seeing an issue with. 🙏
