### ISSUE TITLE
Bad practise in examples (prefixed property last)

### ISSUE THREAD

**Issue by 1jj** [mdn/interactive-examples#2797]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

An example of bad practice: 
```
box-decoration-break: slice;
-webkit-box-decoration-break: slice;
```
Prefixed property last

### What did you expect to see?

```
-webkit-box-decoration-break: slice;
box-decoration-break: slice;
```
Prefixed property first

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/box-decoration-break`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/box-decoration-break/index.md
* Last commit: https://github.com/mdn/content/commit/2adfb8760ac42c80966080e2e84211b14e43b589
* Document last modified: 2023-07-18T00:15:42.000Z

</details>

**Comment by Josh-Cena** [comment]
What's the difference?

**Comment by 1jj** [comment]
> What's the difference?

There could be a difference in future (depending on implementation details)[1], but thats not the point. It's just an undisputed priciple.
https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix#css_prefixes
https://css-tricks.com/ordering-css3-properties/
https://bitsofco.de/css-vendor-prefixes/#how-do-we-use-them
https://stackoverflow.com/questions/7080605/ordering-of-vendor-specific-css-declarations
https://webhint.io/docs/user-guide/hints/hint-css-prefix-order/#what-does-the-hint-check

[1] if they keep their prefixed-property non-standardish and fix it only for the unprefixed version. We have seen this before.
https://groups.google.com/a/chromium.org/g/blink-dev/c/PyIR0yUMYsM

(I see ... you seem to be a fairly young person, means  less experience with CSS Prefix Hell :-)

**Comment by Josh-Cena** [comment]
I see. Not only am I inexperienced with Prefix Hell, I'm also generally inexperienced with CSS ;)
