### ISSUE TITLE
codemirror not being gzipped

### ISSUE THREAD

**Issue by atopal** [mdn/interactive-examples#281]
According to Webpagetest we have assets that are not gzipped, maybe something slipped through the cracks? 

https://www.webpagetest.org/performance_optimization.php?test=170915_99_96e2d8b5d7d2c805708e82f07226845c&run=1#compress_text

**Comment by jgmize** [comment]
I ran the same curl command from my original verification in https://github.com/mdn/interactive-examples/issues/221#issuecomment-326434813 and re-verified that it had the `Content-Encoding: gzip`, and then I checked the 2 webpagetest.org urls, with the following results:

```
$ curl -H "Accept-Encoding: gzip" -I https://interactive-examples.mdn.mozilla.net/js/codemirror.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Content-Length: 179295
Connection: keep-alive
Date: Mon, 28 Aug 2017 19:25:43 GMT
Last-Modified: Mon, 28 Aug 2017 14:01:27 GMT
x-amz-version-id: RW7j4mLLZ3IR.7y1ZKq4X39qQ_N3O2K0
ETag: "27bd3ccb0bd4686c2bece6e429ffd55b"
Server: AmazonS3
X-Cache: RefreshHit from cloudfront
Via: 1.1 28fd9501206a11a06951e60ad8a996fd.cloudfront.net (CloudFront)
X-Amz-Cf-Id: CEyzl8FrDUlf9xXwXwNde0k03wmy9z0lD38DNOzWiFlztqQBwxpVIg==

$ curl -H "Accept-Encoding: gzip" -I https://interactive-examples.mdn.mozilla.net/css/editor-js.css
HTTP/1.1 200 OK
Content-Type: text/css
Connection: keep-alive
Date: Thu, 14 Sep 2017 11:34:09 GMT
Last-Modified: Tue, 12 Sep 2017 10:01:16 GMT
x-amz-version-id: qpB_dnG45MyaCGUqDi6gfgn5VdeiT174
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: RefreshHit from cloudfront
Via: 1.1 cab3e542f2f523a804e99e74cb91af31.cloudfront.net (CloudFront)
X-Amz-Cf-Id: hLmGkqjMqySZzDxKk9jEOID8URBAgy7CAb6lBzMMxtVkABWFLIcXIw==
```

As you can see, the `Content-Encoding: gzip` header is present for the second request, but not the first, despite the presence of the `Accept-Encoding: gzip` header in the request and `application/javascript` being in [list of mimetypes that cloudfront will automatically compress](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-file-types).

**Comment by jgmize** [comment]
Re-opened; my intent was to comment on what I had found so far, not to close the issue. I will open a support issue with amazon.

**Comment by atopal** [comment]
Thanks Josh!

**Comment by jgmize** [comment]
Per the response from amazon support (below) I ran a wildcard invalidation and now everything I have checked is gzipped.

> CloudFront compresses files in each edge location when it gets the files from your origin. When you configure CloudFront to compress your content, it doesn't compress files that are already in edge locations. In addition, when a file expires in an edge location and CloudFront forwards another request for the file to your origin, CloudFront doesn't compress the file if your origin returns an HTTP status code 304 (RefreshHit in response header), which means that the edge location already has the latest version of the file. If you want CloudFront to compress the files that are already in edge locations, you'll need to invalidate those files

**Comment by jgmize** [comment]
Followed up with a new webpagetest against the same URL to verify: https://www.webpagetest.org/result/170918_C3_1f79bed1a464b8f5a7d8596950c32ccb/
