### ISSUE TITLE
input.hidden = "true"   in the example JS prevents it working

### ISSUE THREAD

**Issue by John-Page** [mdn/interactive-examples#2817]
### What information was incorrect, unhelpful, or incomplete?

The last line of the JS :  input.hidden="true"  prevents the demo from working

### What did you expect to see?

Delete the line?

**Comment by Josh-Cena** [comment]
Which example are you referring to?

**Comment by John-Page** [comment]
Sorry, I thought your reporting system picked that up automagically.
It's the example on
https://developer.mozilla.org/en-US/docs/Web/API/Selection/direction
Looks like some debug code got left in.
John P

PS Your reference is a godsend.   It's really very useful.   Thank you for
the work you put into it!

**Comment by Josh-Cena** [comment]
Thanks for the issue. (1) this is not an interactive example so it should not be here. I know our repos are confusing so it's totally fine, but interactive examples are like the one at the top of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#try_it. (2) this is working as intended. It starts by checking `"direction" in Selection.prototype`. If this feature isn't available, this example has no point so it simply prevents any interactions. This feature is only supported in non-Chrome browsers as indicated in the compat table.
