### ISSUE TITLE
Playground Output Result Not Showing

### ISSUE THREAD

**Issue by ghost** [mdn/interactive-examples#2866]
### What information was incorrect, unhelpful, or incomplete?

Whenever I opened up [this link in Task 3]( https://developer.mozilla.org/en-US/play), the output screen shows nothing. No matter how much I refresh the page or clear my cache. I am opening this link from the page [this](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks)

![image](https://github.com/user-attachments/assets/6d07ee8e-5794-488b-a73b-8b428fb55c50)

### What did you expect to see?

Just like the source page [this link](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks) from where I opened my link, the output should be shown clearly, but it is not.

### Do you have any supporting links, references, or citations?

[This is the main page](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks)

**Comment by bsmth** [comment]
Thanks for reporting. This should be fixed now, so I'm going to close this. Could you check again and feel free to reply here if you still have issues. Thanks a lot :)

**Comment by ghost** [comment]
Thank you, it works perfectly now. Not sure if I should ask it here, but is there any way you can add a feature to change the size of the output screen?
