### ISSUE TITLE
console.logging Symbols produces an error

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#292]
For example

```
console.log(Symbol('a'));
```

produces: 

```
Error: Cannot convert a Symbol value to a string
```

and should produce:

```
Symbol(a)
```

Note that trying this out in the browser console **while on the interactive example pages** has the same effect:

```
console.log(Symbol('a'));
editor-js.js:1 Uncaught TypeError: Cannot convert a Symbol value to a string
    at n (editor-js.js:1)
    at console.log (editor-js.js:1)
    at <anonymous>:1:9
```

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [console.logging Symbols produces an error](https://trello.com/c/oXW2OWT2/4-consolelogging-symbols-produces-an-error)

**Comment by maboa** [comment]
This should also be resolved by `console.log` changes that I'm working on.

**Comment by schalkneethling** [comment]
Resolved > Fixed
