### ISSUE TITLE
Console.logging Object.getPrototypeOf can cause unexpected results

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#293]
For example:

```
console.log(Object.getPrototypeOf('foo'));
```

Outputs `String` from browser Consoles, but doesn't output anything in the Interactive Editor.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Console.logging Object.getPrototypeOf can cause unexpected results](https://trello.com/c/7AbJJvna/3-consolelogging-objectgetprototypeof-can-cause-unexpected-results)
