### ISSUE TITLE
Make analytics easier to find in GA

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/interactive-examples#295]
When tracking events most of MDN uses this appraoch:

```
category: 'Thing this is about',
action: 'What about this thing?',
label: 'Value we are interested in.',
```

For example:

```
category: 'youTube',
action: 'play',
label: 'url of video played',
```

I suggest we update the performance event tracking to:

```
category: 'Interactive Example - ' + type,
action: 'Performance'
label: 'Load time in ms: ' + duration,
```

**Comment by schalkneethling** [comment]
> category: 'Interactive Example - ' + type,

@stephaniehobson Should I go ahead and update all of the GA pings to use the above style category?

**Comment by stephaniehobson** [comment]
Yes please.
