### ISSUE TITLE
MDN integration of new examples

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#32]
I tried embedding some of them in MDN pages, and noticed a few things.

For example, compare:
https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/filter_old
https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/filter_new

* the examples don't get any border at the top
* the old version is more compact
* the help text "Try editing the selected examples, or select a different example below:"
 should have a style that matches the page.

I tried embedding some of the new ones, for example: https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/animation_new

* when I load the page initially, the cursor ends up in a weird place, right under the "Try editing the selected examples, or select a different example below:" line.
* you can see (I hope you agree :) that the big comment about slidein is quite distracting
* the lines are too long for the content column, so we get horizontal scrollbars

**Comment by schalkneethling** [comment]
the lines are too long for the content column, so we get horizontal scrollbars

This is something I wanted to talk about.

1. Should we optimise for say 80 chars per line? Less? Again something we need to decide and then document as a standard across the examples.
2. Is there a limit to the number of examples per feature. This is purely for the CSS examples. For example `filter` and `transform` have a ton of examples where others have maybe 2-3. We will probably not have a minimum but, perhaps we should define and document a maximum?

**Comment by wbamberg** [comment]
>  Should we optimise for say 80 chars per line? Less?
> Again something we need to decide and then document as a standard across the examples.

We should aim for less I think. The MDN content column can be quite narrow, and it would be great to avoid horizontal scrollbars if possible. I wonder, though, if the MDN redesign will give us more width here. 

> We will probably not have a minimum but, perhaps we should define and document a maximum?

Yes, I agree. I feel like [filter](https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/filter:v2) is OK with 12, but [transform](https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/transform:v2) has definitely too many at 21.

**Comment by schalkneethling** [comment]
Marking this as a dupe of https://github.com/mdn/interactive-examples/issues/68
