### ISSUE TITLE
CSS examples top/bottom switch doesn't seem to be reliable

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#348]
With the CSS examples, the idea is that they are displayed side by side, but then flip into top/bottom if the width falls below a certain threshold.

What I'm often seeing is that the iframe's dimensions are adjusting, but the example output isn't moving underneath the code, so you still get side-by-side, but have a grey space underneath:

![screen shot 2017-11-21 at 9 04 59 pm](https://user-images.githubusercontent.com/432915/33110909-f2498f9a-ceff-11e7-8066-c39f3b86e4b6.png)

Given the amount of trouble this responsive behavior has caused us, I'm inclined to suggest that we should scrap it, and instead say: if width gets too narrow to show the output, then just hide the output, and make the examples non-interactive (so they are not editable or selectable).

An advantage of this is that we could then potentially define different heights for the iframe, to accommodate properties that want to show more than 6 example choices.

Thoughts @schalkneethling , @atopal ?

**Comment by schalkneethling** [comment]
@wbamberg Thanks for reporting. Let me have a look at this, it might be a `postMessage` problem that is the root cause, as this used to work fine.

**Comment by schalkneethling** [comment]
@wbamberg I tried all three the examples here[1] and cannot reproduce. Tested in both Firefox and Chrome. What is the URL of a page you are seeing that behavior on?

[1] https://developer.mozilla.org/en-US/docs/Experiment:InteractiveEditor

**Comment by wbamberg** [comment]
Oh! I can reproduce it on this page: https://developer.mozilla.org/en-US/docs/User:wbamberg/interactive-css-test and only for examples after the first one. So perhaps it doesn't work when there's more than one editor on a page?

**Comment by stephaniehobson** [comment]
The editor code can't currently support more than one editor per page.

**Comment by wbamberg** [comment]
Thanks for the clarification, let's close this then.
