### ISSUE TITLE
CSS editor doesn't spot errors among multiple declarations

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#354]
If the CSS in an example is something like:

```
position: relative;
top: 65px;
left: 65px;
```

...then the user edits it and makes a mistake, the editor will only flag the edit as incorrect if *all* the declarations are incorrect. For example, it won't flag:

```
position: relative;
top: bananas;
left: handed;
```

I think this might be tricky to support though :(.

**Comment by wbamberg** [comment]
Note that validating the CSS, a la https://github.com/mdn/interactive-examples/issues/455 would fix this too :).

**Comment by NiedziolkaMichal** [comment]
This is now fixed. The presented example is displayed like that:
![image](https://user-images.githubusercontent.com/100634371/221273383-2d14bb27-ac9e-47fc-8f80-4fbffe88bb2c.png)
