### ISSUE TITLE
Reflect.deleteProperty produces unexpected error

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#356]
I'm seeing different errors in the interactive editor in Chrome and Firefox. Pretty sure this used to work.

```
var arr = [1, 2, 3, 4, 5];
Reflect.deleteProperty(arr, '3'); // true
console.log(arr); // [1, 2, 3, , 5]
```

On Chrome we get : `Error: Cannot read property 'constructor' of undefined`

and on Firefox we get : `Error: t is undefined`

This appears to produce the expected behaviour in browser consoles.

**Comment by maboa** [comment]
We also see what appears to be the same issue, with the following example:

```
const object1 = {
  property1: 42
};

const proto1 = Reflect.getPrototypeOf(object1);

console.log(proto1);
// expected output: [object Object]

console.log(Reflect.getPrototypeOf(proto1));
// expected output: null
```

**Comment by maboa** [comment]
Confirmed that this error was not present in earlier versions of the editor. Digging in ...

**Comment by schalkneethling** [comment]
Tested the live examples in Firefox and Chrome and they produce the expected output now. Closing.
