### ISSUE TITLE
Proposed changes to our contribution docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#363]
I'd like us to consider some changes to the meta-docs for contributing examples.

At the moment we have:

* https://github.com/mdn/interactive-examples/blob/master/README.md, that includes stuff on the mechanics of contributing (i.e. prerequisites, which files you need to add, how to use npm start, &c)

* https://github.com/mdn/interactive-examples/blob/master/JS-Example-Guide.md, which covers normative aspects of contributing a good JS example

* A new PR to add a similar thing for CSS examples, that I've called a style guide: https://github.com/mdn/interactive-examples/pull/362

I'd like to suggest:

* we rename "JS-Example-Guide.md" to "JS-Example-Style-Guide.md" to reflect the fact that it only covers the normative stuff.

* we create CONTRIBUTING.md and move into it the stuff from README about how to contribute. This can also link to the JS and CSS style guides. CONTRIBUTING.md is a pretty standard place to keep stuff like this.

What do you think @schalkneethling ?

**Comment by schalkneethling** [comment]
I wholeheartedly support this. Thanks @wbamberg
