### ISSUE TITLE
JS Examples: Need examples for Date.prototype.getUTCMonth()

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#389]
Currently we do not have an example for the `Date.prototype.getUTCMonth()` function. This is not marked as experimental or deprecated so, we probably should have one.

**Comment by wbamberg** [comment]
We have this https://interactive-examples.mdn.mozilla.net/pages/js/date-getutcmonth.html, isn't that it?

**Comment by schalkneethling** [comment]
You are correct. Updated the relevant page.
