### ISSUE TITLE
JS Examples: Need examples for Date.prototype.toSource()

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#395]
Currently we do not have an example for the `Date.prototype.toSource()` function. This is not marked as experimental or deprecated so, we probably should have one.

**Comment by kenrick95** [comment]
At MDN, this feature is marked as non-standard though. ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toSource)) Shall we still add example for this? Thanks

**Comment by schalkneethling** [comment]
@kenrick95 Good point no, let's skip this one.
