### ISSUE TITLE
Typo in title for JavaScript Demo: Date.UTC())

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#398]
Typo in title for JavaScript Demo: Date.UTC())
https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/date-utc.html

**Comment by 7ayushgupta** [comment]
If I am correctly interpreting, the only change needs to be in the file name. `date-utc` needs to be changed to `Date.UTC()`. I can also submit a pull request fixing all the titles, mentioned as bug. Should I proceed?

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/interactive-examples/pull/401
