### ISSUE TITLE
JS Examples: Need examples for Date.prototype[@@toPrimitive]?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#400]
Noticed that we do not have an example for Date.prototype[@@toPrimitive]. There are some others as well as noted in other issues. On this one, I am wondering whether it was left out intentionally? @wbamberg

**Comment by schalkneethling** [comment]
@wbamberg Thoughts on this one?

**Comment by elharony** [comment]
Do you still need an example for it, @schalkneethling ?

**Comment by schalkneethling** [comment]
Hey @elharony - Indeed, looks we do not have an example yet. Thank you for your interest.

**Comment by KRONOS-11** [comment]
hey @schalkneethling , I've attempted to fix this issue in my [pull request](https://github.com/mdn/interactive-examples/pull/1509) , any feedback is appreciated.

**Comment by liuhao088** [comment]
yes

**Comment by wbamberg** [comment]
Closed via https://github.com/mdn/interactive-examples/pull/1509. Thanks @KRONOS-11 !
