### ISSUE TITLE
JS examples: need example for Array.shift()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#416]
-> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift

We should be able to use the existing example-on-top content, ported to interactive-examples. This means converting the content to match the style guide: https://github.com/mdn/interactive-examples/blob/master/JS-Example-Style-Guide.md as well as embedding it in an interactive example.

**Comment by wbamberg** [comment]
Sorry to reopen this, but I think there's one more thing that needs to be fixed: the variable returned from `shift()` is named `array2`, but it is not an array. It would be better to name it `element1`.

**Comment by schalkneethling** [comment]
> It would be better to name it element1.

Very good point @wbamberg

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/445
