### ISSUE TITLE
JS Examples: need example for Array.sort()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#418]
-> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

We should be able to use the existing example-on-top content, ported to interactive-examples. This means converting the content to match the style guide: https://github.com/mdn/interactive-examples/blob/master/JS-Example-Style-Guide.md as well as embedding it in an interactive example.

**Comment by diablero13** [comment]
I added example for Array.sort to the MDN [page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

**Comment by wbamberg** [comment]
Thanks @maddhruv and @diablero13 !
