### ISSUE TITLE
JS Examples: need example for Array.values()

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#423]
-> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values

We should be able to use the existing example-on-top content, ported to interactive-examples. This means converting the content to match the style guide: https://github.com/mdn/interactive-examples/blob/master/JS-Example-Style-Guide.md as well as embedding it in an interactive example.

**Comment by maddhruv** [comment]
hey, @wbamberg please look into this issue

- Google Chrome 63.0.3239.132

![screenshot from 2018-01-15 11-50-56](https://user-images.githubusercontent.com/18121502/34929544-7a970b92-f9ea-11e7-8c5c-f120fd27c8ef.png)

- Mozilla Firefox 57.0.4

![screenshot from 2018-01-15 11-55-01](https://user-images.githubusercontent.com/18121502/34929636-fec767f4-f9ea-11e7-95c4-797c7a4d4afb.png)

**Comment by wbamberg** [comment]
Oh you are right, it's not supported in these browsers, I missed this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values#Browser_compatibility.

I don't think it's worth having an interactive example for this method, given the current state of support.

This, together with the compat note for Firefox ("Available in Firefox Nightly only due to compatibility issues.") makes me wonder if this method should be marked experimental in the compat data. @Elchi3, what do you think?

**Comment by Elchi3** [comment]
Well, the API is fairly stable and part of ES6. We've tried to ship it, and will probably try again soon https://bugzilla.mozilla.org/show_bug.cgi?id=1420101#c8
When it ships, it will need doc updates and bcd updates anyway. I think the ddn process and its definition of done should include "Interactive example written/updated" so that this will get done at that point.
