### ISSUE TITLE
Adding demos for Array.some and Array.shift to MDN

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#443]
Examples for both `Array.some()` and `Array.shift()` have been contributed. We need to update the relevant pages on MDN with these new examples.

**Comment by diablero13** [comment]
I updated pages for [Array.some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) and [Array.shift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift) in MDN.

**Comment by wbamberg** [comment]
Thanks @diablero13 !
