### ISSUE TITLE
CSS examples: need example for border-style

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#467]
https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

We'd have to choose 6 representative values.

**Comment by mfluehr** [comment]
I can work on this. OOC, what do you mean by "have to," exactly? Is six the maximum number of examples that can be embedded on any page? (Knowing would help me with any future examples I work on.)

**Comment by wbamberg** [comment]
> what do you mean by "have to," exactly?

I mean that in a single instance of the editor, you can only fit 6 1-line choices (actually you can have more, but then you get a scrollbar, which we would really like to avoid).

So for example, for `transform`, although it can take many different keyword values, we chose 6 that seemed representative for the example: https://developer.mozilla.org/en-US/docs/Web/CSS/transform.

The case of `border-style` is similar.

>  Is six the maximum number of examples that can be embedded on any page? 

If "examples" here refers to instances of the editor, then currently 1 is the maximum number of examples you can have on a page.

We might look at changing this later on, but the main focus now is to provide simple clear examples at the top of the page. I think it's fine for us to use more traditional techniques for additional examples further down the page. Especially if the additional examples illustrate more complex usages, that then might need to supply more context (including, for example, complete visible HTML and CSS content) than the interactive examples provide.
