### ISSUE TITLE
CSS examples: need example for float

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#468]
https://developer.mozilla.org/en-US/docs/Web/CSS/float

It would make sense to omit inline-start and inline-end, since they are not well-supported.

It could have some text flowing round the floated element, like the example outcome: https://screenshots.firefox.com/URYmzgIb5J3l1X8Q/developer.mozilla.org (which will be replaced when the interactive example is ready).

**Comment by hidde** [comment]
I would like to do this one!

**Comment by rachelandrew** [comment]
Hi @hidde - could you let me know if you are still doing this? I'm about to do shape-outside, clear and so on and I could do this at the same time as it seems a bit odd to have clear, and shape-outside which relies on float, but not float!

**Comment by hidde** [comment]
@rachelandrew Oh yes, that makes sense, feel free to do float as well. 
 
Apologies, bad planning on my side meant I’ve had to postpone doing this a few times, should have updated this issue.

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/interactive-examples/pull/603/
