### ISSUE TITLE
CSS examples: need example for text-transform

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#469]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

It would be good to use one of the existing texts, such as the one for [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) or [padding](https://developer.mozilla.org/en-US/docs/Web/CSS/padding).

**Comment by mfluehr** [comment]
I'll work on it.
