### ISSUE TITLE
CSS examples: example needed for overflow-y

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#470]
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

It would be good to use one of the existing texts, such as the one for [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) or [padding](https://developer.mozilla.org/en-US/docs/Web/CSS/padding).

**Comment by mfluehr** [comment]
I'll work on this.
