### ISSUE TITLE
CSS data type examples

### ISSUE THREAD

**Issue by mfluehr** [mdn/interactive-examples#471]
I'm trying to create some examples for CSS data types, but it doesn't seem to be working for me. The issue appears to be with setting the `data-property` value in the HTML file. (For example, I can't seem to use "angle" or "&lt;angle&gt;".) Is it possible?

**Comment by wbamberg** [comment]
Yes, this `data-property` is used to test whether the thing is supported in the browser - if it isn't, the editor just displays a static version of the code (e.g. see https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink in Firefox compared to Chrome). I think [that code expects it to be a property](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink).

If we want to have examples for non-CSS properties, it would be good to make this code able to handle them.

But as a workaround, if the thing is well-supported among browsers (as `angle` is) you can just omit the `data-property`, and it should skip the check. Does that work?

**Comment by mfluehr** [comment]
Great, the workaround is fine by me. Feel free to close this issue if you don't feel the need to change the code to work with non-CSS properties.

**Comment by wbamberg** [comment]
We should have a bug for this, but just for clarity, I've filed a new one: https://github.com/mdn/interactive-examples/issues/476. Thanks for raising it.
