### ISSUE TITLE
Implement browser support detection for CSS constructs that aren't properties

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#476]
See https://github.com/mdn/interactive-examples/issues/471.

The code that figures out whether a thing is supported by the browser (https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/mce-utils.js#L41) assumes that the thing is a CSS property.

If we want to have examples for things that aren't properties, like functions or data types, it would be good to have a way to do the support check for them.

I don't think this is a very high priority, since there is a simple workaround for items that have good support (just omit the data-property attribute).

**Comment by kenrick95** [comment]
Same as https://github.com/mdn/interactive-examples/issues/534#issuecomment-364433848, maybe we could look into using [`CSS.supports()` function](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports).
