### ISSUE TITLE
CSS examples: example needed for list-style

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#484]
https://developer.mozilla.org/en-US/docs/Web/CSS/list-style

**Comment by danieldiaz14** [comment]
Dips on this!

**Comment by wbamberg** [comment]
Great! For inspiration you could look at the values in the gray PRE block at the start of the page. Of course you don't have to use the same values, but try to cover a similar range.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/interactive-examples/pull/547. Thanks @helmutgranda !
