### ISSUE TITLE
CSS examples: need examples for border-[top, right, bottom, left]-style

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#495]
These could just clone the border-style example that @mfluehr  wrote: https://developer.mozilla.org/en-US/docs/Web/CSS/border-style. The only difference would be of course that it only takes one argument, so the example could instead just focus on the different values it can take.

Hopefully it would be possible to use the [same CSS file](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/css/border-style.css), to make sure it stays consistent.

**Comment by mfluehr** [comment]
I'll work on this.
