### ISSUE TITLE
Typing "while(1){}" then clicking "Run" hangs the browser

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#50]
Note that e.g. codepen.io detects this kind of thing. I think they take a heuristic approach: like, it runs the example for a couple of seconds, then kills it if it is still running. I think this would be more robust than trying to detect all the ways someone could get into this situation.

**Comment by schalkneethling** [comment]
Implement[or use] a library that will sanitise the live code before executing it. Perhaps worth looking at existing editors such as CodePen and jsFiddle to determine if there are existing solutions before rolling our own.

**Comment by wbamberg** [comment]
Codepen does this by running the example for a few seconds, then killing it if it is still running. For example, if you just write a pen like this:

    for (let i = 0; i < 100000; i++) {
      console.log("blah")
    }

... you'll get the "infinite loop" error, and in the console a more nuanced message:

    "[CodePen]: An infinite loop (or a loop taking too long) was detected, so we stopped its execution. Sorry!"

I guess to do this we would run it in a worker. Do you think this might also make us a bit happier about using eval, since the code wouldn't get access to the iframe's DOM?

**Comment by wbamberg** [comment]
Adding release blocker label for the security question: is it acceptable for the editor to eval() user-entered JS, and if not which safer alternatives should we implement?

**Comment by schalkneethling** [comment]
Is this still a release blocker now that we are no longer using `eval`?

**Comment by wbamberg** [comment]
No :). If using Function addresses the security problems of eval, then this doesn't need to block.

**Comment by schalkneethling** [comment]
@wbamberg After having learned how codepen handles this, and that jsFiddle does not do anything to prevent users from running code like this, what do you say:

1. Keep it in the backlog as a nice to have, maybe, possibly, some day based on user feedback or,
2. Let's close this out and not worry about it.

Thanks!

**Comment by schalkneethling** [comment]
I am going to close this out. We can revisit in future should the need arise or a simple solution is found.
