### ISSUE TITLE
CSS examples: need examples for border-radius and associated properties

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#502]
We need an example for:
https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

Once that's done it should be possible to clone it for the corner-specific ones:

https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-left-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-right-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-left-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-right-radius

**Comment by helmutgranda** [comment]
@wbamberg do you see breaking each one of the corner-specific requests being part of their own branch or can the same branch be updated?

**Comment by wbamberg** [comment]
Hey @helmutgranda ! I think it would be fine to include the corner-specific properties in the same branch/PR :).

**Comment by helmutgranda** [comment]
Hey @wbamberg, thanks for merging the PR, can I just keep adding the other border options to the same branch? On pull #546 you can see that it has been "closed".

**Comment by wbamberg** [comment]
Sorry, I should have left it open. Please file a new PR for the other properties, in a new branch.

**Comment by wbamberg** [comment]
Fixed! https://github.com/mdn/interactive-examples/pull/553
