### ISSUE TITLE
Typo: Redundant line in "JavaScript Demo: Expressions - Comparison operators"

### ISSUE THREAD

**Issue by carmacleod** [mdn/interactive-examples#505]
The [Comparison operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) page has the following sample code in the code editor:
```
console.log(1 == 1);
// expected output: true

console.log("1" == 1);
// expected output: true

console.log(1 === 1);
// expected output: true

console.log("1" === 1);
// expected output: false
```

Note that the 1st and 3rd lines of code are exactly the same: `console.log(1 === 1);`
I believe the intent was for the 3rd line of code to be: `console.log("1" === "1");`

**Comment by wbamberg** [comment]
Thanks for filing!

But I think these are not the same. Line 1 is `1 == 1` (equality) and line 3 is `1 === 1` (strict equality).

They have the same result in this case because the types are the same (unlike `"1" == 1` and `"1" === 1`).

**Comment by carmacleod** [comment]
Oh, right. Missed that - glad you saw it.  Thanks! :)
