### ISSUE TITLE
Typo: "Equality Operators" example objects declared as value:key instead of key:value

### ISSUE THREAD

**Issue by carmacleod** [mdn/interactive-examples#506]
The "Equality Operators" section of the [Comparison operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) page has the following little example:
```
var object1 = {'value': 'key'}, object2 = {'value': 'key'}; 
object1 == object2 //false
```

I realize that it doesn't make any difference to the example, but the `'value': 'key'` objects look a bit strange. One would typically expect to see them declared as `'key': 'value'` or `key: 'value'`.
For example:
```
var object1 = {'key': 'value'}, object2 = {'key': 'value'}; 
object1 == object2 //false
```

**Comment by wbamberg** [comment]
Oh yes, good catch. I've updated the Wiki page, please let me know if it looks all right now.

**Comment by carmacleod** [comment]
Looks good - thanks!
