### ISSUE TITLE
CSS examples: need examples for border and border-[top, right, bottom, left]

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#507]
For inspiration, these could use the `border-*` examples already written by @mfluehr 

https://developer.mozilla.org/en-US/docs/Web/CSS/border-style
https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-style

https://developer.mozilla.org/en-US/docs/Web/CSS/border-width
https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-width

https://developer.mozilla.org/en-US/docs/Web/CSS/border-color
https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-color

**Comment by mfluehr** [comment]
I'll work on this.
