### ISSUE TITLE
Implement better "Run" button design for JS examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#51]
When we were working on these prototypes, @stephaniehobson came up with a design for the "Run" button where it was on the left of the output box, with an arrow pointing to the output box. You can see it in the second screenshot here: https://docs.google.com/document/d/1XabiVMF7Dng7nOzK3XLfvMn6JTEPM5KuFyUsMZbmkwM/edit.

I ever got around to implementing this, but we should.

**Comment by schalkneethling** [comment]
Design for reference:

<img width="625" alt="screen shot 2017-06-02 at 12 50 57" src="https://cloud.githubusercontent.com/assets/10350960/26722859/28e189ea-4792-11e7-8caa-a9b22336f28d.png">
