### ISSUE TITLE
text-decoration-skip-ink example appears broken

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/interactive-examples#528]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink

The interactive example on this pages doesn't look like its rendering properly. Just dropping an issue here so it doesn't get forgotten.

**Comment by danielhickman** [comment]
How so? I don't immediately see an issue. Is it the editor itself not showing up correctly or do you think it's an issue with the example code?

**Comment by chrisdavidmills** [comment]
Hrm, that is very weird - I've just tried it in Chrome, and it works just as expected.

In Firefox however the editor window does not show properly - you just see the two example declarations and nothing else.

Then again, my Firefox Nightly has been acting really strange of late. I'm gonna try reinstalling it.

**Comment by danielhickman** [comment]
No, I think that's intended. The support for that property is fairly sparse and the live editor doesn't activate if the property isn't supported by your browser. See [the CSS live editor code](https://github.com/mdn/interactive-examples/blob/1ac9f59ed600053410cc58573f6eaf7fbc31069f/js/editable-css.js#L80). It would be nice if it was cleaner or had image examples instead but that's another issue.

**Comment by wbamberg** [comment]
Yes, as @danielhickman says, it's because this property isn't supported in Firefox, so it displays a fallback. For the reverse, try https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break.

But I've been thinking lately that what it displays is not ideal.

>  that's another issue.

Agreed! -> https://github.com/mdn/interactive-examples/issues/532.

**Comment by chrisdavidmills** [comment]
Ah ha, thanks for the explanation. I did not know this ;-)

I've read#532, and yes, this sounds much better.

**Comment by danielhickman** [comment]
> For the reverse, try https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break.

Speaking of other issues, is creating another to discuss prefixing properties a good idea? I thought it would be smart for experimental technologies such as this one.

**Comment by wbamberg** [comment]
> Speaking of other issues, is creating another to discuss prefixing properties a good idea? I thought it would be smart for experimental technologies such as this one.

I think it's always fine to create issues for discussion :). It feels like there's a general cluster of issues around how to handle browser support, including:

* how to handle prefixed properties
* how to handle partially supported properties (i.e. when not all choices are supported)
* how to do support detection for things that aren't properties

Currently we just have `data-property` - it feels like we might need a more sophisticated way for an example to express the things the editor needs to test

**Comment by danielhickman** [comment]
I made a [new issue](534) for prefixing since that sounds like a good starting place. The title could be edited if the scope of the thread grows instead of braches as well.
