### ISSUE TITLE
Feature not supported case

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#53]
When a JS or CSS feature is not supported by the current browser we want to instead fallback to a static example. Need to decide whether we want to include a lib to handle the feature detection or, create a minimal lib that handles only known cases.

For this iteration, it was decided that if one of the examples is not supported, we fallback to static examples.

**Comment by schalkneethling** [comment]
Duplicate of https://github.com/mdn/interactive-examples/issues/33

**Comment by stephaniehobson** [comment]
The link to the compat tables was a nice idea (from #33). We can't be sure there is a compat table on the page though. We also couldn't link to the heading since those change for l10n but we can expect id="AutoCompatibilityTable" to be there.

**Comment by schalkneethling** [comment]
> The link to the compat tables was a nice idea (from #33). We can't be sure there is a compat table > on the page though. We also couldn't link to the heading since those change for l10n but we can 
> expect id="AutoCompatibilityTable" to be there.

Indeed so, we can check if the id exists, and if it does, show the link?

**Comment by stephaniehobson** [comment]
I don't think we can check that from inside the iframe. But we may able to append a query variable to the iframe src to communicate whether or not it is there. Not sure how much kumascript can look around the page when its parsing.

**Comment by schalkneethling** [comment]
Indeed, I was thinking that as well. Although, we may be able to use `postMessage` ~ https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
