### ISSUE TITLE
Use AWS/S3 for generated pages

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#54]
Currently generated pages are pushed to a `gh-pages` branch to be served via Github. This will not scale well so, we need to have a S3 bucket that these pages can be pushed to via Travis-CS

**Comment by schalkneethling** [comment]
Adding comments from original email thread here for ease of reference:

### Schalk

> Hey All,

> Stephanie brought up a good point during our discussion/review of the interactive examples repo. > As part of moving things to production ready code, and infra, are we going to continue to use ?Github pages as the mechanism for serving the samples or, was the plan to move the generated pages somewhere else? S3 perhaps?

### John

> Schalk is writing some new examples for MDN. I'm not sure where this code is, but my understanding is that there is a compiling step, and then plain files are served. It may be presented > on MDN as an iframe, and should be on a different domain.

> So, we have some options:

> * Install in SCL3 and serve by Apache on mdn.mozillademos.org
> * Serve from GitHub.io from the repo (I'm assuming in the mdn org)
> * Deploy to S3 and serve from a new domain.

> Do any of these options make it easier for the AWS move in the future?

### Schalk

> So the code lives here https://github.com/mdn/interactive-examples/

> The generated pages live here: https://github.com/mdn/interactive-examples/tree/gh-pages

> So, it can be served from Github pages or, the same/similar Travis job that currently generates these pages and then copies them to gh-pages can be changed to instead copy to S3[https://docs.travis-ci.com/user/deployment/s3/] if that makes more sense/makes things easier going forward.

### Josh

> You can get away with using github pages for low volume production, but there are limits[0] that make it a poor fit for potentially popular pages on MDN. I recommend starting off with github pages > for development/staging, and then we can use a CDN like Cloudfront for production.

> Specifically, I recommend transfer the interactive-examples repo to the mdn github org, enable github pages, and use https://mdn.github.io/interactive-examples as a staging domain. I prefer to use the docs subdir on the master branch[1] instead of a separate gh-pages branch[2], but you should feel free to set it up however works best for you. For dev/demo purposes you can still use your personal fork at https://schalknethling.github.io/interactive-examples (not currently working, probably a setting needs to be fixed in your repo-- see links below). 

> [0] https://help.github.com/articles/what-is-github-pages/#usage-limits
> [1] https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch
> [2] https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

**Comment by schalkneethling** [comment]
Had a meeting today with Kadir and one of the talking points was the work needed to host and serve the interactive examples from S3 as apposed to Github pages:

https://github.com/mdn/interactive-examples/issues/54#issuecomment-315131908 [Reference to original email thread is available at this URL]

Here are the current open questions

1. For a beta testing phase of the editors, will Github pages suffice?
2. For this same beta phase, would there be a real benefit to first complete the work on moving things to S3 as apposed to serving them from Github? The main concern here is over page load speed. The general feeling is that for the beta testing phase, using Github as the "back-end" will be sufficient. Is this correct?

Should the beta testing conclude successfully, and we decide to roll this out to all MDN users, we will definitely need to move to serving these pages via a S3 bucket with possibly CloudFront caching. So, should everyone feel comfortable using Github for the beta phase,

1. What is a fair estimated timeline to implement the S3/CloudFront work?
2. Do any of you have a date when you would be able to work on this?

**Comment by jgmize** [comment]
Note that while our most common setup for static pages and assets is s3+cloudfront, we can also use cloudfront with GitHub pages directly if that's easier.

**Comment by schalkneethling** [comment]
This is also being discussed here: https://github.com/mozmeao/infra/issues/362

**Comment by metadave** [comment]
my vote is for S3 instead of Github to keep our static sites consistent.

**Comment by schalkneethling** [comment]
Once this one[https://github.com/mdn/interactive-examples/pull/156] is merged, we can close this one \o/
