### ISSUE TITLE
Are we using IDs for CSS examples?

### ISSUE THREAD

**Issue by danielhickman** [mdn/interactive-examples#548]
Re: [#522 > review thread](https://github.com/mdn/interactive-examples/pull/522#discussion_r165218010)

Do we have uses for `#example_one` [etc] IDs for the CSS examples? I didn't see anything change when I removed them one an old fork after removing the `data-clipboard-target`s. I also didn't see anything in the code and was wondering if @schalkneethling knew off-hand.

*Sorry for another mention, I just think it got lost or will get lost in the comment thread inside the PR review.*

**Comment by schalkneethling** [comment]
@danielhickman Nope, it looks save to remove to me as well.
