### ISSUE TITLE
CSS examples: example needed for z-index

### ISSUE THREAD

**Issue by veekas** [mdn/interactive-examples#554]
https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by veekas** [comment]
@wbamberg: I hope you don't mind me creating this issue on my own. I wasn't sure how to indicate that I'll be working on this. If this isn't the right method, please let me know. Also, if that's the case, I can add a sentence to CONTRIBUTING.md to clarify the process for adding new issues.

**Comment by wbamberg** [comment]
@veekas: thanks for contributing!

z-index would be a great property to work on. If you look in the repo, you'll see that there already is [an example for z-index](https://interactive-examples.mdn.mozilla.net/pages/css/z-index.html), but I think it could definitely be improved:

* it doesn't work well at smaller screen widths
* it's very gray :)
* I'm not sure if the example is ideal

Alternatively, there's an example already [in the page](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index), that isn't interactive: 

<img width="563" alt="screen shot 2018-02-08 at 2 27 00 pm" src="https://user-images.githubusercontent.com/432915/36001718-2d9fbe1a-0cdc-11e8-8e26-b7adb43739f5.png">


So it shows overlapping boxes with `z-index: auto`, then shows how to change the "natural" order using `z-index`. So you could try to convert that one to interactive.

**Comment by wbamberg** [comment]
Also: I think filing a bug for items you want to take is a good idea, as it will help prevent people from bumping into each other :). So far I've not documented the process for finding items to document, mostly I guess because I think of that as a short-term thing (hopefully fairly soon we will be done with the spreadsheet :) but I've added a bit to the ["help wanted" post](https://discourse.mozilla.org/t/css-interactive-examples-help-wanted/24956) asking people to file issues for items they choose.

**Comment by veekas** [comment]
Thanks for the clarification, @wbamberg. Yesterday morning I took the existing example and [modified the CSS](https://github.com/veekas/interactive-examples/blob/master/live-examples/css-examples/transitions/z-index.css) to better accommodate smaller screen widths per the [CSS examples style guide](https://github.com/mdn/interactive-examples/blob/master/CSS-Example-Style-Guide.md#output-width-considerations). I also [modified the existing html](https://github.com/veekas/interactive-examples/blob/master/live-examples/css-examples/transitions/z-index.html) to better reflect the starter code laid out in CONTRIBUTING.md and adding a `div` around the z-indexed example elements to serve as a flexbox container. I didn't make the PR yesterday because I was trying to figure out why I was getting a merge conflict, but it was just because of [this PR removing example id attributes](https://github.com/mdn/interactive-examples/pull/556) on Thursday.

With that said, I'll refrain from submitting a PR in order to update the example to mirror the one currently on the z-index page. I think I should be able to have that done by end of day.

**Comment by veekas** [comment]
I was having trouble figuring out how to do this with one-line CSS declarations, but I came up with a couple options.

## Option 1
![option 1](https://i.imgur.com/AwaEbq0.jpg)

## Option 2
![option 2](https://i.imgur.com/f99SEow.jpg)

I'm partial to the second one, so I'll do a PR for it right now, but let me know if you'd prefer the first.

**Comment by wbamberg** [comment]
Thanks for your contribution @veekas ! I'll take a look but it might not be for a couple of days.
