### ISSUE TITLE
Change layout for CSS examples

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#56]
CSS examples will work much better with a side by side display. This issue tracks the implementation of side by side display for CSS examples with a fallback to examples on top, output at the bottom.

**Comment by stephaniehobson** [comment]
Notes from our in-person meeting:

We want the iframe to be inserted onto the page at different sizes depending on the available width on the page and based on the space necessary for the example. Unfortunately the iframe and the page it's on can't communicate about styling.

So we decided to use 3 different predefined widths, applied by passing a class into the macro when it is added to the page.

I would like us to add the class `live` to all the iframes and the modifier class `live-` for sizes.

    <iframe class="live live-small" src="....

The classes and corresponding *heights* are:

| single | side by side | class |
|---|---|---|
| 250px | 250px | live-small |
| 400px | 200px | |
| 600px | 400px | live-large |

I think the best way to decide how *wide* the space has to be before we flip to the side-by-side width is for @schalkneethling to look at the design and say what the minimum amount of necessary space is and then we can write the CSS declarations based on a combination of which columns the page has and how wide it is (this will get complicated).

**Comment by schalkneethling** [comment]
@stephaniehobson Did we want to default to `small` and so, we only need to set `live-large` when needed? or perhaps `live-tall`?

**Comment by schalkneethling** [comment]
Ok, so this is side by side at 210px

<img width="1005" alt="screen shot 2017-06-07 at 16 49 00" src="https://user-images.githubusercontent.com/10350960/26884949-6158cafa-4ba1-11e7-9147-d1d2b407adb3.png">

And this is side by side at 400px

<img width="996" alt="screen shot 2017-06-07 at 16 49 42" src="https://user-images.githubusercontent.com/10350960/26884960-6b3e17d2-4ba1-11e7-8cce-4cf573d09dc8.png">

**Comment by schalkneethling** [comment]
Another question here is whether:

1. We want to allow comment(I think they can be useful at times)
2. Limit these comments to only ever take up one line

Thoughts @stephaniehobson @wbamberg ?

**Comment by schalkneethling** [comment]
So, here is an example where there is more than 5 but, less than 10

<img width="1000" alt="screen shot 2017-06-07 at 17 33 56" src="https://user-images.githubusercontent.com/10350960/26887167-954a9202-4ba7-11e7-86af-ffec01e664e9.png">

**Comment by wbamberg** [comment]
>  We want to allow comment(I think they can be useful at times)

I think they can be useful if used carefully and quite sparingly. I don't want them to be the documentation :).

> Limit these comments to only ever take up one line

I think this is a good goal.

**Comment by schalkneethling** [comment]
Agreed, I added some comments to the README to reiterate this.
