### ISSUE TITLE
CSS examples: example needed for background

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#562]
https://developer.mozilla.org/en-US/docs/Web/CSS/background

This is quite a complex one I think. It might be worth looking at some of the related examples we've already done, like: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

It would also be worth writing examples for the other background-* properties at the same time, as they could share a lot of the design.

**Comment by mfluehr** [comment]
I'll take a stab at these. Wish me luck!
