### ISSUE TITLE
CSS examples: example needed for transform-origin

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#564]
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin

There's already a neat example in the page, that we could use as the basis of an interactive example:

<img width="704" alt="screen shot 2018-02-08 at 10 14 52 pm" src="https://user-images.githubusercontent.com/432915/36014236-8d5cc78a-0d1d-11e8-9c19-76cb9fb580fa.png">

...except that this example has a range of different transforms, while we should probably pick just one (e.g. `rotate`).

**Comment by mfluehr** [comment]
I'll work on this.
