### ISSUE TITLE
CSS examples: example needed for color

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#566]
https://developer.mozilla.org/en-US/docs/Web/CSS/color

We could use existing interactive examples like [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) for inspiration, as well as existing text examples like [font](https://developer.mozilla.org/en-US/docs/Web/CSS/font).

There's also a nice example in the page that we could interactivise:

<img width="713" alt="screen shot 2018-02-08 at 10 24 38 pm" src="https://user-images.githubusercontent.com/432915/36014488-e3be47c4-0d1e-11e8-88b1-2aaccf69ec12.png">

**Comment by benji1304** [comment]
Has this been done already? I'm reviewing the code in 
https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/color/color.html 

It looks like it was already added here
https://github.com/mdn/interactive-examples/commit/8736d6068a1b9a11cab89d0159062053ec3e8f66#diff-f7f95dcc42987f7979b62565b6eddd0a

**Comment by wbamberg** [comment]
Oh, so it was :). We wrote some examples last year, when we were still developing this thing. I think it could use some minor updates though:

* it has 8 example choices, and we'd prefer to keep to 6, so as to avoid scrollbars. We should choose the 6 most useful/interesting choices 
* it might be good to have a slightly more interesting initial choice than `currentColor` (in fact maybe we should remove the `currentColor` option?)
* we might want to use the same text as some of the [other text examples](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family), for consistency.

**Comment by benji1304** [comment]
I'll give it a go. The PR I submitted earlier was my first ever for MDN so I'll happily give this one a run through too.

**Comment by wbamberg** [comment]
Fixed! https://github.com/mdn/interactive-examples/pull/567
