### ISSUE TITLE
CSS examples: need example for font-stretch

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#573]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch

Syntactically this looks quite simple. The only tricky bit is finding a font that supports the stretched and condensed variants.

For consistency it would be good to base the example on one of the existing font examples:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
etc.

**Comment by akoliyot** [comment]
@wbamberg Can I help with this?

**Comment by wbamberg** [comment]
You certainly can @akoliyot ! Please take a look at the [contribution docs](https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING.md), and ask if you have any questions. Thanks!

**Comment by akoliyot** [comment]
@wbamberg Sorry, I haven't been able to find any fonts that would work with the font-stretch property. 

I found this: 
http://koe.berlin/variablefont/
But for now it's only working when setting the width like this: 
font-variation-settings: "wdth" 10;

I'll keep looking and update as soon as I find something.

**Comment by AreaOfAKite** [comment]
I will research applicable fonts.

**Comment by wbamberg** [comment]
@AreaOfAKite , I went through this a little while ago when updating the [`font-stretch`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch) page, and found [League Mono Variable](http://tylerfinck.com/leaguemonovariable/), which works very nicely :).

**Comment by ashvaibhav** [comment]
Looks like this issue can be closed now.
Examples are added in https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#Font_face_selection

**Comment by wbamberg** [comment]
> Looks like this issue can be closed now.

I don't think so: this issue is to add interactive examples, and there are no interactive examples for `font-stretch` in that page or in this repo.

**Comment by pillig3** [comment]
Gave this a try, it's working in Chrome (79.0) but not Firefox (73.0) nor Safari (12.1.2).
Those should support font-stretch; can anyone tell what's wrong with the code?

- https://github.com/mdn/interactive-examples/compare/master...pillig3:master

**Comment by wbamberg** [comment]
@pillig3 , thanks for your contribution! Your example works fine for me in both Firefox (73 and Nightly) and Safari (13). In what way is it not working for you? Do you get any console errors?

Also, @schalkneethling , does the linked example (https://github.com/mdn/interactive-examples/compare/master...pillig3:master) work for you?

**Comment by pillig3** [comment]
Interesting; I'm not getting any errors (other than a 404 for '/favicon.ico'). The element's style does change, but visually the text doesn't change–

![Screen Shot 2020-02-15 at 9 44 56 PM](https://user-images.githubusercontent.com/26679647/74598746-910c8c80-503c-11ea-9aa2-b82dd0239230.png)

**Comment by schalkneethling** [comment]
> @pillig3 , thanks for your contribution! Your example works fine for me in both Firefox (73 and Nightly) and Safari (13). In what way is it not working for you? Do you get any console errors?
> 
> Also, @schalkneethling , does the linked example ([master...pillig3:master](https://github.com/mdn/interactive-examples/compare/master...pillig3:master)) work for you?

Yes. Tested in Chrome, Firefox, Safari and Edge

**Comment by wbamberg** [comment]
Just to be clear, here's how it looks in Firefox 73 for me:

![font-stretch-firefox](https://user-images.githubusercontent.com/432915/74758482-3fc2ef80-522c-11ea-850a-43fc9d1bc1fd.gif)

**Comment by schalkneethling** [comment]
> Just to be clear, here's how it looks in Firefox 73 for me:
> 

same for me as well.

**Comment by pillig3** [comment]
Thanks for testing it! It's working for me also after re-downloading it, so I made a PR

**Comment by wbamberg** [comment]
Note, I closed https://github.com/mdn/interactive-examples/pull/1545 since it seems to be inactive, so this issue is open for anyone to take.
