### ISSUE TITLE
CSS examples: need example for widows

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#574]
https://developer.mozilla.org/en-US/docs/Web/CSS/widows

It might be good to use columns for this, so this example could use the columns examples as a basis: https://developer.mozilla.org/en-US/docs/Web/CSS/columns.

**Comment by ddbeck** [comment]
It appears that #639 is going to cover this.

**Comment by wbamberg** [comment]
> It appears that #639 is going to cover this.

Yes :)
