### ISSUE TITLE
CSS examples: examples needed for border-image-*

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#575]
We already have an example for the shorthand property: https://developer.mozilla.org/en-US/docs/Web/CSS/border-image.

But it would be worth:
* removing the comment lines
* adding more choices (without comment lines we would have space for 6 choices

I haven't looked in detail at whether we could design better example choices for this one.

Then we need an example for each of the sub-properties:
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-source
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-width
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-outset
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-repeat

Ideally they'd share the same basic setup, for consistency.

**Comment by mfluehr** [comment]
FWIW: I did a bunch of editing on these articles the other day, and something I realized was that border-image examples are very hard to understand without seeing the source image and knowing its dimensions. Maybe the interactive examples should include a link to the source image, as well as text describing its dimensions?

**Comment by wbamberg** [comment]
Yes, I agree. I think it might be tricky to include that in the example itself, what do you think about including it just in the MDN page, immediately after the example itself?

**Comment by mfluehr** [comment]
I'll go ahead and work on this.
