### ISSUE TITLE
HTML editor size adjustments

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#693]
HTML is pretty wordy. The `<table>` example we currently have overflows the editor. I think we should  do the same thing we do for JS examples, with support for a `taller` class: https://github.com/mdn/interactive-examples/issues/408.

23 lines or about that should be enough, and if it turns out not to be we could revisit. @schalkneethling , what do you think?

**Comment by schalkneethling** [comment]
Makes sense to me. Thanks for logging this @wbamberg

**Comment by schalkneethling** [comment]
I am introducing three classes that will be usable on the editor itself, as well as via the macro:

```
.tabbed-shorter # 300px
.tabbed-standard # 370px
.tabbed-tall # 670px
```
