### ISSUE TITLE
HTML examples: should the CSS be optional?

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#700]
I can omit the `cssExampleSrc` line in meta.json, but if I do, I get a CSS tab containing:

```
%example-css-src%
```

This seems like a bug. But I wonder, writing these, if we should omit any CSS unless it seems needed. If so, what should the editor do when no CSS is specified: Omit the CSS tab, or include it but make it empty? Probably the latter.

**Comment by NiedziolkaMichal** [comment]
I added fix to it in PR [#812](https://github.com/mdn/bob/pull/812).

**Comment by NiedziolkaMichal** [comment]
Fixed by #[812](https://github.com/mdn/bob/pull/812)
