### ISSUE TITLE
text-decoration-skip/text-decoration-skip-ink

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/interactive-examples#705]
text-decoration-skip needs an interactive example.
text-decoration-skip-ink has an interactive example, but it doesn't seem to display properly.

**Comment by wbamberg** [comment]
It's not exactly that it doesn't display properly, as that it's not supported in Firefox, and the editor's behavior in this case isn't very intuitive. We have https://github.com/mdn/interactive-examples/issues/532 filed to address this.

In the meantime I think we probably shouldn't have interactive examples for things that are not well-supported, so I have removed the interactive example from `text-decoration-skip-ink`.

**Comment by chrisdavidmills** [comment]
OK, sounds good. Thanks Will!

**Comment by wbamberg** [comment]
I was going to say, let's keep this open for text-decoration-skip, but that doesn't seem to be supported anywhere except Safari, so perhaps we're not ready for it yet?

**Comment by chrisdavidmills** [comment]
I think it might be in chrome too?

**Comment by wbamberg** [comment]
Then the compat data is wrong :)
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip#Browser_Compatibility

**Comment by chrisdavidmills** [comment]
Ah, that's it - it only supports a deprecated value.

**Comment by NiedziolkaMichal** [comment]
Example for [text-decoration-skip-ink](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink) is fully operational, while [text-decoration-skip](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip) support was removed from Chrome & never worked on firefox. I will close this issue as completed, thanks for reporting.
