### ISSUE TITLE
HTML examples: output escapes from its pane

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#706]
CSS added to the CSS pane are applied to the entire page, not just the output:

![html-examples-escape](https://user-images.githubusercontent.com/432915/38700234-3c396ab2-3e4f-11e8-9db2-ae22e9faddd1.gif)

Similarly, clicking links loads the page into the entire example, not just the output:

![html-examples-escape-2](https://user-images.githubusercontent.com/432915/38700256-4f063b0c-3e4f-11e8-9dce-7a3adcf19eb4.gif)

**Comment by a2sheppy** [comment]
Couldn't this be solved by just making it so the editing is in one iframe and the output is in a second iframe, and the editor periodically updates the HTML or CSS contained in the iframe? That shouldn't be hard to do, in theory, although I don't know details of the implementation already in place.

**Comment by chrisdavidmills** [comment]
Or could you do it so that the CSS applied to the output is put through an intermediary stage where it has a namespacing selector put at the start of the chain in each case, like .output-pane ?

**Comment by chrisdavidmills** [comment]
@a2sheppy yeah, I get it does get tricky at that point. I would love to find time to play with this.

**Comment by schalkneethling** [comment]
@a2sheppy I was thinking another iframe as well at first but, that means a different doc to use as the source. We also need to be sure we do not run into scripting issues where we are prevented from updating the CSS and HTML. Currently updates to this happens almost instantly(200ms delay once you stop typing) as you type.

While it is not impossible to generate two separate docs, it will make authoring and testing these locally... hard ;)

@chrisdavidmills I also thought of preprocessing but, once someone chains a couple of selectors i.e. `.class .another .another, .someother { ... }` things can quickly become fragile. We also need to constantly be aware of over all byte size to avoid performance issues.

One solution that would work great is using shadow DOM for the output but, unfortunately only Chrome has support for it currently :(

**Comment by schalkneethling** [comment]
The link portion of this is easy thankfully. I am simply going to attach an event listener to the output container and listen for any clicks on an anchor link that has a value that starts with at least `http`.

Once this happens, `preventDefault` and call `window.open(url);`

**Comment by chrisdavidmills** [comment]
> One solution that would work great is using shadow DOM for the output but, unfortunately only Chrome has support for it currently :(

Could you use Polymer to polyfill it? I guess performance is then an issue.

**Comment by schalkneethling** [comment]
@chrisdavidmills I will have a look at the weight it will add to the component. Thanks for the suggestion.

**Comment by a2sheppy** [comment]
Yet another reason to regret that shadow DOM has taken so long to get widely implemented.

Makes me wish the `<div>` element had a `sandbox` attribute, to allow you to tell the browser to basically treat it like a mini-iframe. :)

**Comment by schalkneethling** [comment]
Being worked on here: https://github.com/mdn/interactive-examples/issues/860 - Closing as duplicate.
