### ISSUE TITLE
"Reset" button obscures warning triangle

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#71]
From https://developer.mozilla.org/en-US/docs/User:schalkneethling:transform.

If you enter some invalid CSS, it shows a yellow "warning" triangle, but this appears underneath the "Reset" button, so you can't see it.

Maybe instead of the triangle, we could change the color of the (currently yellow, possibly green in future) border-right? To red? That would save us some space in the row, which would be handy.

**Comment by schalkneethling** [comment]
> Maybe instead of the triangle, we could change the color of the (currently yellow, possibly green in future) border-right? To red? That would save us some space in the row, which would be handy.

I like that idea. We could also set the border of the edit field to red as well to ensure the user notices that something is wrong. Thoughts @stephaniehobson

**Comment by schalkneethling** [comment]
@wbamberg If you agree with the behaviour introduced here:
https://github.com/mdn/interactive-examples/issues/73#issuecomment-312610290

Then we can go ahead and close this one as well.

**Comment by stephaniehobson** [comment]
I like these ideas :) Green right stripe, and red right stripe and border for an error. Bonus - the addition of the complete border changes the visual state in a way that aids colour blind users knowing something changed, 👍

**Comment by stephaniehobson** [comment]
Stripe appears to be on the left now. Also good :)

Can you switch it to `#4d9f0c` to match the new design colours?  [Full list of colour variables.](https://github.com/mozilla/kuma/blob/master/kuma/static/styles/includes/_vars.scss#L15)

**Comment by schalkneethling** [comment]
Done. https://github.com/mdn/interactive-examples/pull/95

**Comment by wbamberg** [comment]
I do take the point about color blind users, but I'm concerned that this is a bit too heavy as an indication. Think that people will see this error a lot, because it applies the CSS immediately, so if you're typing something it will appear "broken" until you have finished typing. I'm worried that something so string will scare people into thinking they've broken it, when they are just experimenting.

**Comment by schalkneethling** [comment]
@wbamberg We could remove the border that goes around the entire field, and just use the border on the side. We could also change the colour from red to yellow, to make it feel more like a warning, as apposed to an error.

**Comment by schalkneethling** [comment]
Duping in favour of https://github.com/mdn/interactive-examples/issues/103
