### ISSUE TITLE
In Firefox Nightly, the "Reset" button doesn't look like a button

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#72]
In my Firefox Nightly, the Reset button does what I want when I click it, but it doesn't get the "pressed" look when I click it. Also, if I double-click it, I get handles and can resize it!

http://imgur.com/a/h9f0j

I don't see this behavior in Chrome.

**Comment by schalkneethling** [comment]
> Also, if I double-click it, I get handles and can resize it!

What!? Is this a new feature, or a bug ¯\_(ツ)_/¯

**Comment by schalkneethling** [comment]
Using 56.0a1 (2017-07-03) (64-bit) I see the follow behaviour, which is as expected.

![fx-nightly-button](https://user-images.githubusercontent.com/10350960/27790752-2ca37db8-5ff2-11e7-9ec6-23a09afa78ee.gif)

I also do not see the double clicking behaviour. I am guessing it was a bug in that version.
