### ISSUE TITLE
[HTML Examples] Content sectioning ~ <h1>–<h6>: The HTML Section Heading elements

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#729]
Need an HTML example for the HTML section heading elements
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by schalkneethling** [comment]
Note: This issue is being worked on by a community member.

**Comment by MrBojangles** [comment]
like this?
<div>
  <h1>H1 Beetles</h1>
  <div style="margin-left: 10px;">
    <h2>H2 Etymology</h2>
  </div>
  <div style="margin-left: 10px;">
    <h2>H2 Distribution and Diversity</h2>
  </div>
  <div style="margin-left: 10px;">
    <h2>H2 Evolution</h2>
    <div style="margin-left: 10px;">
      <h3>H3 Late Paleozoic</h3>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Jurassic</h3>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Cretaceous</h3>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Cenozoic</h3>
    </div>
  </div>
  <div style="margin-left: 10px;">
    <h2>H2 External Morphology</h2>
    <div style="margin-left: 10px;">
      <h3>H3 Head</h3>
      <div style="margin-left: 10px;">
        <h4>H4 Mouthparts</h4>
      </div>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Thorax</h3>
      <div style="margin-left: 10px;">
        <h4>H4 Prothorax</h4>
      </div>
      <div style="margin-left: 10px;">
        <h4>H4 Pterothorax</h4>
      </div>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Legs</h3>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Wings</h3>
    </div>
    <div style="margin-left: 10px;">
      <h3>H3 Abdomen</h3>
    </div>
  </div>
</div>

**Comment by chrisdavidmills** [comment]
Just to be clear, and so that noone's time is wasted, I think @stephanmax is working on this one. I'll assign him.

**Comment by chrisdavidmills** [comment]
Ah, I can't assign him specifically...but at least we know now ;-)

**Comment by schalkneethling** [comment]
Thanks for the heads up @chrisdavidmills. There is currently an open PR from @a2sheppy for this issue:

https://github.com/mdn/interactive-examples/pull/911

Not sure if @stephanmax should incorporate the work from it, or whether @a2sheppy might want to fix up the items mentioned by @wbamberg and we can simply merge his original PR.

**Comment by chrisdavidmills** [comment]
@stephanmax feel free to file a new one, if you would find that easier.

**Comment by schalkneethling** [comment]
Hey All,

Are we going to close https://github.com/mdn/interactive-examples/pull/911 and https://github.com/mdn/interactive-examples/pull/1053 in favour of the work @stephanmax is doing?

I believe we should, as it is a bit confusing at the moment. Thanks to everyone who contributed here.

**Comment by chrisdavidmills** [comment]
@schalkneethling Yeah, makes sense.

**Comment by wbamberg** [comment]
@stephanmax , are you still planning to write this example? No worries at all if you don't the the time, just let us know so we can finish it off otherwise . And thanks for all the examples you have contributed already :).

**Comment by stephanmax** [comment]
Sorry about that, @wbamberg, bad timing during an intense phase on my side. On it now!

**Comment by TremaineNeethling** [comment]
I'm on this.
