### ISSUE TITLE
Rows with syntax errors stay highlighted after I move to another row

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#73]
If I click a row and edit the CSS, introducing an error, then click in a different row, then the row that had the error keeps its white background, so now there are two highlighted rows:

http://imgur.com/a/tgNhy

I don't think it should do this: there should only be one highlighted row at any time, and the "warning" icon should be hidden for non-highlighted rows

**Comment by schalkneethling** [comment]
@wbamberg I have changed the behaviour of the invalid state to be as follows, let me know your thoughts.

When an error occurs:

![screen shot 2017-07-03 at 12 27 16](https://user-images.githubusercontent.com/10350960/27789045-2da4748a-5feb-11e7-8bb1-d097e973649c.png)

After moving to another field whilst the previous is still in the invalid state:

![screen shot 2017-07-03 at 12 25 48](https://user-images.githubusercontent.com/10350960/27789059-40b87918-5feb-11e7-965e-d70b36d9c582.png)

**Comment by schalkneethling** [comment]
And yes, I still need to change the yellow to green ;)

**Comment by wbamberg** [comment]
I'm not sure about this. I think it's better to just hide any state associated with a row, when it is not active. But I'm open to persuasion.

**Comment by schalkneethling** [comment]
Duping in favour of https://github.com/mdn/interactive-examples/issues/103
