### ISSUE TITLE
[HTML Examples] Content sectioning ~ header

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#730]
Need an HTML example for the `header` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/789
