### ISSUE TITLE
[HTML Examples] Content sectioning ~ section

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#734]
Need an HTML example for the `section` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/888
