### ISSUE TITLE
[HTML Examples] Document metadata ~ link

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#737]
Need an HTML example for the `link` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by Elchi3** [comment]
Is this really suitable? I'm a bit unsure what demo interactively here. Ideas?

**Comment by Elchi3** [comment]
Ah, okay, I haven't realized the media folder yet. I think that would work, I will work on it. Thank you, Will!

**Comment by stephanmax** [comment]
I’m happy to work on this.

**Comment by stephanmax** [comment]
@wbamberg, this can be closed after PR #1029 got merged.
