### ISSUE TITLE
Tabbing through rows places the cursor oddly

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#74]
It's great that you can tab through the rows, but tabbing from a row to the next places the cursor on the line _before_ the CSS in the row after next. If you then start typing, you get unformatted text (although it is applied as CSS):

http://imgur.com/a/KAzE8

**Comment by schalkneethling** [comment]
Sounds like along the same lines as https://github.com/mdn/interactive-examples/issues/67
