### ISSUE TITLE
[HTML Examples] Forms ~ legend

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#748]
Need an HTML example for the `legend` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/795
