### ISSUE TITLE
[HTML Examples] Forms ~ meter

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#749]
Need an HTML example for the `meter` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/798
