### ISSUE TITLE
[HTML Examples] Forms ~ progress

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#752]
Need an HTML example for the `progress` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/801
