### ISSUE TITLE
[HTML Examples] Image and multimedia ~ audio

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#759]
Need an HTML example for the `audio` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by Elchi3** [comment]
I think this was already done in https://github.com/mdn/interactive-examples/pull/627

**Comment by wbamberg** [comment]
Yeah, this was done, but I just threw something together for user testing. It's worth someone taking a look to see if they can improve it, I think.

**Comment by stephanmax** [comment]
Would you mind me taking a look?

**Comment by wbamberg** [comment]
@stephanmax , I would not mind at all!
