### ISSUE TITLE
[HTML Examples] Inline text semantics ~ bdo

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#766]
Need an HTML example for the `bdo` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdo

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by schalkneethling** [comment]
Note: This is being worked on by a community member

**Comment by wbamberg** [comment]
This is done, isn't it? https://github.com/mdn/interactive-examples/pull/1041.

**Comment by schalkneethling** [comment]
@wbamberg Dang, you are correct
