### ISSUE TITLE
[HTML Examples] Inline text semantics ~ br

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#767]
Need an HTML example for the `br` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
Fixed -> https://github.com/mdn/interactive-examples/pull/828
