### ISSUE TITLE
"logger" instead of "console"

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#77]
Looking at https://developer.mozilla.org/en-US/docs/User:schalkneethling:push

The code sample has "logger.log()" not "console.log()". Is there a reason for this? I'd have thought console would be more obvious.

**Comment by schalkneethling** [comment]
> The code sample has "logger.log()" not "console.log()". Is there a reason for this? I'd have thought console would be more obvious.

I changed to `logger`. The reason is that should you try to actually `.log`, `.dir` or anything like that when debugging the live editor code, this override swallows it :-/

**Comment by wbamberg** [comment]
Yes, that makes sense. I don't know if you changed the implementation of `console`, but in the original it was pretty basic!

**Comment by wbamberg** [comment]
I'd like to reopen this. Feedback in our testing in SF was that "logger" was confusing. I think at least we should reconsider whether to use "console".

**Comment by schalkneethling** [comment]
@wbamberg Actually, the way I refactored the code, would allow us to do that now. The problem previously was that the variables and function were all exposed to the global object and so, our `console` was overriding the global `console`. I will make this change.

**Comment by schalkneethling** [comment]
No, I take that back. For it to work with the examples it needs to be exposed to the global object which means we will be overwriting the global console :-/

**Comment by schalkneethling** [comment]
Ok, never mind again ;) Turns out there is a way to have the best of both.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mdn/interactive-examples/pull/97
