### ISSUE TITLE
Add editor config file to help enforce our spacing standards

### ISSUE THREAD

**Issue by a2sheppy** [mdn/interactive-examples#778]
Since the source files here have different spacing standards than nearly everything else we do at Mozilla (where 2-space is pretty much universal), we should add an editorconfig file to help ensure that spacing winds up right in the sources created for the examples.

**Comment by a2sheppy** [comment]
Hm. There is one, but it's not working for me. Strange.

**Comment by schalkneethling** [comment]
@a2sheppy Which editor are you using?

**Comment by schalkneethling** [comment]
@a2sheppy I think I saw that you are using VS Code. I would recommend adding:https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by schalkneethling** [comment]
Closing this as we use Prettier to ensure appropriate formatting and eslint for JS. Both configurations for this are contained in the project.

For VSCode you should add: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

For Atom: https://github.com/prettier/prettier-atom
