### ISSUE TITLE
JS examples: transition is applied to the whole output box, not just the text

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#80]
It's great to have the transition when you click "Run", to signal that something is happening. But it's being applied to the whole output box, not just the output. So the whole box flickers when you press "Run". I think it would be better to apply the transition only to the text in the box.

**Comment by schalkneethling** [comment]
Agreed.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mdn/interactive-examples/pull/82
