### ISSUE TITLE
[HTML Examples] Web Components ~ template

### ISSUE THREAD

**Issue by a2sheppy** [mdn/interactive-examples#823]
Need an HTML example for the `template` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

## Contributing
https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

**Comment by wbamberg** [comment]
It's not clear how web component HTML elements can have usable examples without JS, so we've opted not to include interactive examples for them (as noted in https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=0).
