### ISSUE TITLE
Change examples to use 2-space tabs to be consistent with the rest of MDN

### ISSUE THREAD

**Issue by a2sheppy** [mdn/interactive-examples#825]
MDN has always used 2-space tabs (with the exception of some pages created by volunteers and never fixed). Using 4-space tabs in interactive examples is inconsistent and should be changed to match. Unless we intend to change to a 4-space standard and update content the other direction.

**Comment by schalkneethling** [comment]
We use Prettier to format all code. Kuma is also in the process of switching over to using Prettier and this is documented in MDN-Fiori.

4 space is for CSS and JS
2 spaces is for HTML
