### ISSUE TITLE
Local server not setting for checking contribution

### ISSUE THREAD

**Issue by Satyam-Bhalla** [mdn/interactive-examples#84]
I am getting an error while starting the node server for the interactive examples. My node version is 5.0.4 still my http-server is not working.
![error](https://user-images.githubusercontent.com/17814101/27637848-c45863de-5c2e-11e7-933f-8d85cbcf4349.JPG)

**Comment by schalkneethling** [comment]
Hey @Satyam-Bhalla - Apologies for only replying now. I am running Nodejs v7.4.0

I would definitely suggest that you upgrade. If you cannot upgrade system wide, you can use `nvm`[1] to create a virtual environment for the project and install the latest stable version of Nodejs.

Other than that, get the most recent code from master, then run:

```
npm run build
# followed by
npm start
```

[1] https://github.com/creationix/nvm

**Comment by Satyam-Bhalla** [comment]
@schalkneethling I am again getting this error when I use the 7.4.0 version. It is saying that there is a problem in the interactive-examples@1.0.0 start script.

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Just to confirm, after upgrading Nodejs and getting the latest from master, did you do a `npm install` at the root of the project directory?

**Comment by Satyam-Bhalla** [comment]
Yes, I did the same.I have tried that using 2 versions of angular 7.4.0 and with the latest 8x version.

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Please paste the output of your terminal after running `npm run build`, and then `npm start`. Thank you.

**Comment by Satyam-Bhalla** [comment]
![1st](https://user-images.githubusercontent.com/17814101/27870139-b8bf7436-61bf-11e7-9fd7-d26e0340a623.JPG)
![error1](https://user-images.githubusercontent.com/17814101/27870140-b90c65ac-61bf-11e7-8f1b-5dc74c097548.jpg)

**Comment by schalkneethling** [comment]
Oh ok, I see it is not the server that is the problem, it is chokidar. Strange that you get the error and I do not, let me have a look.

**Comment by Satyam-Bhalla** [comment]
Thanks for the help.It will help me to contribute.

**Comment by schalkneethling** [comment]
Ok @Satyam-Bhalla, grab the latest from master https://github.com/mdn/interactive-examples, and then you should only need to run `npm start` - I changed the configuration for chokidar, and whilst I could not reproduce your error, this config is much better.

Let me know how it goes. Thanks!

**Comment by Satyam-Bhalla** [comment]
Yes, now it is working fine.But when I only used 

> npm start

 it gives me the error of page not found when i open my http://127.0.0.1:8080. Then I used the previous method and now its working fine.

**Comment by Satyam-Bhalla** [comment]
Can you please tell me how can I contribute to this project like is there something that you need.In which I can contribute.

**Comment by schalkneethling** [comment]
@Satyam-Bhalla There are definitely ways you can contribute. Let me think about this for a bit a write up a proper doc, on which you can provide feedback. We can then take it from there.

Thank you so much for your interest, and please let us know if you run into any bugs or have any suggestions.

I am going to close out this issue but, I will create a new issue in which I will include you to figure out how to best make this project easy to contribute to.
