### ISSUE TITLE
[HTML Examples] Text content  <figcaption> 

### ISSUE THREAD

**Issue by dagolinuxoid** [mdn/interactive-examples#938]
At the moment the stage is 'Not started' so I can give it a try.

**Comment by dagolinuxoid** [comment]
@wbamberg, I've finished the example for figcaption and made pr few days ago — you can take a look and comment: is it ok or not. https://github.com/mdn/interactive-examples/pull/941

**Comment by wbamberg** [comment]
Fixed! -> https://github.com/mdn/interactive-examples/pull/941
