### ISSUE TITLE
Links should not open in the same browsing context

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#946]
Originally reported in https://github.com/mdn/interactive-examples/issues/706

Clicking links loads the page into the entire example, not just the output:

![html-examples-escape-2](https://user-images.githubusercontent.com/432915/38700256-4f063b0c-3e4f-11e8-9dce-7a3adcf19eb4.gif)

Suggested solution: https://github.com/mdn/interactive-examples/issues/706#issuecomment-382315508 sounds good!

**Comment by stephanmax** [comment]
I'd be happy to take on this one.

**Comment by schalkneethling** [comment]
@stephanmax You are most welcome to grab this one. Ensure you are on the latest from master, because the output is now in a shadow dom. Also, the UX we decided on is to simply open these links in a new tab. Thanks for your contributions.

**Comment by schalkneethling** [comment]
## Acceptance Criteria

Links inside the output area of the tabbed editor open in a new tab when clicked.

**Comment by schalkneethling** [comment]
@stephanmax Just a quick check-in. Are you actively working on this at the moment?

**Comment by stephanmax** [comment]
Hey @schalkneethling, thanks for the ping and sorry for the delay. Absolutely, I am on it. Please expect a PR by Friday.

**Comment by schalkneethling** [comment]
Hey @stephanmax, quick follow up on this one. While it is not a huge priority for us at the moment, I want to be sure it is not causing you any stress. If you are simply swamped with work/life, I am happy to take this one.

There will definitely always be work that you can contribute to in this project so, please do not feel bad if you need to drop this one. Thanks!

**Comment by schalkneethling** [comment]
@stephanmax No worries, thanks so much for sticking with it and the PR. I will review ASAP.
