### ISSUE TITLE
Create a wiki page on How, and What the community can contribute

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#99]
We have some interest from the greater community out there to contribute to this project, and this is great. Specifically want to call out @Satyam-Bhalla

This issue is to create a wiki page with clear documentation on how to contribute, and what would be needed.

**Comment by schalkneethling** [comment]
@Satyam-Bhalla if there is anything with regards to the current README[https://github.com/mdn/interactive-examples/blob/master/README.md] that you feel we can improve, please let us know here.

**Comment by Satyam-Bhalla** [comment]
@schalkneethling  I have found some more bugs like when I made a sample page according to your readme.md file.I didn't get any folder named docs in my browser and my server is giving me 404 error. But when I open my local directory after building my new page then I get that page (eg. Border radius) there. But your readme says that it must be found with the server too at localhost:8080/docs/pages/css/border-radius.html or http://127.0.0.1:8080/docs/pages/css/border-radius.html but it also gives me a 404 error.You can see that in my screenshots and must fix that error and also include that in your readme.
![capture](https://user-images.githubusercontent.com/17814101/27946461-92473edc-630f-11e7-99e5-abe06129e7ca.JPG)
![error2](https://user-images.githubusercontent.com/17814101/27946462-9247d07c-630f-11e7-9b21-87a365b3b3ea.jpg)

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Ah ok, so I guess you created a new page, with a new entry in `site.json`. I am thinking the `watch` task did not pick up these changes or, it picked up everything except for the change to `site.json`

Are you saying that after you ran `npm run build`, and then `npm start` the new page was available at the URL you expected?

**Comment by Satyam-Bhalla** [comment]
No, when I start my server it did not show me the docs folder as given in your readme.But I got the changes locally on my computer drive but did not get the folder at the localhost. So when I open my local drive the page is there with all the changes but my localhost did not serve that page or the docs folder. So the URL http://localhost/docs/pages/css/border-radius.html did not open.

**Comment by schalkneethling** [comment]
Ok, I think there may be a misunderstanding or, the README is not clear. Let me test the flow as described in the README and see if I can reproduce.

Thank you for your contribution and interest in the project @Satyam-Bhalla

**Comment by Satyam-Bhalla** [comment]
You can also check the above screenshots that show the error message in the console (GET \docs not found) @schalkneethling

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Please pull the latest code from `master` and let me know if you are still experiencing issues. Thank you.

**Comment by Satyam-Bhalla** [comment]
Yes the issues are still the same @schalkneethling

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Thank you for the feedback. This is odd. I will pull down a fresh copy of the latest from master and see if I can reproduce.

**Comment by schalkneethling** [comment]
@Satyam-Bhalla I see that you have forked this repo to your own user but, it seems the last time you synced with this main repo was 22 days ago.

This might be the cause of the problems you are seeing. As I do not know how well you know Git/Github. What you want to do is the following:

1. At the root of your local clone of your fork of the repository, add this repo as a remote:

```
git remote add mozilla https://github.com/mdn/interactive-examples.git
```

2. After the above, run:

```
git pull mozilla master
```

This will ensure that your fork of the repo is up to date with the master branch of this repo. Now, just to be safe, delete the directory `node_modules` and run:

```
npm install
```

3. Once this completes, try simply running:

```
npm start
```

Let me know the outcome of the above. Thank you again for your interest in contributing to this project.

**Comment by Satyam-Bhalla** [comment]
Yes, Its working fine now. I have checked the readme again and you have changed the path from http://127.0.0.1/docs to http://127.0.0.1/pages/css and now it's working. Thanks @schalkneethling

**Comment by schalkneethling** [comment]
@Satyam-Bhalla Wonderful news. I will be working on the wiki page today. Will update this issue as soon as that is done.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a wiki page on How, and What the community can contribute](https://trello.com/c/dpxWKRkH/5-create-a-wiki-page-on-how-and-what-the-community-can-contribute)
