### ISSUE TITLE
Add a build step to squash images

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#995]
We should already check in review that images are not too big, but it would be helpful to have a build step that automatically squashes images.

**Comment by wbamberg** [comment]
@schalkneethling , should I refile this on https://github.com/mdn/bob ? And is it covered by the work mentioned here: https://github.com/mdn/interactive-examples/pull/1191 "to compress all media assets during build"?

**Comment by wbamberg** [comment]
Refiled as https://github.com/mdn/bob/issues/175.

**Comment by peterbe** [comment]
Pardon my ignorance on this but wouldn't it be better to do this as a "lint step" as part of CI. 
If an image could be vastly optimized, it could break the build. 
Actually, out of curiosity I built a possible hack for this.

**Comment by wbamberg** [comment]
If it's a thing the machines can do for us by squashing automatically, why place the burden on contributors?

If the CI knows enough about what it wants here to give precise instructions to contributors, then surely the machines can just do this for us (as they do with prettier for example).

If the CI doesn't know enough to give precise instructions, then this seems like it will be very frustrating for contributors. I mean, if I just get "image could be squashed more" as a lint error, am I supposed to keep trying with various tools until the CI is happy with me?

**Comment by peterbe** [comment]
The image is part of the git so it'd be a bit weird if CI changed it. Will CI then also check in the new slimmed image into git?

A lot of organized projects have some sort of thing like this in their `package.json` scripts section for example:
```
    "lintcheck": "prettier *.js",
    "lintfix": "prettier --write *.js",
```
Then, in developer's git hooks or integrated into their IDE, they execute the `lintfix` because why should a human developer have to correct things a machine can do. 
But as a second line of defense, in case the local dev tooling isn't working exactly, in CI you then execute `lintcheck`. 
I like that pattern. 

We could have a little script that does something similar. When devs use their command line they can run `yarn run imageoptimize live-examples/mynew/image.png`, but in `.travis.yml` it can run `yarn run imageoptimize` which just checks.

**Comment by peterbe** [comment]
I ended up writing a simple tool. Its output looks like this:
```
▶ node imagesizecheck.js
WARNING live-examples/media/cc0-images/gecko-320-213.jpg was 8.4KB and could be 5.7KB (32.4% smaller) which is more than 15%
WARNING live-examples/media/examples/british-flag.png was 1.1KB and could be 0.8KB (30.1% smaller) which is more than 15%
ERROR   live-examples/media/examples/fish.png was 73.0KB and could be 21.4KB (70.6% smaller) which is more than 55%
ERROR   live-examples/media/examples/lizard.png was 42.5KB and could be 13.5KB (68.2% smaller) which is more than 55%
ERROR   live-examples/media/examples/mdn-info.png was 36.1KB and could be 11.9KB (66.9% smaller) which is more than 55%
ERROR   live-examples/media/examples/mdn-info2.png was 21.5KB and could be 7.5KB (65.2% smaller) which is more than 55%
ERROR   live-examples/media/examples/round-balloon-threshold.png was 39.9KB and could be 12.8KB (68.0% smaller) which is more than 55%
ERROR   live-examples/media/examples/round-balloon.png was 40.0KB and could be 12.9KB (67.7% smaller) which is more than 55%
WARNING live-examples/media/examples/star.png was 3.0KB and could be 1.6KB (44.9% smaller) which is more than 15%
3 images could be improved by at least 15%
6 images could be improved by at least 55%
```

I think it's scary to mess with other people's images. What if a particular .jpg is supposed to be large as that's the example. Or, perhaps an image needs to be expensively super-crisp and its value would be ruined if we ran `jpegtran`/`pngquant` on it. 

What my little hack script does is that it compresses all files into `/tmp/` then it compares the compressed file with the original and hence the warning/error depending on the file sizes of a pair of files. 

There could be a hint at the bottom of the output. E.g. 

```
To fix live-examples/media/examples/mdn-info2.png type:

  cp /tmp/live-examples-images/mdn-info2.png live-examples/media/examples/mdn-info2.png

and then git commit that change.
```
```

**Comment by peterbe** [comment]
Here's my hack by the way: https://github.com/mdn/interactive-examples/compare/master...peterbe:995-add-a-build-step-to-squash-images

**Comment by wbamberg** [comment]
Yes, I could see how this would be helpful. I like the idea of making it a hint and providing a squashed version that people can use if they choose.

**Comment by schalkneethling** [comment]
That is neat! It would indeed be a very nice touch if the command would ask the user at the end whether they want to commit as is or commit the optimized images.

**Comment by schalkneethling** [comment]
It won't crop, so that makes it safer, and we do not have to be overly aggressive with the compression level. In general, these images will not need to be super large as the output window is pretty small.

**Comment by peterbe** [comment]
Actually, suppose that we land this. One if you two gentlemen could take care and optimize every single existing image (that is mentioned in the warnings and errors output). That means that if someone comes with a new PR, only their newly added images would be potential for error.

**Comment by schalkneethling** [comment]
> Actually, suppose that we land this. One if you two gentlemen could take care and optimize every single existing image (that is mentioned in the warnings and errors output). That means that if someone comes with a new PR, only their newly added images would be potential for error.

I am happy to run ImgOptim over it and commit the changes. @wbamberg What do you think?
