### ISSUE TITLE
Remove image attribution footers

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#997]
At the moment we usually use images from unsplash.com and attribute them in a footer. The footer adds extra markup and CSS that distracts from the main point of the example. We should use public domain images and remove the footer.

## Acceptance criteria

- [x] Add assorted CC0 images to the IE repository that can be used by contributors
- [x] Examples that include images or other resources use public domain resources and don't contain an attribution footer.

**Comment by a2sheppy** [comment]
I think we should find and add to the site's repo a modest selection of assorted public domain images that we can choose among, and then update examples to select from those. They should be of a few different types of objects, with different contrast levels and sizes.

**Comment by a2sheppy** [comment]
PR #1082 adds the stock images.

**Comment by a2sheppy** [comment]
I’ve now merged PR #1082 and am in the process of creating PRs for each example that needs to be updated.
