### ISSUE TITLE
Finish HTML element examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#999]
There are still 7 HTML elements missing an example:

```
<h1>-<h6>
<link>
<style>
<a>
<bdi>
<bdo>
<figure>
```

## Acceptance criteria

All HTML elements have interactive examples, except those we have explicitly marked as not suitable for examples.

**Comment by wbamberg** [comment]
Sounds great @stephanmax . It would probably be good to have separate issues for each example, so more than one person can contribute examples. There are already issues for four of these examples, some of which have been started:

* [`<bdo>`](https://github.com/mdn/interactive-examples/issues/766) - this is currently unassigned, although @Elchi3 [started a PR for it](https://github.com/mdn/interactive-examples/pull/880), but it needs rework before it can be merged.

* [`<bdi>`](https://github.com/mdn/interactive-examples/issues/765) - same story as for `<bdo>`.

* [`<link>`](https://github.com/mdn/interactive-examples/issues/737) - currently unassigned, some discussion in the bug but no PR.

* [`<h1>–<h6>`](https://github.com/mdn/interactive-examples/pull/911) - currently unassigned, a PR filed with some outstanding review comments.

I think it would be fine to take any of the above, and either reuse any existing work or start again from scratch.

For the others:

* I just checked, and `<figure>` has actually been done.
* `<style>` has also been done, but has a bug that's preventing us adding it to the page. I just filed https://github.com/mdn/interactive-examples/issues/1013 for that.
* I just filed [an issue for `<a>`](https://github.com/mdn/interactive-examples/issues/1014), which hasn't been started at all. I think we were waiting for https://github.com/mdn/interactive-examples/issues/946 to be fixed, so thanks for fixing that :).

**Comment by chrisdavidmills** [comment]
`<bdi>` and `<bdo>` examples done: https://github.com/mdn/interactive-examples/pull/1041

**Comment by chrisdavidmills** [comment]
`<link>` example also done: https://github.com/mdn/interactive-examples/pull/1029

**Comment by stephanmax** [comment]
Cool, that only leaves `<h*>`, I think. I know there is a PR and I wasn't sure what the usual process is for those scenarios, but I am happy to jump in and finish that example.

**Comment by chrisdavidmills** [comment]
@stephanmax if you'd be willing to jump in and finish off the h1-h6 example, that would be much appreciated! Feel free to put me as a reviewer once you're done. Sheppy was working on it, but he has been pulled on to other things now.

In that case, I can move on to the HTML global attribute live examples.

**Comment by chrisdavidmills** [comment]
Oh, and just for the record, we also have an example in for `<a>`: https://github.com/mdn/interactive-examples/pull/1022

(Thanks again @stephanmax !)

**Comment by stephanmax** [comment]
My pleasure, @chrisdavidmills. Will get the `<h*>` example in.

**Comment by jmswisher** [comment]
Heading elements example is done and in-page
